/*
###############################################################
#  Generated by:      Cadence Innovus 17.11-s080_1
#  OS:                Linux x86_64(Host ID localhost.localdomain)
#  Generated on:      Sun Nov 21 13:47:05 2021
#  Design:            IIRfilter
#  Command:           saveNetlist IIRfilter.v
###############################################################
*/
/////////////////////////////////////////////////////////////
// Created by: Synopsys DC Expert(TM) in wire load mode
// Version   : O-2018.06-SP4
// Date      : Sun Nov 21 12:14:45 2021
/////////////////////////////////////////////////////////////
module IIRfilter (
	DIN, 
	H1, 
	H2, 
	H3, 
	VIN, 
	RST_n, 
	CLK, 
	DOUT, 
	VOUT);
   input [6:0] DIN;
   input [6:0] H1;
   input [6:0] H2;
   input [6:0] H3;
   input VIN;
   input RST_n;
   input CLK;
   output [6:0] DOUT;
   output VOUT;

   // Internal wires
   wire FE_DBTN6_w_reg_out_0;
   wire FE_DBTN5_w_reg_out_1;
   wire FE_DBTN4_w_reg_out_2;
   wire FE_DBTN3_w_reg_out_3;
   wire FE_DBTN2_w_reg_out_4;
   wire FE_DBTN1_w_reg_out_5;
   wire FE_DBTN0_w_reg_out_6;
   wire n1;
   wire n3;
   wire n4;
   wire n5;
   wire n6;
   wire n7;
   wire n8;
   wire n9;
   wire n10;
   wire n11;
   wire n12;
   wire n13;
   wire n14;
   wire n15;
   wire n16;
   wire n17;
   wire n18;
   wire n19;
   wire n20;
   wire n21;
   wire n22;
   wire n23;
   wire n24;
   wire n25;
   wire n26;
   wire n27;
   wire n28;
   wire n29;
   wire n30;
   wire n31;
   wire n40;
   wire ff_sh_6_;
   wire ff_sh_5_;
   wire ff_sh_4_;
   wire ff_sh_3_;
   wire ff_sh_2_;
   wire ff_sh_1_;
   wire ff_sh_0_;
   wire b0_w_9_;
   wire b0_w_8_;
   wire b0_w_7_;
   wire b0_w_6_;
   wire b0_w_12_;
   wire b0_w_11_;
   wire b0_w_10_;
   wire n42;
   wire n43;
   wire n44;
   wire n45;
   wire n46;
   wire n47;
   wire n48;
   wire n49;
   wire n50;
   wire sub_28_n8;
   wire sub_28_n7;
   wire sub_28_n6;
   wire sub_28_n5;
   wire sub_28_n4;
   wire sub_28_n3;
   wire sub_28_n2;
   wire sub_28_n1;
   wire mult_33_n208;
   wire mult_33_n207;
   wire mult_33_n206;
   wire mult_33_n205;
   wire mult_33_n204;
   wire mult_33_n203;
   wire mult_33_n202;
   wire mult_33_n201;
   wire mult_33_n200;
   wire mult_33_n199;
   wire mult_33_n198;
   wire mult_33_n197;
   wire mult_33_n189;
   wire mult_33_n188;
   wire mult_33_n187;
   wire mult_33_n186;
   wire mult_33_n185;
   wire mult_33_n184;
   wire mult_33_n183;
   wire mult_33_n182;
   wire mult_33_n181;
   wire mult_33_n180;
   wire mult_33_n179;
   wire mult_33_n136;
   wire mult_33_n135;
   wire mult_33_n134;
   wire mult_33_n133;
   wire mult_33_n131;
   wire mult_33_n129;
   wire mult_33_n128;
   wire mult_33_n127;
   wire mult_33_n126;
   wire mult_33_n125;
   wire mult_33_n124;
   wire mult_33_n123;
   wire mult_33_n121;
   wire mult_33_n120;
   wire mult_33_n119;
   wire mult_33_n118;
   wire mult_33_n117;
   wire mult_33_n116;
   wire mult_33_n115;
   wire mult_33_n114;
   wire mult_33_n113;
   wire mult_33_n112;
   wire mult_33_n111;
   wire mult_33_n110;
   wire mult_33_n109;
   wire mult_33_n108;
   wire mult_33_n107;
   wire mult_33_n106;
   wire mult_33_n105;
   wire mult_33_n103;
   wire mult_33_n102;
   wire mult_33_n101;
   wire mult_33_n100;
   wire mult_33_n99;
   wire mult_33_n98;
   wire mult_33_n97;
   wire mult_33_n96;
   wire mult_33_n95;
   wire mult_33_n94;
   wire mult_33_n93;
   wire mult_33_n91;
   wire mult_33_n90;
   wire mult_33_n89;
   wire mult_33_n88;
   wire mult_33_n87;
   wire mult_33_n86;
   wire mult_33_n84;
   wire mult_33_n83;
   wire mult_33_n82;
   wire mult_33_n81;
   wire mult_33_n80;
   wire mult_33_n79;
   wire mult_33_n78;
   wire mult_33_n77;
   wire mult_33_n76;
   wire mult_33_n75;
   wire mult_33_n74;
   wire mult_33_n73;
   wire mult_33_n72;
   wire mult_33_n71;
   wire mult_33_n70;
   wire mult_33_n69;
   wire mult_33_n68;
   wire mult_33_n67;
   wire mult_33_n66;
   wire mult_33_n65;
   wire mult_33_n64;
   wire mult_33_n63;
   wire mult_33_n62;
   wire mult_33_n61;
   wire mult_33_n60;
   wire mult_33_n59;
   wire mult_33_n58;
   wire mult_33_n57;
   wire mult_33_n56;
   wire mult_33_n55;
   wire mult_33_n54;
   wire mult_33_n52;
   wire mult_33_n51;
   wire mult_33_n50;
   wire mult_33_n49;
   wire mult_33_n48;
   wire mult_33_n47;
   wire mult_33_n46;
   wire mult_33_n45;
   wire mult_33_n44;
   wire mult_33_n43;
   wire mult_33_n42;
   wire mult_33_n41;
   wire mult_33_n40;
   wire mult_33_n39;
   wire mult_33_n38;
   wire mult_33_n37;
   wire mult_33_n36;
   wire mult_33_n35;
   wire mult_33_n34;
   wire mult_33_n33;
   wire mult_33_n32;
   wire mult_33_n31;
   wire mult_33_n30;
   wire mult_33_n29;
   wire mult_33_n28;
   wire mult_33_n27;
   wire mult_33_n26;
   wire mult_33_n25;
   wire mult_33_n24;
   wire mult_33_n23;
   wire mult_33_n22;
   wire mult_33_n21;
   wire mult_33_n20;
   wire mult_33_n19;
   wire mult_33_n18;
   wire mult_33_n17;
   wire mult_33_n16;
   wire mult_33_n15;
   wire mult_33_n8;
   wire mult_33_n7;
   wire mult_33_n6;
   wire mult_33_n5;
   wire mult_33_n4;
   wire mult_33_n3;
   wire mult_33_n2;
   wire mult_34_n208;
   wire mult_34_n207;
   wire mult_34_n206;
   wire mult_34_n205;
   wire mult_34_n204;
   wire mult_34_n203;
   wire mult_34_n202;
   wire mult_34_n201;
   wire mult_34_n200;
   wire mult_34_n199;
   wire mult_34_n198;
   wire mult_34_n197;
   wire mult_34_n189;
   wire mult_34_n188;
   wire mult_34_n187;
   wire mult_34_n186;
   wire mult_34_n185;
   wire mult_34_n184;
   wire mult_34_n183;
   wire mult_34_n182;
   wire mult_34_n181;
   wire mult_34_n180;
   wire mult_34_n179;
   wire mult_34_n136;
   wire mult_34_n135;
   wire mult_34_n134;
   wire mult_34_n133;
   wire mult_34_n131;
   wire mult_34_n129;
   wire mult_34_n128;
   wire mult_34_n127;
   wire mult_34_n126;
   wire mult_34_n125;
   wire mult_34_n124;
   wire mult_34_n123;
   wire mult_34_n121;
   wire mult_34_n120;
   wire mult_34_n119;
   wire mult_34_n118;
   wire mult_34_n117;
   wire mult_34_n116;
   wire mult_34_n115;
   wire mult_34_n114;
   wire mult_34_n113;
   wire mult_34_n112;
   wire mult_34_n111;
   wire mult_34_n110;
   wire mult_34_n109;
   wire mult_34_n108;
   wire mult_34_n107;
   wire mult_34_n106;
   wire mult_34_n105;
   wire mult_34_n103;
   wire mult_34_n102;
   wire mult_34_n101;
   wire mult_34_n100;
   wire mult_34_n99;
   wire mult_34_n98;
   wire mult_34_n97;
   wire mult_34_n96;
   wire mult_34_n95;
   wire mult_34_n94;
   wire mult_34_n93;
   wire mult_34_n91;
   wire mult_34_n90;
   wire mult_34_n89;
   wire mult_34_n88;
   wire mult_34_n87;
   wire mult_34_n86;
   wire mult_34_n84;
   wire mult_34_n83;
   wire mult_34_n82;
   wire mult_34_n81;
   wire mult_34_n80;
   wire mult_34_n79;
   wire mult_34_n78;
   wire mult_34_n77;
   wire mult_34_n76;
   wire mult_34_n75;
   wire mult_34_n74;
   wire mult_34_n73;
   wire mult_34_n72;
   wire mult_34_n71;
   wire mult_34_n70;
   wire mult_34_n69;
   wire mult_34_n68;
   wire mult_34_n67;
   wire mult_34_n66;
   wire mult_34_n65;
   wire mult_34_n64;
   wire mult_34_n63;
   wire mult_34_n62;
   wire mult_34_n61;
   wire mult_34_n60;
   wire mult_34_n59;
   wire mult_34_n58;
   wire mult_34_n57;
   wire mult_34_n56;
   wire mult_34_n55;
   wire mult_34_n54;
   wire mult_34_n52;
   wire mult_34_n51;
   wire mult_34_n50;
   wire mult_34_n49;
   wire mult_34_n48;
   wire mult_34_n47;
   wire mult_34_n46;
   wire mult_34_n45;
   wire mult_34_n44;
   wire mult_34_n43;
   wire mult_34_n42;
   wire mult_34_n41;
   wire mult_34_n40;
   wire mult_34_n39;
   wire mult_34_n38;
   wire mult_34_n37;
   wire mult_34_n36;
   wire mult_34_n35;
   wire mult_34_n34;
   wire mult_34_n33;
   wire mult_34_n32;
   wire mult_34_n31;
   wire mult_34_n30;
   wire mult_34_n29;
   wire mult_34_n28;
   wire mult_34_n27;
   wire mult_34_n26;
   wire mult_34_n25;
   wire mult_34_n24;
   wire mult_34_n23;
   wire mult_34_n22;
   wire mult_34_n21;
   wire mult_34_n20;
   wire mult_34_n19;
   wire mult_34_n18;
   wire mult_34_n17;
   wire mult_34_n16;
   wire mult_34_n15;
   wire mult_34_n8;
   wire mult_34_n7;
   wire mult_34_n6;
   wire mult_34_n5;
   wire mult_34_n4;
   wire mult_34_n3;
   wire mult_34_n2;
   wire mult_31_n208;
   wire mult_31_n207;
   wire mult_31_n206;
   wire mult_31_n205;
   wire mult_31_n204;
   wire mult_31_n203;
   wire mult_31_n202;
   wire mult_31_n201;
   wire mult_31_n200;
   wire mult_31_n199;
   wire mult_31_n198;
   wire mult_31_n197;
   wire mult_31_n196;
   wire mult_31_n195;
   wire mult_31_n194;
   wire mult_31_n193;
   wire mult_31_n192;
   wire mult_31_n191;
   wire mult_31_n190;
   wire mult_31_n189;
   wire mult_31_n188;
   wire mult_31_n187;
   wire mult_31_n186;
   wire mult_31_n185;
   wire mult_31_n184;
   wire mult_31_n183;
   wire mult_31_n182;
   wire mult_31_n181;
   wire mult_31_n180;
   wire mult_31_n179;
   wire mult_31_n136;
   wire mult_31_n135;
   wire mult_31_n134;
   wire mult_31_n133;
   wire mult_31_n131;
   wire mult_31_n129;
   wire mult_31_n128;
   wire mult_31_n127;
   wire mult_31_n126;
   wire mult_31_n125;
   wire mult_31_n124;
   wire mult_31_n123;
   wire mult_31_n121;
   wire mult_31_n120;
   wire mult_31_n119;
   wire mult_31_n118;
   wire mult_31_n117;
   wire mult_31_n116;
   wire mult_31_n115;
   wire mult_31_n114;
   wire mult_31_n113;
   wire mult_31_n112;
   wire mult_31_n111;
   wire mult_31_n110;
   wire mult_31_n109;
   wire mult_31_n108;
   wire mult_31_n107;
   wire mult_31_n106;
   wire mult_31_n105;
   wire mult_31_n103;
   wire mult_31_n102;
   wire mult_31_n101;
   wire mult_31_n100;
   wire mult_31_n99;
   wire mult_31_n98;
   wire mult_31_n97;
   wire mult_31_n96;
   wire mult_31_n95;
   wire mult_31_n94;
   wire mult_31_n93;
   wire mult_31_n91;
   wire mult_31_n90;
   wire mult_31_n89;
   wire mult_31_n88;
   wire mult_31_n87;
   wire mult_31_n86;
   wire mult_31_n84;
   wire mult_31_n83;
   wire mult_31_n82;
   wire mult_31_n81;
   wire mult_31_n80;
   wire mult_31_n79;
   wire mult_31_n78;
   wire mult_31_n77;
   wire mult_31_n76;
   wire mult_31_n75;
   wire mult_31_n74;
   wire mult_31_n73;
   wire mult_31_n72;
   wire mult_31_n71;
   wire mult_31_n70;
   wire mult_31_n69;
   wire mult_31_n68;
   wire mult_31_n67;
   wire mult_31_n66;
   wire mult_31_n65;
   wire mult_31_n64;
   wire mult_31_n63;
   wire mult_31_n62;
   wire mult_31_n61;
   wire mult_31_n60;
   wire mult_31_n59;
   wire mult_31_n58;
   wire mult_31_n57;
   wire mult_31_n56;
   wire mult_31_n55;
   wire mult_31_n54;
   wire mult_31_n52;
   wire mult_31_n51;
   wire mult_31_n50;
   wire mult_31_n49;
   wire mult_31_n48;
   wire mult_31_n47;
   wire mult_31_n46;
   wire mult_31_n45;
   wire mult_31_n44;
   wire mult_31_n43;
   wire mult_31_n42;
   wire mult_31_n41;
   wire mult_31_n40;
   wire mult_31_n39;
   wire mult_31_n38;
   wire mult_31_n37;
   wire mult_31_n36;
   wire mult_31_n35;
   wire mult_31_n34;
   wire mult_31_n33;
   wire mult_31_n32;
   wire mult_31_n31;
   wire mult_31_n30;
   wire mult_31_n29;
   wire mult_31_n28;
   wire mult_31_n27;
   wire mult_31_n26;
   wire mult_31_n25;
   wire mult_31_n24;
   wire mult_31_n23;
   wire mult_31_n22;
   wire mult_31_n21;
   wire mult_31_n20;
   wire mult_31_n19;
   wire mult_31_n18;
   wire mult_31_n17;
   wire mult_31_n16;
   wire mult_31_n15;
   wire mult_31_n8;
   wire mult_31_n7;
   wire mult_31_n6;
   wire mult_31_n5;
   wire mult_31_n4;
   wire mult_31_n3;
   wire mult_31_n2;
   wire add_32_n2;
   wire [6:0] fb_sh;
   wire [7:0] w;
   wire [6:0] DOUT_reg_in;
   wire [7:0] w_reg_out;
   wire [7:1] sub_28_carry;
   wire [6:2] add_32_carry;

   INV_X1 FE_DBTC6_w_reg_out_0 (.A(w_reg_out[0]),
	.ZN(FE_DBTN6_w_reg_out_0));
   INV_X1 FE_DBTC5_w_reg_out_1 (.A(w_reg_out[1]),
	.ZN(FE_DBTN5_w_reg_out_1));
   INV_X1 FE_DBTC4_w_reg_out_2 (.A(w_reg_out[2]),
	.ZN(FE_DBTN4_w_reg_out_2));
   INV_X1 FE_DBTC3_w_reg_out_3 (.A(w_reg_out[3]),
	.ZN(FE_DBTN3_w_reg_out_3));
   INV_X1 FE_DBTC2_w_reg_out_4 (.A(w_reg_out[4]),
	.ZN(FE_DBTN2_w_reg_out_4));
   INV_X1 FE_DBTC1_w_reg_out_5 (.A(w_reg_out[5]),
	.ZN(FE_DBTN1_w_reg_out_5));
   INV_X1 FE_DBTC0_w_reg_out_6 (.A(w_reg_out[6]),
	.ZN(FE_DBTN0_w_reg_out_6));
   DFFR_X1 VOUT_reg (.D(n40),
	.RN(RST_n),
	.CK(CLK),
	.Q(VOUT),
	.QN(n17));
   DFFR_X1 w_reg_out_reg_7_ (.D(n42),
	.RN(RST_n),
	.CK(CLK),
	.Q(w_reg_out[7]));
   DFFR_X1 w_reg_out_reg_6_ (.D(n43),
	.RN(RST_n),
	.CK(CLK),
	.Q(w_reg_out[6]));
   DFFR_X1 w_reg_out_reg_5_ (.D(n44),
	.RN(RST_n),
	.CK(CLK),
	.Q(w_reg_out[5]));
   DFFR_X1 w_reg_out_reg_4_ (.D(n45),
	.RN(RST_n),
	.CK(CLK),
	.Q(w_reg_out[4]));
   DFFR_X1 w_reg_out_reg_3_ (.D(n46),
	.RN(RST_n),
	.CK(CLK),
	.Q(w_reg_out[3]));
   DFFR_X1 w_reg_out_reg_2_ (.D(n47),
	.RN(RST_n),
	.CK(CLK),
	.Q(w_reg_out[2]));
   DFFR_X1 w_reg_out_reg_1_ (.D(n48),
	.RN(RST_n),
	.CK(CLK),
	.Q(w_reg_out[1]));
   DFFR_X1 w_reg_out_reg_0_ (.D(n49),
	.RN(RST_n),
	.CK(CLK),
	.Q(w_reg_out[0]));
   DFFR_X1 DOUT_reg_6_ (.D(n31),
	.RN(RST_n),
	.CK(CLK),
	.Q(DOUT[6]),
	.QN(n24));
   DFFR_X1 DOUT_reg_5_ (.D(n30),
	.RN(RST_n),
	.CK(CLK),
	.Q(DOUT[5]),
	.QN(n23));
   DFFR_X1 DOUT_reg_4_ (.D(n29),
	.RN(RST_n),
	.CK(CLK),
	.Q(DOUT[4]),
	.QN(n22));
   DFFR_X1 DOUT_reg_3_ (.D(n28),
	.RN(RST_n),
	.CK(CLK),
	.Q(DOUT[3]),
	.QN(n21));
   DFFR_X1 DOUT_reg_2_ (.D(n27),
	.RN(RST_n),
	.CK(CLK),
	.Q(DOUT[2]),
	.QN(n20));
   DFFR_X1 DOUT_reg_1_ (.D(n26),
	.RN(RST_n),
	.CK(CLK),
	.Q(DOUT[1]),
	.QN(n19));
   DFFR_X1 DOUT_reg_0_ (.D(n25),
	.RN(RST_n),
	.CK(CLK),
	.Q(DOUT[0]),
	.QN(n18));
   OAI21_X1 U35 (.A(n8),
	.B1(n22),
	.B2(VIN),
	.ZN(n29));
   NAND2_X1 U36 (.A1(DOUT_reg_in[4]),
	.A2(VIN),
	.ZN(n8));
   OAI21_X1 U37 (.A(n10),
	.B1(n24),
	.B2(VIN),
	.ZN(n31));
   NAND2_X1 U38 (.A1(DOUT_reg_in[6]),
	.A2(VIN),
	.ZN(n10));
   OAI21_X1 U39 (.A(n7),
	.B1(n21),
	.B2(VIN),
	.ZN(n28));
   NAND2_X1 U40 (.A1(DOUT_reg_in[3]),
	.A2(VIN),
	.ZN(n7));
   OAI21_X1 U41 (.A(n9),
	.B1(n23),
	.B2(VIN),
	.ZN(n30));
   NAND2_X1 U42 (.A1(DOUT_reg_in[5]),
	.A2(VIN),
	.ZN(n9));
   OAI21_X1 U43 (.A(n4),
	.B1(n18),
	.B2(VIN),
	.ZN(n25));
   NAND2_X1 U44 (.A1(DOUT_reg_in[0]),
	.A2(VIN),
	.ZN(n4));
   OAI21_X1 U45 (.A(n5),
	.B1(n19),
	.B2(VIN),
	.ZN(n26));
   NAND2_X1 U46 (.A1(DOUT_reg_in[1]),
	.A2(VIN),
	.ZN(n5));
   OAI21_X1 U47 (.A(n6),
	.B1(n20),
	.B2(VIN),
	.ZN(n27));
   NAND2_X1 U48 (.A1(DOUT_reg_in[2]),
	.A2(VIN),
	.ZN(n6));
   INV_X1 U49 (.A(n3),
	.ZN(n42));
   AOI22_X1 U50 (.A1(w_reg_out[7]),
	.A2(n50),
	.B1(w[7]),
	.B2(VIN),
	.ZN(n3));
   INV_X1 U51 (.A(n1),
	.ZN(n43));
   AOI22_X1 U52 (.A1(w_reg_out[6]),
	.A2(n50),
	.B1(w[6]),
	.B2(VIN),
	.ZN(n1));
   INV_X1 U53 (.A(n13),
	.ZN(n47));
   AOI22_X1 U54 (.A1(w_reg_out[2]),
	.A2(n50),
	.B1(w[2]),
	.B2(VIN),
	.ZN(n13));
   INV_X1 U55 (.A(n11),
	.ZN(n49));
   AOI22_X1 U56 (.A1(w_reg_out[0]),
	.A2(n50),
	.B1(w[0]),
	.B2(VIN),
	.ZN(n11));
   INV_X1 U57 (.A(n12),
	.ZN(n48));
   AOI22_X1 U58 (.A1(w_reg_out[1]),
	.A2(n50),
	.B1(w[1]),
	.B2(VIN),
	.ZN(n12));
   INV_X1 U59 (.A(n14),
	.ZN(n46));
   AOI22_X1 U60 (.A1(w_reg_out[3]),
	.A2(n50),
	.B1(w[3]),
	.B2(VIN),
	.ZN(n14));
   INV_X1 U61 (.A(n15),
	.ZN(n45));
   AOI22_X1 U62 (.A1(w_reg_out[4]),
	.A2(n50),
	.B1(w[4]),
	.B2(VIN),
	.ZN(n15));
   INV_X1 U63 (.A(n16),
	.ZN(n44));
   AOI22_X1 U64 (.A1(w_reg_out[5]),
	.A2(n50),
	.B1(w[5]),
	.B2(VIN),
	.ZN(n16));
   INV_X1 U65 (.A(VIN),
	.ZN(n50));
   NAND2_X1 U66 (.A1(n17),
	.A2(n50),
	.ZN(n40));
   XNOR2_X1 sub_28_U10 (.A(sub_28_n8),
	.B(DIN[0]),
	.ZN(w[0]));
   INV_X1 sub_28_U9 (.A(fb_sh[5]),
	.ZN(sub_28_n3));
   INV_X1 sub_28_U8 (.A(fb_sh[4]),
	.ZN(sub_28_n4));
   INV_X1 sub_28_U7 (.A(fb_sh[3]),
	.ZN(sub_28_n5));
   INV_X1 sub_28_U6 (.A(fb_sh[2]),
	.ZN(sub_28_n6));
   INV_X1 sub_28_U5 (.A(DIN[0]),
	.ZN(sub_28_n1));
   INV_X1 sub_28_U4 (.A(fb_sh[1]),
	.ZN(sub_28_n7));
   NAND2_X1 sub_28_U3 (.A1(fb_sh[0]),
	.A2(sub_28_n1),
	.ZN(sub_28_carry[1]));
   INV_X1 sub_28_U2 (.A(fb_sh[6]),
	.ZN(sub_28_n2));
   INV_X1 sub_28_U1 (.A(fb_sh[0]),
	.ZN(sub_28_n8));
   FA_X1 sub_28_U2_1 (.A(DIN[1]),
	.B(sub_28_n7),
	.CI(sub_28_carry[1]),
	.CO(sub_28_carry[2]),
	.S(w[1]));
   FA_X1 sub_28_U2_2 (.A(DIN[2]),
	.B(sub_28_n6),
	.CI(sub_28_carry[2]),
	.CO(sub_28_carry[3]),
	.S(w[2]));
   FA_X1 sub_28_U2_3 (.A(DIN[3]),
	.B(sub_28_n5),
	.CI(sub_28_carry[3]),
	.CO(sub_28_carry[4]),
	.S(w[3]));
   FA_X1 sub_28_U2_4 (.A(DIN[4]),
	.B(sub_28_n4),
	.CI(sub_28_carry[4]),
	.CO(sub_28_carry[5]),
	.S(w[4]));
   FA_X1 sub_28_U2_5 (.A(DIN[5]),
	.B(sub_28_n3),
	.CI(sub_28_carry[5]),
	.CO(sub_28_carry[6]),
	.S(w[5]));
   FA_X1 sub_28_U2_6 (.A(DIN[6]),
	.B(sub_28_n2),
	.CI(sub_28_carry[6]),
	.CO(sub_28_carry[7]),
	.S(w[6]));
   FA_X1 sub_28_U2_7 (.A(DIN[6]),
	.B(sub_28_n2),
	.CI(sub_28_carry[7]),
	.S(w[7]));
   NOR2_X1 mult_33_U203 (.A1(FE_DBTN0_w_reg_out_6),
	.A2(mult_33_n183),
	.ZN(mult_33_n100));
   NOR2_X1 mult_33_U202 (.A1(mult_33_n183),
	.A2(FE_DBTN1_w_reg_out_5),
	.ZN(mult_33_n101));
   NOR2_X1 mult_33_U201 (.A1(mult_33_n183),
	.A2(FE_DBTN2_w_reg_out_4),
	.ZN(mult_33_n102));
   NOR2_X1 mult_33_U200 (.A1(mult_33_n183),
	.A2(FE_DBTN3_w_reg_out_3),
	.ZN(mult_33_n103));
   NOR2_X1 mult_33_U199 (.A1(mult_33_n183),
	.A2(FE_DBTN5_w_reg_out_1),
	.ZN(mult_33_n105));
   NOR2_X1 mult_33_U198 (.A1(mult_33_n183),
	.A2(FE_DBTN6_w_reg_out_0),
	.ZN(mult_33_n106));
   NAND2_X1 mult_33_U197 (.A1(H1[3]),
	.A2(w_reg_out[7]),
	.ZN(mult_33_n107));
   NOR2_X1 mult_33_U196 (.A1(FE_DBTN0_w_reg_out_6),
	.A2(mult_33_n185),
	.ZN(mult_33_n108));
   NOR2_X1 mult_33_U195 (.A1(FE_DBTN1_w_reg_out_5),
	.A2(mult_33_n185),
	.ZN(mult_33_n109));
   NOR2_X1 mult_33_U194 (.A1(FE_DBTN2_w_reg_out_4),
	.A2(mult_33_n185),
	.ZN(mult_33_n110));
   NOR2_X1 mult_33_U193 (.A1(FE_DBTN3_w_reg_out_3),
	.A2(mult_33_n185),
	.ZN(mult_33_n111));
   NOR2_X1 mult_33_U192 (.A1(FE_DBTN4_w_reg_out_2),
	.A2(mult_33_n185),
	.ZN(mult_33_n112));
   NOR2_X1 mult_33_U191 (.A1(FE_DBTN5_w_reg_out_1),
	.A2(mult_33_n185),
	.ZN(mult_33_n113));
   NOR2_X1 mult_33_U190 (.A1(FE_DBTN6_w_reg_out_0),
	.A2(mult_33_n185),
	.ZN(mult_33_n114));
   NAND2_X1 mult_33_U189 (.A1(H1[2]),
	.A2(w_reg_out[7]),
	.ZN(mult_33_n115));
   NOR2_X1 mult_33_U188 (.A1(FE_DBTN0_w_reg_out_6),
	.A2(mult_33_n186),
	.ZN(mult_33_n116));
   NOR2_X1 mult_33_U187 (.A1(FE_DBTN1_w_reg_out_5),
	.A2(mult_33_n186),
	.ZN(mult_33_n117));
   NOR2_X1 mult_33_U186 (.A1(FE_DBTN2_w_reg_out_4),
	.A2(mult_33_n186),
	.ZN(mult_33_n118));
   NOR2_X1 mult_33_U185 (.A1(FE_DBTN3_w_reg_out_3),
	.A2(mult_33_n186),
	.ZN(mult_33_n119));
   NOR2_X1 mult_33_U184 (.A1(FE_DBTN4_w_reg_out_2),
	.A2(mult_33_n186),
	.ZN(mult_33_n120));
   NOR2_X1 mult_33_U183 (.A1(FE_DBTN5_w_reg_out_1),
	.A2(mult_33_n186),
	.ZN(mult_33_n121));
   NAND2_X1 mult_33_U182 (.A1(H1[1]),
	.A2(w_reg_out[7]),
	.ZN(mult_33_n123));
   NOR2_X1 mult_33_U181 (.A1(FE_DBTN0_w_reg_out_6),
	.A2(mult_33_n188),
	.ZN(mult_33_n124));
   NOR2_X1 mult_33_U180 (.A1(FE_DBTN1_w_reg_out_5),
	.A2(mult_33_n188),
	.ZN(mult_33_n125));
   NOR2_X1 mult_33_U179 (.A1(FE_DBTN2_w_reg_out_4),
	.A2(mult_33_n188),
	.ZN(mult_33_n126));
   NOR2_X1 mult_33_U178 (.A1(FE_DBTN3_w_reg_out_3),
	.A2(mult_33_n188),
	.ZN(mult_33_n127));
   NOR2_X1 mult_33_U177 (.A1(FE_DBTN4_w_reg_out_2),
	.A2(mult_33_n188),
	.ZN(mult_33_n128));
   NOR2_X1 mult_33_U176 (.A1(FE_DBTN5_w_reg_out_1),
	.A2(mult_33_n188),
	.ZN(mult_33_n129));
   NAND2_X1 mult_33_U175 (.A1(H1[0]),
	.A2(w_reg_out[7]),
	.ZN(mult_33_n131));
   NOR2_X1 mult_33_U174 (.A1(FE_DBTN1_w_reg_out_5),
	.A2(mult_33_n189),
	.ZN(mult_33_n133));
   NOR2_X1 mult_33_U173 (.A1(FE_DBTN2_w_reg_out_4),
	.A2(mult_33_n189),
	.ZN(mult_33_n134));
   NOR2_X1 mult_33_U172 (.A1(FE_DBTN3_w_reg_out_3),
	.A2(mult_33_n189),
	.ZN(mult_33_n135));
   NOR2_X1 mult_33_U171 (.A1(FE_DBTN4_w_reg_out_2),
	.A2(mult_33_n189),
	.ZN(mult_33_n136));
   NAND2_X1 mult_33_U170 (.A1(w_reg_out[2]),
	.A2(H1[5]),
	.ZN(mult_33_n54));
   NAND2_X1 mult_33_U169 (.A1(H1[0]),
	.A2(w_reg_out[6]),
	.ZN(mult_33_n208));
   NAND2_X1 mult_33_U168 (.A1(w_reg_out[2]),
	.A2(H1[4]),
	.ZN(mult_33_n207));
   NAND2_X1 mult_33_U167 (.A1(mult_33_n208),
	.A2(mult_33_n207),
	.ZN(mult_33_n63));
   XNOR2_X1 mult_33_U166 (.A(mult_33_n207),
	.B(mult_33_n208),
	.ZN(mult_33_n64));
   NOR4_X1 mult_33_U165 (.A1(mult_33_n188),
	.A2(mult_33_n189),
	.A3(FE_DBTN5_w_reg_out_1),
	.A4(FE_DBTN6_w_reg_out_0),
	.ZN(mult_33_n205));
   NOR2_X1 mult_33_U164 (.A1(mult_33_n186),
	.A2(FE_DBTN6_w_reg_out_0),
	.ZN(mult_33_n206));
   AOI222_X1 mult_33_U163 (.A1(mult_33_n84),
	.A2(mult_33_n205),
	.B1(mult_33_n206),
	.B2(mult_33_n84),
	.C1(mult_33_n206),
	.C2(mult_33_n205),
	.ZN(mult_33_n204));
   OAI222_X1 mult_33_U162 (.A1(mult_33_n204),
	.A2(mult_33_n187),
	.B1(mult_33_n187),
	.B2(mult_33_n184),
	.C1(mult_33_n204),
	.C2(mult_33_n184),
	.ZN(mult_33_n203));
   AOI222_X1 mult_33_U161 (.A1(mult_33_n203),
	.A2(mult_33_n74),
	.B1(mult_33_n203),
	.B2(mult_33_n76),
	.C1(mult_33_n76),
	.C2(mult_33_n74),
	.ZN(mult_33_n202));
   OAI222_X1 mult_33_U160 (.A1(mult_33_n202),
	.A2(mult_33_n179),
	.B1(mult_33_n202),
	.B2(mult_33_n182),
	.C1(mult_33_n182),
	.C2(mult_33_n179),
	.ZN(mult_33_n8));
   NAND2_X1 mult_33_U159 (.A1(w_reg_out[5]),
	.A2(H1[6]),
	.ZN(mult_33_n86));
   NAND2_X1 mult_33_U158 (.A1(w_reg_out[4]),
	.A2(H1[6]),
	.ZN(mult_33_n87));
   NAND2_X1 mult_33_U157 (.A1(w_reg_out[3]),
	.A2(H1[6]),
	.ZN(mult_33_n88));
   NAND2_X1 mult_33_U156 (.A1(w_reg_out[2]),
	.A2(H1[6]),
	.ZN(mult_33_n89));
   NAND2_X1 mult_33_U155 (.A1(w_reg_out[1]),
	.A2(H1[6]),
	.ZN(mult_33_n90));
   NAND2_X1 mult_33_U154 (.A1(w_reg_out[0]),
	.A2(H1[6]),
	.ZN(mult_33_n91));
   NOR2_X1 mult_33_U153 (.A1(mult_33_n180),
	.A2(FE_DBTN0_w_reg_out_6),
	.ZN(mult_33_n93));
   NOR2_X1 mult_33_U152 (.A1(mult_33_n180),
	.A2(FE_DBTN1_w_reg_out_5),
	.ZN(mult_33_n94));
   NOR2_X1 mult_33_U151 (.A1(mult_33_n180),
	.A2(FE_DBTN2_w_reg_out_4),
	.ZN(mult_33_n95));
   NOR2_X1 mult_33_U150 (.A1(mult_33_n180),
	.A2(FE_DBTN3_w_reg_out_3),
	.ZN(mult_33_n96));
   NOR2_X1 mult_33_U149 (.A1(mult_33_n180),
	.A2(FE_DBTN5_w_reg_out_1),
	.ZN(mult_33_n97));
   NOR2_X1 mult_33_U148 (.A1(mult_33_n180),
	.A2(FE_DBTN6_w_reg_out_0),
	.ZN(mult_33_n98));
   NAND2_X1 mult_33_U147 (.A1(H1[4]),
	.A2(w_reg_out[7]),
	.ZN(mult_33_n99));
   XNOR2_X1 mult_33_U146 (.A(mult_33_n2),
	.B(mult_33_n17),
	.ZN(mult_33_n201));
   XOR2_X1 mult_33_U145 (.A(mult_33_n201),
	.B(mult_33_n15),
	.Z(mult_33_n197));
   NAND2_X1 mult_33_U144 (.A1(H1[5]),
	.A2(w_reg_out[7]),
	.ZN(mult_33_n199));
   AND2_X1 mult_33_U143 (.A1(w_reg_out[6]),
	.A2(H1[6]),
	.ZN(mult_33_n200));
   XOR2_X1 mult_33_U142 (.A(mult_33_n199),
	.B(mult_33_n200),
	.Z(mult_33_n198));
   XOR2_X1 mult_33_U141 (.A(mult_33_n197),
	.B(mult_33_n198),
	.Z(fb_sh[6]));
   INV_X1 mult_33_U135 (.A(H1[0]),
	.ZN(mult_33_n189));
   INV_X1 mult_33_U133 (.A(H1[4]),
	.ZN(mult_33_n183));
   INV_X1 mult_33_U132 (.A(H1[5]),
	.ZN(mult_33_n180));
   INV_X1 mult_33_U130 (.A(H1[3]),
	.ZN(mult_33_n185));
   INV_X1 mult_33_U129 (.A(H1[2]),
	.ZN(mult_33_n186));
   INV_X1 mult_33_U128 (.A(H1[1]),
	.ZN(mult_33_n188));
   INV_X1 mult_33_U127 (.A(mult_33_n54),
	.ZN(mult_33_n181));
   INV_X1 mult_33_U126 (.A(mult_33_n80),
	.ZN(mult_33_n187));
   INV_X1 mult_33_U125 (.A(mult_33_n66),
	.ZN(mult_33_n179));
   INV_X1 mult_33_U124 (.A(mult_33_n73),
	.ZN(mult_33_n182));
   INV_X1 mult_33_U123 (.A(mult_33_n82),
	.ZN(mult_33_n184));
   HA_X1 mult_33_U51 (.A(mult_33_n129),
	.B(mult_33_n136),
	.CO(mult_33_n83),
	.S(mult_33_n84));
   HA_X1 mult_33_U50 (.A(mult_33_n114),
	.B(mult_33_n121),
	.CO(mult_33_n81),
	.S(mult_33_n82));
   FA_X1 mult_33_U49 (.A(mult_33_n128),
	.B(mult_33_n135),
	.CI(mult_33_n83),
	.CO(mult_33_n79),
	.S(mult_33_n80));
   HA_X1 mult_33_U48 (.A(mult_33_n106),
	.B(mult_33_n113),
	.CO(mult_33_n77),
	.S(mult_33_n78));
   FA_X1 mult_33_U47 (.A(mult_33_n120),
	.B(mult_33_n134),
	.CI(mult_33_n127),
	.CO(mult_33_n75),
	.S(mult_33_n76));
   FA_X1 mult_33_U46 (.A(mult_33_n78),
	.B(mult_33_n81),
	.CI(mult_33_n79),
	.CO(mult_33_n73),
	.S(mult_33_n74));
   HA_X1 mult_33_U45 (.A(mult_33_n98),
	.B(mult_33_n105),
	.CO(mult_33_n71),
	.S(mult_33_n72));
   FA_X1 mult_33_U44 (.A(mult_33_n112),
	.B(mult_33_n133),
	.CI(mult_33_n119),
	.CO(mult_33_n69),
	.S(mult_33_n70));
   FA_X1 mult_33_U43 (.A(mult_33_n77),
	.B(mult_33_n126),
	.CI(mult_33_n72),
	.CO(mult_33_n67),
	.S(mult_33_n68));
   FA_X1 mult_33_U42 (.A(mult_33_n70),
	.B(mult_33_n75),
	.CI(mult_33_n68),
	.CO(mult_33_n65),
	.S(mult_33_n66));
   FA_X1 mult_33_U39 (.A(mult_33_n97),
	.B(mult_33_n125),
	.CI(mult_33_n111),
	.CO(mult_33_n61),
	.S(mult_33_n62));
   FA_X1 mult_33_U38 (.A(mult_33_n91),
	.B(mult_33_n118),
	.CI(mult_33_n71),
	.CO(mult_33_n59),
	.S(mult_33_n60));
   FA_X1 mult_33_U37 (.A(mult_33_n69),
	.B(mult_33_n64),
	.CI(mult_33_n62),
	.CO(mult_33_n57),
	.S(mult_33_n58));
   FA_X1 mult_33_U36 (.A(mult_33_n60),
	.B(mult_33_n67),
	.CI(mult_33_n58),
	.CO(mult_33_n55),
	.S(mult_33_n56));
   FA_X1 mult_33_U34 (.A(mult_33_n103),
	.B(mult_33_n110),
	.CI(mult_33_n124),
	.CO(mult_33_n51),
	.S(mult_33_n52));
   FA_X1 mult_33_U33 (.A(mult_33_n131),
	.B(mult_33_n117),
	.CI(mult_33_n90),
	.CO(mult_33_n49),
	.S(mult_33_n50));
   FA_X1 mult_33_U32 (.A(mult_33_n63),
	.B(mult_33_n54),
	.CI(mult_33_n61),
	.CO(mult_33_n47),
	.S(mult_33_n48));
   FA_X1 mult_33_U31 (.A(mult_33_n52),
	.B(mult_33_n59),
	.CI(mult_33_n50),
	.CO(mult_33_n45),
	.S(mult_33_n46));
   FA_X1 mult_33_U30 (.A(mult_33_n48),
	.B(mult_33_n57),
	.CI(mult_33_n46),
	.CO(mult_33_n43),
	.S(mult_33_n44));
   FA_X1 mult_33_U29 (.A(mult_33_n102),
	.B(mult_33_n181),
	.CI(mult_33_n96),
	.CO(mult_33_n41),
	.S(mult_33_n42));
   FA_X1 mult_33_U28 (.A(mult_33_n116),
	.B(mult_33_n109),
	.CI(mult_33_n123),
	.CO(mult_33_n39),
	.S(mult_33_n40));
   FA_X1 mult_33_U27 (.A(mult_33_n51),
	.B(mult_33_n89),
	.CI(mult_33_n49),
	.CO(mult_33_n37),
	.S(mult_33_n38));
   FA_X1 mult_33_U26 (.A(mult_33_n40),
	.B(mult_33_n42),
	.CI(mult_33_n47),
	.CO(mult_33_n35),
	.S(mult_33_n36));
   FA_X1 mult_33_U25 (.A(mult_33_n38),
	.B(mult_33_n45),
	.CI(mult_33_n36),
	.CO(mult_33_n33),
	.S(mult_33_n34));
   FA_X1 mult_33_U24 (.A(mult_33_n95),
	.B(mult_33_n101),
	.CI(mult_33_n108),
	.CO(mult_33_n31),
	.S(mult_33_n32));
   FA_X1 mult_33_U23 (.A(mult_33_n88),
	.B(mult_33_n115),
	.CI(mult_33_n41),
	.CO(mult_33_n29),
	.S(mult_33_n30));
   FA_X1 mult_33_U22 (.A(mult_33_n32),
	.B(mult_33_n39),
	.CI(mult_33_n37),
	.CO(mult_33_n27),
	.S(mult_33_n28));
   FA_X1 mult_33_U21 (.A(mult_33_n35),
	.B(mult_33_n30),
	.CI(mult_33_n28),
	.CO(mult_33_n25),
	.S(mult_33_n26));
   FA_X1 mult_33_U20 (.A(mult_33_n94),
	.B(mult_33_n100),
	.CI(mult_33_n107),
	.CO(mult_33_n23),
	.S(mult_33_n24));
   FA_X1 mult_33_U19 (.A(mult_33_n31),
	.B(mult_33_n87),
	.CI(mult_33_n24),
	.CO(mult_33_n21),
	.S(mult_33_n22));
   FA_X1 mult_33_U18 (.A(mult_33_n27),
	.B(mult_33_n29),
	.CI(mult_33_n22),
	.CO(mult_33_n19),
	.S(mult_33_n20));
   FA_X1 mult_33_U17 (.A(mult_33_n99),
	.B(mult_33_n93),
	.CI(mult_33_n86),
	.CO(mult_33_n17),
	.S(mult_33_n18));
   FA_X1 mult_33_U16 (.A(mult_33_n18),
	.B(mult_33_n23),
	.CI(mult_33_n21),
	.CO(mult_33_n15),
	.S(mult_33_n16));
   FA_X1 mult_33_U8 (.A(mult_33_n56),
	.B(mult_33_n65),
	.CI(mult_33_n8),
	.CO(mult_33_n7),
	.S(fb_sh[0]));
   FA_X1 mult_33_U7 (.A(mult_33_n44),
	.B(mult_33_n55),
	.CI(mult_33_n7),
	.CO(mult_33_n6),
	.S(fb_sh[1]));
   FA_X1 mult_33_U6 (.A(mult_33_n34),
	.B(mult_33_n43),
	.CI(mult_33_n6),
	.CO(mult_33_n5),
	.S(fb_sh[2]));
   FA_X1 mult_33_U5 (.A(mult_33_n26),
	.B(mult_33_n33),
	.CI(mult_33_n5),
	.CO(mult_33_n4),
	.S(fb_sh[3]));
   FA_X1 mult_33_U4 (.A(mult_33_n20),
	.B(mult_33_n25),
	.CI(mult_33_n4),
	.CO(mult_33_n3),
	.S(fb_sh[4]));
   FA_X1 mult_33_U3 (.A(mult_33_n19),
	.B(mult_33_n16),
	.CI(mult_33_n3),
	.CO(mult_33_n2),
	.S(fb_sh[5]));
   NOR2_X1 mult_34_U203 (.A1(FE_DBTN0_w_reg_out_6),
	.A2(mult_34_n183),
	.ZN(mult_34_n100));
   NOR2_X1 mult_34_U202 (.A1(mult_34_n183),
	.A2(FE_DBTN1_w_reg_out_5),
	.ZN(mult_34_n101));
   NOR2_X1 mult_34_U201 (.A1(mult_34_n183),
	.A2(FE_DBTN2_w_reg_out_4),
	.ZN(mult_34_n102));
   NOR2_X1 mult_34_U200 (.A1(mult_34_n183),
	.A2(FE_DBTN3_w_reg_out_3),
	.ZN(mult_34_n103));
   NOR2_X1 mult_34_U199 (.A1(mult_34_n183),
	.A2(FE_DBTN5_w_reg_out_1),
	.ZN(mult_34_n105));
   NOR2_X1 mult_34_U198 (.A1(mult_34_n183),
	.A2(FE_DBTN6_w_reg_out_0),
	.ZN(mult_34_n106));
   NAND2_X1 mult_34_U197 (.A1(H3[3]),
	.A2(w_reg_out[7]),
	.ZN(mult_34_n107));
   NOR2_X1 mult_34_U196 (.A1(FE_DBTN0_w_reg_out_6),
	.A2(mult_34_n185),
	.ZN(mult_34_n108));
   NOR2_X1 mult_34_U195 (.A1(FE_DBTN1_w_reg_out_5),
	.A2(mult_34_n185),
	.ZN(mult_34_n109));
   NOR2_X1 mult_34_U194 (.A1(FE_DBTN2_w_reg_out_4),
	.A2(mult_34_n185),
	.ZN(mult_34_n110));
   NOR2_X1 mult_34_U193 (.A1(FE_DBTN3_w_reg_out_3),
	.A2(mult_34_n185),
	.ZN(mult_34_n111));
   NOR2_X1 mult_34_U192 (.A1(FE_DBTN4_w_reg_out_2),
	.A2(mult_34_n185),
	.ZN(mult_34_n112));
   NOR2_X1 mult_34_U191 (.A1(FE_DBTN5_w_reg_out_1),
	.A2(mult_34_n185),
	.ZN(mult_34_n113));
   NOR2_X1 mult_34_U190 (.A1(FE_DBTN6_w_reg_out_0),
	.A2(mult_34_n185),
	.ZN(mult_34_n114));
   NAND2_X1 mult_34_U189 (.A1(H3[2]),
	.A2(w_reg_out[7]),
	.ZN(mult_34_n115));
   NOR2_X1 mult_34_U188 (.A1(FE_DBTN0_w_reg_out_6),
	.A2(mult_34_n186),
	.ZN(mult_34_n116));
   NOR2_X1 mult_34_U187 (.A1(FE_DBTN1_w_reg_out_5),
	.A2(mult_34_n186),
	.ZN(mult_34_n117));
   NOR2_X1 mult_34_U186 (.A1(FE_DBTN2_w_reg_out_4),
	.A2(mult_34_n186),
	.ZN(mult_34_n118));
   NOR2_X1 mult_34_U185 (.A1(FE_DBTN3_w_reg_out_3),
	.A2(mult_34_n186),
	.ZN(mult_34_n119));
   NOR2_X1 mult_34_U184 (.A1(FE_DBTN4_w_reg_out_2),
	.A2(mult_34_n186),
	.ZN(mult_34_n120));
   NOR2_X1 mult_34_U183 (.A1(FE_DBTN5_w_reg_out_1),
	.A2(mult_34_n186),
	.ZN(mult_34_n121));
   NAND2_X1 mult_34_U182 (.A1(H3[1]),
	.A2(w_reg_out[7]),
	.ZN(mult_34_n123));
   NOR2_X1 mult_34_U181 (.A1(FE_DBTN0_w_reg_out_6),
	.A2(mult_34_n188),
	.ZN(mult_34_n124));
   NOR2_X1 mult_34_U180 (.A1(FE_DBTN1_w_reg_out_5),
	.A2(mult_34_n188),
	.ZN(mult_34_n125));
   NOR2_X1 mult_34_U179 (.A1(FE_DBTN2_w_reg_out_4),
	.A2(mult_34_n188),
	.ZN(mult_34_n126));
   NOR2_X1 mult_34_U178 (.A1(FE_DBTN3_w_reg_out_3),
	.A2(mult_34_n188),
	.ZN(mult_34_n127));
   NOR2_X1 mult_34_U177 (.A1(FE_DBTN4_w_reg_out_2),
	.A2(mult_34_n188),
	.ZN(mult_34_n128));
   NOR2_X1 mult_34_U176 (.A1(FE_DBTN5_w_reg_out_1),
	.A2(mult_34_n188),
	.ZN(mult_34_n129));
   NAND2_X1 mult_34_U175 (.A1(H3[0]),
	.A2(w_reg_out[7]),
	.ZN(mult_34_n131));
   NOR2_X1 mult_34_U174 (.A1(FE_DBTN1_w_reg_out_5),
	.A2(mult_34_n189),
	.ZN(mult_34_n133));
   NOR2_X1 mult_34_U173 (.A1(FE_DBTN2_w_reg_out_4),
	.A2(mult_34_n189),
	.ZN(mult_34_n134));
   NOR2_X1 mult_34_U172 (.A1(FE_DBTN3_w_reg_out_3),
	.A2(mult_34_n189),
	.ZN(mult_34_n135));
   NOR2_X1 mult_34_U171 (.A1(FE_DBTN4_w_reg_out_2),
	.A2(mult_34_n189),
	.ZN(mult_34_n136));
   NAND2_X1 mult_34_U170 (.A1(w_reg_out[2]),
	.A2(H3[5]),
	.ZN(mult_34_n54));
   NAND2_X1 mult_34_U169 (.A1(H3[0]),
	.A2(w_reg_out[6]),
	.ZN(mult_34_n208));
   NAND2_X1 mult_34_U168 (.A1(w_reg_out[2]),
	.A2(H3[4]),
	.ZN(mult_34_n207));
   NAND2_X1 mult_34_U167 (.A1(mult_34_n208),
	.A2(mult_34_n207),
	.ZN(mult_34_n63));
   XNOR2_X1 mult_34_U166 (.A(mult_34_n207),
	.B(mult_34_n208),
	.ZN(mult_34_n64));
   NOR4_X1 mult_34_U165 (.A1(mult_34_n188),
	.A2(mult_34_n189),
	.A3(FE_DBTN5_w_reg_out_1),
	.A4(FE_DBTN6_w_reg_out_0),
	.ZN(mult_34_n205));
   NOR2_X1 mult_34_U164 (.A1(mult_34_n186),
	.A2(FE_DBTN6_w_reg_out_0),
	.ZN(mult_34_n206));
   AOI222_X1 mult_34_U163 (.A1(mult_34_n84),
	.A2(mult_34_n205),
	.B1(mult_34_n206),
	.B2(mult_34_n84),
	.C1(mult_34_n206),
	.C2(mult_34_n205),
	.ZN(mult_34_n204));
   OAI222_X1 mult_34_U162 (.A1(mult_34_n204),
	.A2(mult_34_n187),
	.B1(mult_34_n187),
	.B2(mult_34_n184),
	.C1(mult_34_n204),
	.C2(mult_34_n184),
	.ZN(mult_34_n203));
   AOI222_X1 mult_34_U161 (.A1(mult_34_n203),
	.A2(mult_34_n74),
	.B1(mult_34_n203),
	.B2(mult_34_n76),
	.C1(mult_34_n76),
	.C2(mult_34_n74),
	.ZN(mult_34_n202));
   OAI222_X1 mult_34_U160 (.A1(mult_34_n202),
	.A2(mult_34_n179),
	.B1(mult_34_n202),
	.B2(mult_34_n182),
	.C1(mult_34_n182),
	.C2(mult_34_n179),
	.ZN(mult_34_n8));
   NAND2_X1 mult_34_U159 (.A1(w_reg_out[5]),
	.A2(H3[6]),
	.ZN(mult_34_n86));
   NAND2_X1 mult_34_U158 (.A1(w_reg_out[4]),
	.A2(H3[6]),
	.ZN(mult_34_n87));
   NAND2_X1 mult_34_U157 (.A1(w_reg_out[3]),
	.A2(H3[6]),
	.ZN(mult_34_n88));
   NAND2_X1 mult_34_U156 (.A1(w_reg_out[2]),
	.A2(H3[6]),
	.ZN(mult_34_n89));
   NAND2_X1 mult_34_U155 (.A1(w_reg_out[1]),
	.A2(H3[6]),
	.ZN(mult_34_n90));
   NAND2_X1 mult_34_U154 (.A1(w_reg_out[0]),
	.A2(H3[6]),
	.ZN(mult_34_n91));
   NOR2_X1 mult_34_U153 (.A1(mult_34_n180),
	.A2(FE_DBTN0_w_reg_out_6),
	.ZN(mult_34_n93));
   NOR2_X1 mult_34_U152 (.A1(mult_34_n180),
	.A2(FE_DBTN1_w_reg_out_5),
	.ZN(mult_34_n94));
   NOR2_X1 mult_34_U151 (.A1(mult_34_n180),
	.A2(FE_DBTN2_w_reg_out_4),
	.ZN(mult_34_n95));
   NOR2_X1 mult_34_U150 (.A1(mult_34_n180),
	.A2(FE_DBTN3_w_reg_out_3),
	.ZN(mult_34_n96));
   NOR2_X1 mult_34_U149 (.A1(mult_34_n180),
	.A2(FE_DBTN5_w_reg_out_1),
	.ZN(mult_34_n97));
   NOR2_X1 mult_34_U148 (.A1(mult_34_n180),
	.A2(FE_DBTN6_w_reg_out_0),
	.ZN(mult_34_n98));
   NAND2_X1 mult_34_U147 (.A1(H3[4]),
	.A2(w_reg_out[7]),
	.ZN(mult_34_n99));
   XNOR2_X1 mult_34_U146 (.A(mult_34_n2),
	.B(mult_34_n17),
	.ZN(mult_34_n201));
   XOR2_X1 mult_34_U145 (.A(mult_34_n201),
	.B(mult_34_n15),
	.Z(mult_34_n197));
   NAND2_X1 mult_34_U144 (.A1(H3[5]),
	.A2(w_reg_out[7]),
	.ZN(mult_34_n199));
   AND2_X1 mult_34_U143 (.A1(w_reg_out[6]),
	.A2(H3[6]),
	.ZN(mult_34_n200));
   XOR2_X1 mult_34_U142 (.A(mult_34_n199),
	.B(mult_34_n200),
	.Z(mult_34_n198));
   XOR2_X1 mult_34_U141 (.A(mult_34_n197),
	.B(mult_34_n198),
	.Z(ff_sh_6_));
   INV_X1 mult_34_U140 (.A(H3[0]),
	.ZN(mult_34_n189));
   INV_X1 mult_34_U136 (.A(H3[4]),
	.ZN(mult_34_n183));
   INV_X1 mult_34_U135 (.A(H3[5]),
	.ZN(mult_34_n180));
   INV_X1 mult_34_U130 (.A(H3[3]),
	.ZN(mult_34_n185));
   INV_X1 mult_34_U129 (.A(H3[2]),
	.ZN(mult_34_n186));
   INV_X1 mult_34_U128 (.A(H3[1]),
	.ZN(mult_34_n188));
   INV_X1 mult_34_U127 (.A(mult_34_n54),
	.ZN(mult_34_n181));
   INV_X1 mult_34_U126 (.A(mult_34_n80),
	.ZN(mult_34_n187));
   INV_X1 mult_34_U125 (.A(mult_34_n66),
	.ZN(mult_34_n179));
   INV_X1 mult_34_U124 (.A(mult_34_n73),
	.ZN(mult_34_n182));
   INV_X1 mult_34_U123 (.A(mult_34_n82),
	.ZN(mult_34_n184));
   HA_X1 mult_34_U51 (.A(mult_34_n129),
	.B(mult_34_n136),
	.CO(mult_34_n83),
	.S(mult_34_n84));
   HA_X1 mult_34_U50 (.A(mult_34_n114),
	.B(mult_34_n121),
	.CO(mult_34_n81),
	.S(mult_34_n82));
   FA_X1 mult_34_U49 (.A(mult_34_n128),
	.B(mult_34_n135),
	.CI(mult_34_n83),
	.CO(mult_34_n79),
	.S(mult_34_n80));
   HA_X1 mult_34_U48 (.A(mult_34_n106),
	.B(mult_34_n113),
	.CO(mult_34_n77),
	.S(mult_34_n78));
   FA_X1 mult_34_U47 (.A(mult_34_n120),
	.B(mult_34_n134),
	.CI(mult_34_n127),
	.CO(mult_34_n75),
	.S(mult_34_n76));
   FA_X1 mult_34_U46 (.A(mult_34_n78),
	.B(mult_34_n81),
	.CI(mult_34_n79),
	.CO(mult_34_n73),
	.S(mult_34_n74));
   HA_X1 mult_34_U45 (.A(mult_34_n98),
	.B(mult_34_n105),
	.CO(mult_34_n71),
	.S(mult_34_n72));
   FA_X1 mult_34_U44 (.A(mult_34_n112),
	.B(mult_34_n133),
	.CI(mult_34_n119),
	.CO(mult_34_n69),
	.S(mult_34_n70));
   FA_X1 mult_34_U43 (.A(mult_34_n77),
	.B(mult_34_n126),
	.CI(mult_34_n72),
	.CO(mult_34_n67),
	.S(mult_34_n68));
   FA_X1 mult_34_U42 (.A(mult_34_n70),
	.B(mult_34_n75),
	.CI(mult_34_n68),
	.CO(mult_34_n65),
	.S(mult_34_n66));
   FA_X1 mult_34_U39 (.A(mult_34_n97),
	.B(mult_34_n125),
	.CI(mult_34_n111),
	.CO(mult_34_n61),
	.S(mult_34_n62));
   FA_X1 mult_34_U38 (.A(mult_34_n91),
	.B(mult_34_n118),
	.CI(mult_34_n71),
	.CO(mult_34_n59),
	.S(mult_34_n60));
   FA_X1 mult_34_U37 (.A(mult_34_n69),
	.B(mult_34_n64),
	.CI(mult_34_n62),
	.CO(mult_34_n57),
	.S(mult_34_n58));
   FA_X1 mult_34_U36 (.A(mult_34_n60),
	.B(mult_34_n67),
	.CI(mult_34_n58),
	.CO(mult_34_n55),
	.S(mult_34_n56));
   FA_X1 mult_34_U34 (.A(mult_34_n103),
	.B(mult_34_n110),
	.CI(mult_34_n124),
	.CO(mult_34_n51),
	.S(mult_34_n52));
   FA_X1 mult_34_U33 (.A(mult_34_n131),
	.B(mult_34_n117),
	.CI(mult_34_n90),
	.CO(mult_34_n49),
	.S(mult_34_n50));
   FA_X1 mult_34_U32 (.A(mult_34_n63),
	.B(mult_34_n54),
	.CI(mult_34_n61),
	.CO(mult_34_n47),
	.S(mult_34_n48));
   FA_X1 mult_34_U31 (.A(mult_34_n52),
	.B(mult_34_n59),
	.CI(mult_34_n50),
	.CO(mult_34_n45),
	.S(mult_34_n46));
   FA_X1 mult_34_U30 (.A(mult_34_n48),
	.B(mult_34_n57),
	.CI(mult_34_n46),
	.CO(mult_34_n43),
	.S(mult_34_n44));
   FA_X1 mult_34_U29 (.A(mult_34_n102),
	.B(mult_34_n181),
	.CI(mult_34_n96),
	.CO(mult_34_n41),
	.S(mult_34_n42));
   FA_X1 mult_34_U28 (.A(mult_34_n116),
	.B(mult_34_n109),
	.CI(mult_34_n123),
	.CO(mult_34_n39),
	.S(mult_34_n40));
   FA_X1 mult_34_U27 (.A(mult_34_n51),
	.B(mult_34_n89),
	.CI(mult_34_n49),
	.CO(mult_34_n37),
	.S(mult_34_n38));
   FA_X1 mult_34_U26 (.A(mult_34_n40),
	.B(mult_34_n42),
	.CI(mult_34_n47),
	.CO(mult_34_n35),
	.S(mult_34_n36));
   FA_X1 mult_34_U25 (.A(mult_34_n38),
	.B(mult_34_n45),
	.CI(mult_34_n36),
	.CO(mult_34_n33),
	.S(mult_34_n34));
   FA_X1 mult_34_U24 (.A(mult_34_n95),
	.B(mult_34_n101),
	.CI(mult_34_n108),
	.CO(mult_34_n31),
	.S(mult_34_n32));
   FA_X1 mult_34_U23 (.A(mult_34_n88),
	.B(mult_34_n115),
	.CI(mult_34_n41),
	.CO(mult_34_n29),
	.S(mult_34_n30));
   FA_X1 mult_34_U22 (.A(mult_34_n32),
	.B(mult_34_n39),
	.CI(mult_34_n37),
	.CO(mult_34_n27),
	.S(mult_34_n28));
   FA_X1 mult_34_U21 (.A(mult_34_n35),
	.B(mult_34_n30),
	.CI(mult_34_n28),
	.CO(mult_34_n25),
	.S(mult_34_n26));
   FA_X1 mult_34_U20 (.A(mult_34_n94),
	.B(mult_34_n100),
	.CI(mult_34_n107),
	.CO(mult_34_n23),
	.S(mult_34_n24));
   FA_X1 mult_34_U19 (.A(mult_34_n31),
	.B(mult_34_n87),
	.CI(mult_34_n24),
	.CO(mult_34_n21),
	.S(mult_34_n22));
   FA_X1 mult_34_U18 (.A(mult_34_n27),
	.B(mult_34_n29),
	.CI(mult_34_n22),
	.CO(mult_34_n19),
	.S(mult_34_n20));
   FA_X1 mult_34_U17 (.A(mult_34_n99),
	.B(mult_34_n93),
	.CI(mult_34_n86),
	.CO(mult_34_n17),
	.S(mult_34_n18));
   FA_X1 mult_34_U16 (.A(mult_34_n18),
	.B(mult_34_n23),
	.CI(mult_34_n21),
	.CO(mult_34_n15),
	.S(mult_34_n16));
   FA_X1 mult_34_U8 (.A(mult_34_n56),
	.B(mult_34_n65),
	.CI(mult_34_n8),
	.CO(mult_34_n7),
	.S(ff_sh_0_));
   FA_X1 mult_34_U7 (.A(mult_34_n44),
	.B(mult_34_n55),
	.CI(mult_34_n7),
	.CO(mult_34_n6),
	.S(ff_sh_1_));
   FA_X1 mult_34_U6 (.A(mult_34_n34),
	.B(mult_34_n43),
	.CI(mult_34_n6),
	.CO(mult_34_n5),
	.S(ff_sh_2_));
   FA_X1 mult_34_U5 (.A(mult_34_n26),
	.B(mult_34_n33),
	.CI(mult_34_n5),
	.CO(mult_34_n4),
	.S(ff_sh_3_));
   FA_X1 mult_34_U4 (.A(mult_34_n20),
	.B(mult_34_n25),
	.CI(mult_34_n4),
	.CO(mult_34_n3),
	.S(ff_sh_4_));
   FA_X1 mult_34_U3 (.A(mult_34_n19),
	.B(mult_34_n16),
	.CI(mult_34_n3),
	.CO(mult_34_n2),
	.S(ff_sh_5_));
   NOR2_X1 mult_31_U203 (.A1(mult_31_n179),
	.A2(mult_31_n192),
	.ZN(mult_31_n100));
   NOR2_X1 mult_31_U202 (.A1(mult_31_n192),
	.A2(mult_31_n181),
	.ZN(mult_31_n101));
   NOR2_X1 mult_31_U201 (.A1(mult_31_n192),
	.A2(mult_31_n182),
	.ZN(mult_31_n102));
   NOR2_X1 mult_31_U200 (.A1(mult_31_n192),
	.A2(mult_31_n185),
	.ZN(mult_31_n103));
   NOR2_X1 mult_31_U199 (.A1(mult_31_n192),
	.A2(mult_31_n189),
	.ZN(mult_31_n105));
   NOR2_X1 mult_31_U198 (.A1(mult_31_n192),
	.A2(mult_31_n190),
	.ZN(mult_31_n106));
   NAND2_X1 mult_31_U197 (.A1(H2[3]),
	.A2(w[7]),
	.ZN(mult_31_n107));
   NOR2_X1 mult_31_U196 (.A1(mult_31_n179),
	.A2(mult_31_n193),
	.ZN(mult_31_n108));
   NOR2_X1 mult_31_U195 (.A1(mult_31_n181),
	.A2(mult_31_n193),
	.ZN(mult_31_n109));
   NOR2_X1 mult_31_U194 (.A1(mult_31_n182),
	.A2(mult_31_n193),
	.ZN(mult_31_n110));
   NOR2_X1 mult_31_U193 (.A1(mult_31_n185),
	.A2(mult_31_n193),
	.ZN(mult_31_n111));
   NOR2_X1 mult_31_U192 (.A1(mult_31_n187),
	.A2(mult_31_n193),
	.ZN(mult_31_n112));
   NOR2_X1 mult_31_U191 (.A1(mult_31_n189),
	.A2(mult_31_n193),
	.ZN(mult_31_n113));
   NOR2_X1 mult_31_U190 (.A1(mult_31_n190),
	.A2(mult_31_n193),
	.ZN(mult_31_n114));
   NAND2_X1 mult_31_U189 (.A1(H2[2]),
	.A2(w[7]),
	.ZN(mult_31_n115));
   NOR2_X1 mult_31_U188 (.A1(mult_31_n179),
	.A2(mult_31_n194),
	.ZN(mult_31_n116));
   NOR2_X1 mult_31_U187 (.A1(mult_31_n181),
	.A2(mult_31_n194),
	.ZN(mult_31_n117));
   NOR2_X1 mult_31_U186 (.A1(mult_31_n182),
	.A2(mult_31_n194),
	.ZN(mult_31_n118));
   NOR2_X1 mult_31_U185 (.A1(mult_31_n185),
	.A2(mult_31_n194),
	.ZN(mult_31_n119));
   NOR2_X1 mult_31_U184 (.A1(mult_31_n187),
	.A2(mult_31_n194),
	.ZN(mult_31_n120));
   NOR2_X1 mult_31_U183 (.A1(mult_31_n189),
	.A2(mult_31_n194),
	.ZN(mult_31_n121));
   NAND2_X1 mult_31_U182 (.A1(H2[1]),
	.A2(w[7]),
	.ZN(mult_31_n123));
   NOR2_X1 mult_31_U181 (.A1(mult_31_n179),
	.A2(mult_31_n195),
	.ZN(mult_31_n124));
   NOR2_X1 mult_31_U180 (.A1(mult_31_n181),
	.A2(mult_31_n195),
	.ZN(mult_31_n125));
   NOR2_X1 mult_31_U179 (.A1(mult_31_n182),
	.A2(mult_31_n195),
	.ZN(mult_31_n126));
   NOR2_X1 mult_31_U178 (.A1(mult_31_n185),
	.A2(mult_31_n195),
	.ZN(mult_31_n127));
   NOR2_X1 mult_31_U177 (.A1(mult_31_n187),
	.A2(mult_31_n195),
	.ZN(mult_31_n128));
   NOR2_X1 mult_31_U176 (.A1(mult_31_n189),
	.A2(mult_31_n195),
	.ZN(mult_31_n129));
   NAND2_X1 mult_31_U175 (.A1(H2[0]),
	.A2(w[7]),
	.ZN(mult_31_n131));
   NOR2_X1 mult_31_U174 (.A1(mult_31_n181),
	.A2(mult_31_n196),
	.ZN(mult_31_n133));
   NOR2_X1 mult_31_U173 (.A1(mult_31_n182),
	.A2(mult_31_n196),
	.ZN(mult_31_n134));
   NOR2_X1 mult_31_U172 (.A1(mult_31_n185),
	.A2(mult_31_n196),
	.ZN(mult_31_n135));
   NOR2_X1 mult_31_U171 (.A1(mult_31_n187),
	.A2(mult_31_n196),
	.ZN(mult_31_n136));
   NAND2_X1 mult_31_U170 (.A1(w[2]),
	.A2(H2[5]),
	.ZN(mult_31_n54));
   NAND2_X1 mult_31_U169 (.A1(H2[0]),
	.A2(w[6]),
	.ZN(mult_31_n208));
   NAND2_X1 mult_31_U168 (.A1(w[2]),
	.A2(H2[4]),
	.ZN(mult_31_n207));
   NAND2_X1 mult_31_U167 (.A1(mult_31_n208),
	.A2(mult_31_n207),
	.ZN(mult_31_n63));
   XNOR2_X1 mult_31_U166 (.A(mult_31_n207),
	.B(mult_31_n208),
	.ZN(mult_31_n64));
   NOR4_X1 mult_31_U165 (.A1(mult_31_n195),
	.A2(mult_31_n196),
	.A3(mult_31_n189),
	.A4(mult_31_n190),
	.ZN(mult_31_n205));
   NOR2_X1 mult_31_U164 (.A1(mult_31_n194),
	.A2(mult_31_n190),
	.ZN(mult_31_n206));
   AOI222_X1 mult_31_U163 (.A1(mult_31_n84),
	.A2(mult_31_n205),
	.B1(mult_31_n206),
	.B2(mult_31_n84),
	.C1(mult_31_n206),
	.C2(mult_31_n205),
	.ZN(mult_31_n204));
   OAI222_X1 mult_31_U162 (.A1(mult_31_n204),
	.A2(mult_31_n184),
	.B1(mult_31_n184),
	.B2(mult_31_n188),
	.C1(mult_31_n204),
	.C2(mult_31_n188),
	.ZN(mult_31_n203));
   AOI222_X1 mult_31_U161 (.A1(mult_31_n203),
	.A2(mult_31_n74),
	.B1(mult_31_n203),
	.B2(mult_31_n76),
	.C1(mult_31_n76),
	.C2(mult_31_n74),
	.ZN(mult_31_n202));
   OAI222_X1 mult_31_U160 (.A1(mult_31_n202),
	.A2(mult_31_n180),
	.B1(mult_31_n202),
	.B2(mult_31_n183),
	.C1(mult_31_n183),
	.C2(mult_31_n180),
	.ZN(mult_31_n8));
   NAND2_X1 mult_31_U159 (.A1(w[5]),
	.A2(H2[6]),
	.ZN(mult_31_n86));
   NAND2_X1 mult_31_U158 (.A1(w[4]),
	.A2(H2[6]),
	.ZN(mult_31_n87));
   NAND2_X1 mult_31_U157 (.A1(w[3]),
	.A2(H2[6]),
	.ZN(mult_31_n88));
   NAND2_X1 mult_31_U156 (.A1(w[2]),
	.A2(H2[6]),
	.ZN(mult_31_n89));
   NAND2_X1 mult_31_U155 (.A1(w[1]),
	.A2(H2[6]),
	.ZN(mult_31_n90));
   NAND2_X1 mult_31_U154 (.A1(w[0]),
	.A2(H2[6]),
	.ZN(mult_31_n91));
   NOR2_X1 mult_31_U153 (.A1(mult_31_n191),
	.A2(mult_31_n179),
	.ZN(mult_31_n93));
   NOR2_X1 mult_31_U152 (.A1(mult_31_n191),
	.A2(mult_31_n181),
	.ZN(mult_31_n94));
   NOR2_X1 mult_31_U151 (.A1(mult_31_n191),
	.A2(mult_31_n182),
	.ZN(mult_31_n95));
   NOR2_X1 mult_31_U150 (.A1(mult_31_n191),
	.A2(mult_31_n185),
	.ZN(mult_31_n96));
   NOR2_X1 mult_31_U149 (.A1(mult_31_n191),
	.A2(mult_31_n189),
	.ZN(mult_31_n97));
   NOR2_X1 mult_31_U148 (.A1(mult_31_n191),
	.A2(mult_31_n190),
	.ZN(mult_31_n98));
   NAND2_X1 mult_31_U147 (.A1(H2[4]),
	.A2(w[7]),
	.ZN(mult_31_n99));
   XNOR2_X1 mult_31_U146 (.A(mult_31_n2),
	.B(mult_31_n17),
	.ZN(mult_31_n201));
   XOR2_X1 mult_31_U145 (.A(mult_31_n201),
	.B(mult_31_n15),
	.Z(mult_31_n197));
   NAND2_X1 mult_31_U144 (.A1(H2[5]),
	.A2(w[7]),
	.ZN(mult_31_n199));
   AND2_X1 mult_31_U143 (.A1(w[6]),
	.A2(H2[6]),
	.ZN(mult_31_n200));
   XOR2_X1 mult_31_U142 (.A(mult_31_n199),
	.B(mult_31_n200),
	.Z(mult_31_n198));
   XOR2_X1 mult_31_U141 (.A(mult_31_n197),
	.B(mult_31_n198),
	.Z(b0_w_12_));
   INV_X1 mult_31_U140 (.A(H2[0]),
	.ZN(mult_31_n196));
   INV_X1 mult_31_U139 (.A(H2[4]),
	.ZN(mult_31_n192));
   INV_X1 mult_31_U138 (.A(H2[5]),
	.ZN(mult_31_n191));
   INV_X1 mult_31_U137 (.A(H2[3]),
	.ZN(mult_31_n193));
   INV_X1 mult_31_U136 (.A(H2[2]),
	.ZN(mult_31_n194));
   INV_X1 mult_31_U135 (.A(H2[1]),
	.ZN(mult_31_n195));
   INV_X1 mult_31_U134 (.A(w[0]),
	.ZN(mult_31_n190));
   INV_X1 mult_31_U133 (.A(mult_31_n54),
	.ZN(mult_31_n186));
   INV_X1 mult_31_U132 (.A(w[1]),
	.ZN(mult_31_n189));
   INV_X1 mult_31_U131 (.A(w[2]),
	.ZN(mult_31_n187));
   INV_X1 mult_31_U130 (.A(w[6]),
	.ZN(mult_31_n179));
   INV_X1 mult_31_U129 (.A(w[3]),
	.ZN(mult_31_n185));
   INV_X1 mult_31_U128 (.A(w[4]),
	.ZN(mult_31_n182));
   INV_X1 mult_31_U127 (.A(w[5]),
	.ZN(mult_31_n181));
   INV_X1 mult_31_U126 (.A(mult_31_n80),
	.ZN(mult_31_n184));
   INV_X1 mult_31_U125 (.A(mult_31_n82),
	.ZN(mult_31_n188));
   INV_X1 mult_31_U124 (.A(mult_31_n73),
	.ZN(mult_31_n183));
   INV_X1 mult_31_U123 (.A(mult_31_n66),
	.ZN(mult_31_n180));
   HA_X1 mult_31_U51 (.A(mult_31_n129),
	.B(mult_31_n136),
	.CO(mult_31_n83),
	.S(mult_31_n84));
   HA_X1 mult_31_U50 (.A(mult_31_n114),
	.B(mult_31_n121),
	.CO(mult_31_n81),
	.S(mult_31_n82));
   FA_X1 mult_31_U49 (.A(mult_31_n128),
	.B(mult_31_n135),
	.CI(mult_31_n83),
	.CO(mult_31_n79),
	.S(mult_31_n80));
   HA_X1 mult_31_U48 (.A(mult_31_n106),
	.B(mult_31_n113),
	.CO(mult_31_n77),
	.S(mult_31_n78));
   FA_X1 mult_31_U47 (.A(mult_31_n120),
	.B(mult_31_n134),
	.CI(mult_31_n127),
	.CO(mult_31_n75),
	.S(mult_31_n76));
   FA_X1 mult_31_U46 (.A(mult_31_n78),
	.B(mult_31_n81),
	.CI(mult_31_n79),
	.CO(mult_31_n73),
	.S(mult_31_n74));
   HA_X1 mult_31_U45 (.A(mult_31_n98),
	.B(mult_31_n105),
	.CO(mult_31_n71),
	.S(mult_31_n72));
   FA_X1 mult_31_U44 (.A(mult_31_n112),
	.B(mult_31_n133),
	.CI(mult_31_n119),
	.CO(mult_31_n69),
	.S(mult_31_n70));
   FA_X1 mult_31_U43 (.A(mult_31_n77),
	.B(mult_31_n126),
	.CI(mult_31_n72),
	.CO(mult_31_n67),
	.S(mult_31_n68));
   FA_X1 mult_31_U42 (.A(mult_31_n70),
	.B(mult_31_n75),
	.CI(mult_31_n68),
	.CO(mult_31_n65),
	.S(mult_31_n66));
   FA_X1 mult_31_U39 (.A(mult_31_n97),
	.B(mult_31_n125),
	.CI(mult_31_n111),
	.CO(mult_31_n61),
	.S(mult_31_n62));
   FA_X1 mult_31_U38 (.A(mult_31_n91),
	.B(mult_31_n118),
	.CI(mult_31_n71),
	.CO(mult_31_n59),
	.S(mult_31_n60));
   FA_X1 mult_31_U37 (.A(mult_31_n69),
	.B(mult_31_n64),
	.CI(mult_31_n62),
	.CO(mult_31_n57),
	.S(mult_31_n58));
   FA_X1 mult_31_U36 (.A(mult_31_n60),
	.B(mult_31_n67),
	.CI(mult_31_n58),
	.CO(mult_31_n55),
	.S(mult_31_n56));
   FA_X1 mult_31_U34 (.A(mult_31_n103),
	.B(mult_31_n110),
	.CI(mult_31_n124),
	.CO(mult_31_n51),
	.S(mult_31_n52));
   FA_X1 mult_31_U33 (.A(mult_31_n131),
	.B(mult_31_n117),
	.CI(mult_31_n90),
	.CO(mult_31_n49),
	.S(mult_31_n50));
   FA_X1 mult_31_U32 (.A(mult_31_n63),
	.B(mult_31_n54),
	.CI(mult_31_n61),
	.CO(mult_31_n47),
	.S(mult_31_n48));
   FA_X1 mult_31_U31 (.A(mult_31_n52),
	.B(mult_31_n59),
	.CI(mult_31_n50),
	.CO(mult_31_n45),
	.S(mult_31_n46));
   FA_X1 mult_31_U30 (.A(mult_31_n48),
	.B(mult_31_n57),
	.CI(mult_31_n46),
	.CO(mult_31_n43),
	.S(mult_31_n44));
   FA_X1 mult_31_U29 (.A(mult_31_n102),
	.B(mult_31_n186),
	.CI(mult_31_n96),
	.CO(mult_31_n41),
	.S(mult_31_n42));
   FA_X1 mult_31_U28 (.A(mult_31_n116),
	.B(mult_31_n109),
	.CI(mult_31_n123),
	.CO(mult_31_n39),
	.S(mult_31_n40));
   FA_X1 mult_31_U27 (.A(mult_31_n51),
	.B(mult_31_n89),
	.CI(mult_31_n49),
	.CO(mult_31_n37),
	.S(mult_31_n38));
   FA_X1 mult_31_U26 (.A(mult_31_n40),
	.B(mult_31_n42),
	.CI(mult_31_n47),
	.CO(mult_31_n35),
	.S(mult_31_n36));
   FA_X1 mult_31_U25 (.A(mult_31_n38),
	.B(mult_31_n45),
	.CI(mult_31_n36),
	.CO(mult_31_n33),
	.S(mult_31_n34));
   FA_X1 mult_31_U24 (.A(mult_31_n95),
	.B(mult_31_n101),
	.CI(mult_31_n108),
	.CO(mult_31_n31),
	.S(mult_31_n32));
   FA_X1 mult_31_U23 (.A(mult_31_n88),
	.B(mult_31_n115),
	.CI(mult_31_n41),
	.CO(mult_31_n29),
	.S(mult_31_n30));
   FA_X1 mult_31_U22 (.A(mult_31_n32),
	.B(mult_31_n39),
	.CI(mult_31_n37),
	.CO(mult_31_n27),
	.S(mult_31_n28));
   FA_X1 mult_31_U21 (.A(mult_31_n35),
	.B(mult_31_n30),
	.CI(mult_31_n28),
	.CO(mult_31_n25),
	.S(mult_31_n26));
   FA_X1 mult_31_U20 (.A(mult_31_n94),
	.B(mult_31_n100),
	.CI(mult_31_n107),
	.CO(mult_31_n23),
	.S(mult_31_n24));
   FA_X1 mult_31_U19 (.A(mult_31_n31),
	.B(mult_31_n87),
	.CI(mult_31_n24),
	.CO(mult_31_n21),
	.S(mult_31_n22));
   FA_X1 mult_31_U18 (.A(mult_31_n27),
	.B(mult_31_n29),
	.CI(mult_31_n22),
	.CO(mult_31_n19),
	.S(mult_31_n20));
   FA_X1 mult_31_U17 (.A(mult_31_n99),
	.B(mult_31_n93),
	.CI(mult_31_n86),
	.CO(mult_31_n17),
	.S(mult_31_n18));
   FA_X1 mult_31_U16 (.A(mult_31_n18),
	.B(mult_31_n23),
	.CI(mult_31_n21),
	.CO(mult_31_n15),
	.S(mult_31_n16));
   FA_X1 mult_31_U8 (.A(mult_31_n56),
	.B(mult_31_n65),
	.CI(mult_31_n8),
	.CO(mult_31_n7),
	.S(b0_w_6_));
   FA_X1 mult_31_U7 (.A(mult_31_n44),
	.B(mult_31_n55),
	.CI(mult_31_n7),
	.CO(mult_31_n6),
	.S(b0_w_7_));
   FA_X1 mult_31_U6 (.A(mult_31_n34),
	.B(mult_31_n43),
	.CI(mult_31_n6),
	.CO(mult_31_n5),
	.S(b0_w_8_));
   FA_X1 mult_31_U5 (.A(mult_31_n26),
	.B(mult_31_n33),
	.CI(mult_31_n5),
	.CO(mult_31_n4),
	.S(b0_w_9_));
   FA_X1 mult_31_U4 (.A(mult_31_n20),
	.B(mult_31_n25),
	.CI(mult_31_n4),
	.CO(mult_31_n3),
	.S(b0_w_10_));
   FA_X1 mult_31_U3 (.A(mult_31_n19),
	.B(mult_31_n16),
	.CI(mult_31_n3),
	.CO(mult_31_n2),
	.S(b0_w_11_));
   AND2_X1 add_32_U2 (.A1(ff_sh_0_),
	.A2(b0_w_6_),
	.ZN(add_32_n2));
   XOR2_X1 add_32_U1 (.A(ff_sh_0_),
	.B(b0_w_6_),
	.Z(DOUT_reg_in[0]));
   FA_X1 add_32_U1_1 (.A(b0_w_7_),
	.B(ff_sh_1_),
	.CI(add_32_n2),
	.CO(add_32_carry[2]),
	.S(DOUT_reg_in[1]));
   FA_X1 add_32_U1_2 (.A(b0_w_8_),
	.B(ff_sh_2_),
	.CI(add_32_carry[2]),
	.CO(add_32_carry[3]),
	.S(DOUT_reg_in[2]));
   FA_X1 add_32_U1_3 (.A(b0_w_9_),
	.B(ff_sh_3_),
	.CI(add_32_carry[3]),
	.CO(add_32_carry[4]),
	.S(DOUT_reg_in[3]));
   FA_X1 add_32_U1_4 (.A(b0_w_10_),
	.B(ff_sh_4_),
	.CI(add_32_carry[4]),
	.CO(add_32_carry[5]),
	.S(DOUT_reg_in[4]));
   FA_X1 add_32_U1_5 (.A(b0_w_11_),
	.B(ff_sh_5_),
	.CI(add_32_carry[5]),
	.CO(add_32_carry[6]),
	.S(DOUT_reg_in[5]));
   FA_X1 add_32_U1_6 (.A(b0_w_12_),
	.B(ff_sh_6_),
	.CI(add_32_carry[6]),
	.S(DOUT_reg_in[6]));
endmodule

