/*
###############################################################
#  Generated by:      Cadence Innovus 17.11-s080_1
#  OS:                Linux x86_64(Host ID localhost.localdomain)
#  Generated on:      Sun Nov 21 16:49:05 2021
#  Design:            IIRfilter_LA
#  Command:           saveNetlist IIRfilter_LA.v
###############################################################
*/
/////////////////////////////////////////////////////////////
// Created by: Synopsys DC Expert(TM) in wire load mode
// Version   : O-2018.06-SP4
// Date      : Sun Nov 21 14:19:22 2021
/////////////////////////////////////////////////////////////
module IIRfilter_LA (
	DIN, 
	H0, 
	H1, 
	H2, 
	H3, 
	H4, 
	VIN, 
	RST_n, 
	CLK, 
	DOUT, 
	VOUT);
   input [6:0] DIN;
   input [6:0] H0;
   input [6:0] H1;
   input [6:0] H2;
   input [6:0] H3;
   input [13:0] H4;
   input VIN;
   input RST_n;
   input CLK;
   output [6:0] DOUT;
   output VOUT;

   // Internal wires
   wire FE_DBTN3_w_0;
   wire FE_DBTN2_w_1;
   wire FE_DBTN1_w_3;
   wire FE_DBTN0_w_5;
   wire n1;
   wire n2;
   wire n3;
   wire n4;
   wire n5;
   wire n6;
   wire n7;
   wire n11;
   wire n14;
   wire n17;
   wire n20;
   wire n23;
   wire n26;
   wire n29;
   wire n32;
   wire n33;
   wire n34;
   wire n35;
   wire n36;
   wire n37;
   wire n38;
   wire n39;
   wire n40;
   wire n41;
   wire n42;
   wire n43;
   wire n44;
   wire n45;
   wire n46;
   wire n47;
   wire n56;
   wire n57;
   wire n58;
   wire n59;
   wire n60;
   wire n61;
   wire n62;
   wire n63;
   wire n64;
   wire n65;
   wire n66;
   wire n67;
   wire n68;
   wire n69;
   wire n70;
   wire n71;
   wire n72;
   wire n73;
   wire n74;
   wire n75;
   wire n76;
   wire n77;
   wire n78;
   wire n79;
   wire n80;
   wire n81;
   wire n82;
   wire n83;
   wire n84;
   wire n85;
   wire n86;
   wire n87;
   wire n88;
   wire n89;
   wire n90;
   wire n91;
   wire n92;
   wire n93;
   wire w_add_6_;
   wire w_add_5_;
   wire w_add_4_;
   wire w_add_3_;
   wire w_add_2_;
   wire w_add_1_;
   wire w_add_0_;
   wire w_a1b0_20_;
   wire w_a1b0_19_;
   wire w_a1b0_18_;
   wire w_a1b0_17_;
   wire w_a1b0_16_;
   wire w_a1b0_15_;
   wire w_a1b0_14_;
   wire ff_sh_6_;
   wire ff_sh_5_;
   wire ff_sh_4_;
   wire ff_sh_3_;
   wire ff_sh_2_;
   wire ff_sh_1_;
   wire ff_sh_0_;
   wire din_b0_9_;
   wire din_b0_8_;
   wire din_b0_7_;
   wire din_b0_6_;
   wire din_b0_12_;
   wire din_b0_11_;
   wire din_b0_10_;
   wire n98;
   wire n99;
   wire n100;
   wire n101;
   wire n102;
   wire n103;
   wire n104;
   wire n105;
   wire n106;
   wire n107;
   wire n108;
   wire n109;
   wire n110;
   wire n111;
   wire n112;
   wire n113;
   wire n114;
   wire sub_32_n8;
   wire sub_32_n7;
   wire sub_32_n6;
   wire sub_32_n5;
   wire sub_32_n4;
   wire sub_32_n3;
   wire sub_32_n2;
   wire sub_32_n1;
   wire mult_39_n184;
   wire mult_39_n183;
   wire mult_39_n182;
   wire mult_39_n181;
   wire mult_39_n180;
   wire mult_39_n179;
   wire mult_39_n178;
   wire mult_39_n177;
   wire mult_39_n176;
   wire mult_39_n175;
   wire mult_39_n174;
   wire mult_39_n173;
   wire mult_39_n172;
   wire mult_39_n171;
   wire mult_39_n170;
   wire mult_39_n169;
   wire mult_39_n168;
   wire mult_39_n167;
   wire mult_39_n166;
   wire mult_39_n165;
   wire mult_39_n164;
   wire mult_39_n163;
   wire mult_39_n162;
   wire mult_39_n161;
   wire mult_39_n160;
   wire mult_39_n119;
   wire mult_39_n118;
   wire mult_39_n117;
   wire mult_39_n116;
   wire mult_39_n115;
   wire mult_39_n113;
   wire mult_39_n112;
   wire mult_39_n111;
   wire mult_39_n110;
   wire mult_39_n109;
   wire mult_39_n108;
   wire mult_39_n106;
   wire mult_39_n105;
   wire mult_39_n104;
   wire mult_39_n103;
   wire mult_39_n102;
   wire mult_39_n101;
   wire mult_39_n100;
   wire mult_39_n99;
   wire mult_39_n98;
   wire mult_39_n97;
   wire mult_39_n95;
   wire mult_39_n94;
   wire mult_39_n93;
   wire mult_39_n92;
   wire mult_39_n91;
   wire mult_39_n90;
   wire mult_39_n89;
   wire mult_39_n88;
   wire mult_39_n87;
   wire mult_39_n86;
   wire mult_39_n85;
   wire mult_39_n83;
   wire mult_39_n82;
   wire mult_39_n81;
   wire mult_39_n80;
   wire mult_39_n79;
   wire mult_39_n78;
   wire mult_39_n77;
   wire mult_39_n76;
   wire mult_39_n75;
   wire mult_39_n74;
   wire mult_39_n72;
   wire mult_39_n71;
   wire mult_39_n70;
   wire mult_39_n69;
   wire mult_39_n68;
   wire mult_39_n67;
   wire mult_39_n66;
   wire mult_39_n65;
   wire mult_39_n64;
   wire mult_39_n63;
   wire mult_39_n62;
   wire mult_39_n61;
   wire mult_39_n60;
   wire mult_39_n59;
   wire mult_39_n58;
   wire mult_39_n57;
   wire mult_39_n56;
   wire mult_39_n55;
   wire mult_39_n54;
   wire mult_39_n53;
   wire mult_39_n52;
   wire mult_39_n51;
   wire mult_39_n50;
   wire mult_39_n49;
   wire mult_39_n48;
   wire mult_39_n47;
   wire mult_39_n46;
   wire mult_39_n45;
   wire mult_39_n44;
   wire mult_39_n43;
   wire mult_39_n42;
   wire mult_39_n41;
   wire mult_39_n40;
   wire mult_39_n39;
   wire mult_39_n38;
   wire mult_39_n37;
   wire mult_39_n36;
   wire mult_39_n35;
   wire mult_39_n34;
   wire mult_39_n33;
   wire mult_39_n32;
   wire mult_39_n31;
   wire mult_39_n30;
   wire mult_39_n29;
   wire mult_39_n28;
   wire mult_39_n27;
   wire mult_39_n26;
   wire mult_39_n25;
   wire mult_39_n24;
   wire mult_39_n23;
   wire mult_39_n22;
   wire mult_39_n21;
   wire mult_39_n20;
   wire mult_39_n19;
   wire mult_39_n18;
   wire mult_39_n17;
   wire mult_39_n16;
   wire mult_39_n15;
   wire mult_39_n14;
   wire mult_39_n13;
   wire mult_39_n8;
   wire mult_39_n7;
   wire mult_39_n6;
   wire mult_39_n5;
   wire mult_39_n4;
   wire mult_39_n3;
   wire mult_39_n2;
   wire mult_42_n208;
   wire mult_42_n207;
   wire mult_42_n206;
   wire mult_42_n205;
   wire mult_42_n204;
   wire mult_42_n203;
   wire mult_42_n202;
   wire mult_42_n201;
   wire mult_42_n200;
   wire mult_42_n199;
   wire mult_42_n198;
   wire mult_42_n197;
   wire mult_42_n196;
   wire mult_42_n195;
   wire mult_42_n194;
   wire mult_42_n193;
   wire mult_42_n192;
   wire mult_42_n191;
   wire mult_42_n188;
   wire mult_42_n187;
   wire mult_42_n186;
   wire mult_42_n184;
   wire mult_42_n183;
   wire mult_42_n182;
   wire mult_42_n180;
   wire mult_42_n179;
   wire mult_42_n136;
   wire mult_42_n135;
   wire mult_42_n134;
   wire mult_42_n133;
   wire mult_42_n131;
   wire mult_42_n129;
   wire mult_42_n128;
   wire mult_42_n127;
   wire mult_42_n126;
   wire mult_42_n125;
   wire mult_42_n124;
   wire mult_42_n123;
   wire mult_42_n121;
   wire mult_42_n120;
   wire mult_42_n119;
   wire mult_42_n118;
   wire mult_42_n117;
   wire mult_42_n116;
   wire mult_42_n115;
   wire mult_42_n114;
   wire mult_42_n113;
   wire mult_42_n112;
   wire mult_42_n111;
   wire mult_42_n110;
   wire mult_42_n109;
   wire mult_42_n108;
   wire mult_42_n107;
   wire mult_42_n106;
   wire mult_42_n105;
   wire mult_42_n103;
   wire mult_42_n102;
   wire mult_42_n101;
   wire mult_42_n100;
   wire mult_42_n99;
   wire mult_42_n98;
   wire mult_42_n97;
   wire mult_42_n96;
   wire mult_42_n95;
   wire mult_42_n94;
   wire mult_42_n93;
   wire mult_42_n91;
   wire mult_42_n90;
   wire mult_42_n89;
   wire mult_42_n88;
   wire mult_42_n87;
   wire mult_42_n86;
   wire mult_42_n84;
   wire mult_42_n83;
   wire mult_42_n82;
   wire mult_42_n81;
   wire mult_42_n80;
   wire mult_42_n79;
   wire mult_42_n78;
   wire mult_42_n77;
   wire mult_42_n76;
   wire mult_42_n75;
   wire mult_42_n74;
   wire mult_42_n73;
   wire mult_42_n72;
   wire mult_42_n71;
   wire mult_42_n70;
   wire mult_42_n69;
   wire mult_42_n68;
   wire mult_42_n67;
   wire mult_42_n66;
   wire mult_42_n65;
   wire mult_42_n64;
   wire mult_42_n63;
   wire mult_42_n62;
   wire mult_42_n61;
   wire mult_42_n60;
   wire mult_42_n59;
   wire mult_42_n58;
   wire mult_42_n57;
   wire mult_42_n56;
   wire mult_42_n55;
   wire mult_42_n54;
   wire mult_42_n52;
   wire mult_42_n51;
   wire mult_42_n50;
   wire mult_42_n49;
   wire mult_42_n48;
   wire mult_42_n47;
   wire mult_42_n46;
   wire mult_42_n45;
   wire mult_42_n44;
   wire mult_42_n43;
   wire mult_42_n42;
   wire mult_42_n41;
   wire mult_42_n40;
   wire mult_42_n39;
   wire mult_42_n38;
   wire mult_42_n37;
   wire mult_42_n36;
   wire mult_42_n35;
   wire mult_42_n34;
   wire mult_42_n33;
   wire mult_42_n32;
   wire mult_42_n31;
   wire mult_42_n30;
   wire mult_42_n29;
   wire mult_42_n28;
   wire mult_42_n27;
   wire mult_42_n26;
   wire mult_42_n25;
   wire mult_42_n24;
   wire mult_42_n23;
   wire mult_42_n22;
   wire mult_42_n21;
   wire mult_42_n20;
   wire mult_42_n19;
   wire mult_42_n18;
   wire mult_42_n17;
   wire mult_42_n16;
   wire mult_42_n15;
   wire mult_42_n8;
   wire mult_42_n7;
   wire mult_42_n6;
   wire mult_42_n5;
   wire mult_42_n4;
   wire mult_42_n3;
   wire mult_42_n2;
   wire mult_40_n409;
   wire mult_40_n408;
   wire mult_40_n407;
   wire mult_40_n406;
   wire mult_40_n405;
   wire mult_40_n404;
   wire mult_40_n403;
   wire mult_40_n402;
   wire mult_40_n401;
   wire mult_40_n400;
   wire mult_40_n399;
   wire mult_40_n398;
   wire mult_40_n397;
   wire mult_40_n396;
   wire mult_40_n395;
   wire mult_40_n394;
   wire mult_40_n393;
   wire mult_40_n392;
   wire mult_40_n391;
   wire mult_40_n390;
   wire mult_40_n389;
   wire mult_40_n388;
   wire mult_40_n387;
   wire mult_40_n386;
   wire mult_40_n385;
   wire mult_40_n384;
   wire mult_40_n383;
   wire mult_40_n382;
   wire mult_40_n381;
   wire mult_40_n380;
   wire mult_40_n379;
   wire mult_40_n378;
   wire mult_40_n377;
   wire mult_40_n376;
   wire mult_40_n375;
   wire mult_40_n374;
   wire mult_40_n373;
   wire mult_40_n372;
   wire mult_40_n371;
   wire mult_40_n370;
   wire mult_40_n369;
   wire mult_40_n368;
   wire mult_40_n367;
   wire mult_40_n366;
   wire mult_40_n365;
   wire mult_40_n364;
   wire mult_40_n363;
   wire mult_40_n362;
   wire mult_40_n361;
   wire mult_40_n360;
   wire mult_40_n359;
   wire mult_40_n358;
   wire mult_40_n357;
   wire mult_40_n356;
   wire mult_40_n355;
   wire mult_40_n354;
   wire mult_40_n353;
   wire mult_40_n352;
   wire mult_40_n351;
   wire mult_40_n350;
   wire mult_40_n349;
   wire mult_40_n348;
   wire mult_40_n347;
   wire mult_40_n346;
   wire mult_40_n345;
   wire mult_40_n344;
   wire mult_40_n343;
   wire mult_40_n342;
   wire mult_40_n341;
   wire mult_40_n340;
   wire mult_40_n339;
   wire mult_40_n338;
   wire mult_40_n337;
   wire mult_40_n336;
   wire mult_40_n335;
   wire mult_40_n334;
   wire mult_40_n333;
   wire mult_40_n332;
   wire mult_40_n331;
   wire mult_40_n330;
   wire mult_40_n329;
   wire mult_40_n328;
   wire mult_40_n327;
   wire mult_40_n326;
   wire mult_40_n325;
   wire mult_40_n324;
   wire mult_40_n323;
   wire mult_40_n322;
   wire mult_40_n321;
   wire mult_40_n320;
   wire mult_40_n317;
   wire mult_40_n316;
   wire mult_40_n315;
   wire mult_40_n314;
   wire mult_40_n312;
   wire mult_40_n311;
   wire mult_40_n310;
   wire mult_40_n309;
   wire mult_40_n307;
   wire mult_40_n306;
   wire mult_40_n305;
   wire mult_40_n304;
   wire mult_40_n303;
   wire mult_40_n302;
   wire mult_40_n301;
   wire mult_40_n300;
   wire mult_40_n299;
   wire mult_40_n298;
   wire mult_40_n297;
   wire mult_40_n296;
   wire mult_40_n295;
   wire mult_40_n294;
   wire mult_40_n293;
   wire mult_40_n292;
   wire mult_40_n167;
   wire mult_40_n166;
   wire mult_40_n165;
   wire mult_40_n164;
   wire mult_40_n163;
   wire mult_40_n162;
   wire mult_40_n161;
   wire mult_40_n160;
   wire mult_40_n159;
   wire mult_40_n158;
   wire mult_40_n157;
   wire mult_40_n154;
   wire mult_40_n153;
   wire mult_40_n152;
   wire mult_40_n151;
   wire mult_40_n150;
   wire mult_40_n149;
   wire mult_40_n148;
   wire mult_40_n147;
   wire mult_40_n146;
   wire mult_40_n145;
   wire mult_40_n144;
   wire mult_40_n142;
   wire mult_40_n141;
   wire mult_40_n140;
   wire mult_40_n139;
   wire mult_40_n138;
   wire mult_40_n137;
   wire mult_40_n136;
   wire mult_40_n135;
   wire mult_40_n134;
   wire mult_40_n133;
   wire mult_40_n132;
   wire mult_40_n131;
   wire mult_40_n130;
   wire mult_40_n129;
   wire mult_40_n127;
   wire mult_40_n126;
   wire mult_40_n125;
   wire mult_40_n124;
   wire mult_40_n123;
   wire mult_40_n122;
   wire mult_40_n121;
   wire mult_40_n120;
   wire mult_40_n118;
   wire mult_40_n117;
   wire mult_40_n116;
   wire mult_40_n115;
   wire mult_40_n111;
   wire mult_40_n110;
   wire mult_40_n98;
   wire mult_40_n97;
   wire mult_40_n96;
   wire mult_40_n95;
   wire mult_40_n94;
   wire mult_40_n93;
   wire mult_40_n92;
   wire mult_40_n91;
   wire mult_40_n90;
   wire mult_40_n89;
   wire mult_40_n88;
   wire mult_40_n87;
   wire mult_40_n86;
   wire mult_40_n85;
   wire mult_40_n84;
   wire mult_40_n83;
   wire mult_40_n82;
   wire mult_40_n81;
   wire mult_40_n80;
   wire mult_40_n79;
   wire mult_40_n78;
   wire mult_40_n77;
   wire mult_40_n76;
   wire mult_40_n75;
   wire mult_40_n74;
   wire mult_40_n73;
   wire mult_40_n72;
   wire mult_40_n71;
   wire mult_40_n70;
   wire mult_40_n69;
   wire mult_40_n68;
   wire mult_40_n67;
   wire mult_40_n66;
   wire mult_40_n65;
   wire mult_40_n64;
   wire mult_40_n63;
   wire mult_40_n62;
   wire mult_40_n61;
   wire mult_40_n60;
   wire mult_40_n59;
   wire mult_40_n58;
   wire mult_40_n57;
   wire mult_40_n56;
   wire mult_40_n55;
   wire mult_40_n54;
   wire mult_40_n53;
   wire mult_40_n52;
   wire mult_40_n51;
   wire mult_40_n50;
   wire mult_40_n49;
   wire mult_40_n48;
   wire mult_40_n47;
   wire mult_40_n46;
   wire mult_40_n45;
   wire mult_40_n44;
   wire mult_40_n43;
   wire mult_40_n42;
   wire mult_40_n41;
   wire mult_40_n40;
   wire mult_40_n39;
   wire mult_40_n38;
   wire mult_40_n36;
   wire mult_40_n35;
   wire mult_40_n34;
   wire mult_40_n33;
   wire mult_40_n32;
   wire mult_40_n31;
   wire mult_40_n30;
   wire mult_40_n29;
   wire mult_40_n27;
   wire mult_40_n26;
   wire mult_40_n25;
   wire mult_40_n24;
   wire mult_40_n23;
   wire mult_40_n22;
   wire mult_40_n8;
   wire mult_40_n7;
   wire mult_40_n6;
   wire mult_40_n5;
   wire mult_40_n4;
   wire mult_40_n3;
   wire mult_40_n2;
   wire add_1_root_sub_0_root_add_37_n1;
   wire sub_0_root_sub_0_root_add_37_n8;
   wire sub_0_root_sub_0_root_add_37_n7;
   wire sub_0_root_sub_0_root_add_37_n6;
   wire sub_0_root_sub_0_root_add_37_n5;
   wire sub_0_root_sub_0_root_add_37_n4;
   wire sub_0_root_sub_0_root_add_37_n3;
   wire sub_0_root_sub_0_root_add_37_n2;
   wire sub_0_root_sub_0_root_add_37_n1;
   wire mult_41_n208;
   wire mult_41_n207;
   wire mult_41_n206;
   wire mult_41_n205;
   wire mult_41_n204;
   wire mult_41_n203;
   wire mult_41_n202;
   wire mult_41_n201;
   wire mult_41_n200;
   wire mult_41_n199;
   wire mult_41_n198;
   wire mult_41_n197;
   wire mult_41_n196;
   wire mult_41_n195;
   wire mult_41_n194;
   wire mult_41_n193;
   wire mult_41_n192;
   wire mult_41_n191;
   wire mult_41_n190;
   wire mult_41_n189;
   wire mult_41_n188;
   wire mult_41_n187;
   wire mult_41_n186;
   wire mult_41_n185;
   wire mult_41_n184;
   wire mult_41_n183;
   wire mult_41_n182;
   wire mult_41_n181;
   wire mult_41_n180;
   wire mult_41_n179;
   wire mult_41_n136;
   wire mult_41_n135;
   wire mult_41_n134;
   wire mult_41_n133;
   wire mult_41_n131;
   wire mult_41_n129;
   wire mult_41_n128;
   wire mult_41_n127;
   wire mult_41_n126;
   wire mult_41_n125;
   wire mult_41_n124;
   wire mult_41_n123;
   wire mult_41_n121;
   wire mult_41_n120;
   wire mult_41_n119;
   wire mult_41_n118;
   wire mult_41_n117;
   wire mult_41_n116;
   wire mult_41_n115;
   wire mult_41_n114;
   wire mult_41_n113;
   wire mult_41_n112;
   wire mult_41_n111;
   wire mult_41_n110;
   wire mult_41_n109;
   wire mult_41_n108;
   wire mult_41_n107;
   wire mult_41_n106;
   wire mult_41_n105;
   wire mult_41_n103;
   wire mult_41_n102;
   wire mult_41_n101;
   wire mult_41_n100;
   wire mult_41_n99;
   wire mult_41_n98;
   wire mult_41_n97;
   wire mult_41_n96;
   wire mult_41_n95;
   wire mult_41_n94;
   wire mult_41_n93;
   wire mult_41_n91;
   wire mult_41_n90;
   wire mult_41_n89;
   wire mult_41_n88;
   wire mult_41_n87;
   wire mult_41_n86;
   wire mult_41_n84;
   wire mult_41_n83;
   wire mult_41_n82;
   wire mult_41_n81;
   wire mult_41_n80;
   wire mult_41_n79;
   wire mult_41_n78;
   wire mult_41_n77;
   wire mult_41_n76;
   wire mult_41_n75;
   wire mult_41_n74;
   wire mult_41_n73;
   wire mult_41_n72;
   wire mult_41_n71;
   wire mult_41_n70;
   wire mult_41_n69;
   wire mult_41_n68;
   wire mult_41_n67;
   wire mult_41_n66;
   wire mult_41_n65;
   wire mult_41_n64;
   wire mult_41_n63;
   wire mult_41_n62;
   wire mult_41_n61;
   wire mult_41_n60;
   wire mult_41_n59;
   wire mult_41_n58;
   wire mult_41_n57;
   wire mult_41_n56;
   wire mult_41_n55;
   wire mult_41_n54;
   wire mult_41_n52;
   wire mult_41_n51;
   wire mult_41_n50;
   wire mult_41_n49;
   wire mult_41_n48;
   wire mult_41_n47;
   wire mult_41_n46;
   wire mult_41_n45;
   wire mult_41_n44;
   wire mult_41_n43;
   wire mult_41_n42;
   wire mult_41_n41;
   wire mult_41_n40;
   wire mult_41_n39;
   wire mult_41_n38;
   wire mult_41_n37;
   wire mult_41_n36;
   wire mult_41_n35;
   wire mult_41_n34;
   wire mult_41_n33;
   wire mult_41_n32;
   wire mult_41_n31;
   wire mult_41_n30;
   wire mult_41_n29;
   wire mult_41_n28;
   wire mult_41_n27;
   wire mult_41_n26;
   wire mult_41_n25;
   wire mult_41_n24;
   wire mult_41_n23;
   wire mult_41_n22;
   wire mult_41_n21;
   wire mult_41_n20;
   wire mult_41_n19;
   wire mult_41_n18;
   wire mult_41_n17;
   wire mult_41_n16;
   wire mult_41_n15;
   wire mult_41_n8;
   wire mult_41_n7;
   wire mult_41_n6;
   wire mult_41_n5;
   wire mult_41_n4;
   wire mult_41_n3;
   wire mult_41_n2;
   wire [6:0] DIN1_reg_out;
   wire [6:0] fb_sh;
   wire [7:0] w;
   wire [6:0] DOUT_reg_in;
   wire [7:0] w2_reg_out;
   wire [7:1] sub_32_carry;
   wire [6:2] add_1_root_sub_0_root_add_37_carry;
   wire [6:1] sub_0_root_sub_0_root_add_37_carry;

   OAI21_X1 FE_RC_3_0 (.A(mult_40_n323),
	.B1(mult_40_n324),
	.B2(mult_40_n299),
	.ZN(mult_40_n322));
   AOI21_X1 FE_RC_2_0 (.A(mult_40_n356),
	.B1(mult_40_n355),
	.B2(mult_40_n354),
	.ZN(mult_40_n395));
   OAI21_X1 FE_RC_1_0 (.A(mult_40_n352),
	.B1(mult_40_n315),
	.B2(mult_40_n314),
	.ZN(mult_40_n142));
   AOI21_X1 FE_RC_0_0 (.A(mult_40_n368),
	.B1(FE_DBTN3_w_0),
	.B2(mult_40_n343),
	.ZN(mult_40_n369));
   INV_X1 FE_DBTC3_w_0 (.A(w[0]),
	.ZN(FE_DBTN3_w_0));
   INV_X2 FE_DBTC2_w_1 (.A(w[1]),
	.ZN(FE_DBTN2_w_1));
   INV_X1 FE_DBTC1_w_3 (.A(w[3]),
	.ZN(FE_DBTN1_w_3));
   INV_X2 FE_DBTC0_w_5 (.A(w[5]),
	.ZN(FE_DBTN0_w_5));
   DFFR_X1 VOUT_reg (.D(n93),
	.RN(RST_n),
	.CK(CLK),
	.Q(VOUT),
	.QN(n40));
   DFFR_X1 DIN1_reg_out_reg_6_ (.D(n92),
	.RN(RST_n),
	.CK(CLK),
	.Q(DIN1_reg_out[6]),
	.QN(n62));
   DFFR_X1 DIN1_reg_out_reg_5_ (.D(n91),
	.RN(RST_n),
	.CK(CLK),
	.Q(DIN1_reg_out[5]),
	.QN(n61));
   DFFR_X1 DIN1_reg_out_reg_4_ (.D(n90),
	.RN(RST_n),
	.CK(CLK),
	.Q(DIN1_reg_out[4]),
	.QN(n60));
   DFFR_X1 DIN1_reg_out_reg_3_ (.D(n89),
	.RN(RST_n),
	.CK(CLK),
	.Q(DIN1_reg_out[3]),
	.QN(n59));
   DFFR_X1 DIN1_reg_out_reg_2_ (.D(n88),
	.RN(RST_n),
	.CK(CLK),
	.Q(DIN1_reg_out[2]),
	.QN(n58));
   DFFR_X1 DIN1_reg_out_reg_1_ (.D(n87),
	.RN(RST_n),
	.CK(CLK),
	.Q(DIN1_reg_out[1]),
	.QN(n57));
   DFFR_X1 DIN1_reg_out_reg_0_ (.D(n86),
	.RN(RST_n),
	.CK(CLK),
	.Q(DIN1_reg_out[0]),
	.QN(n56));
   DFFR_X1 w1_reg_out_reg_0_ (.D(n85),
	.RN(RST_n),
	.CK(CLK),
	.QN(n99));
   DFFR_X1 w2_reg_out_reg_0_ (.D(n84),
	.RN(RST_n),
	.CK(CLK),
	.Q(w2_reg_out[0]),
	.QN(n100));
   DFFR_X1 w1_reg_out_reg_1_ (.D(n83),
	.RN(RST_n),
	.CK(CLK),
	.QN(n101));
   DFFR_X1 w2_reg_out_reg_1_ (.D(n82),
	.RN(RST_n),
	.CK(CLK),
	.Q(w2_reg_out[1]),
	.QN(n102));
   DFFR_X1 w1_reg_out_reg_2_ (.D(n81),
	.RN(RST_n),
	.CK(CLK),
	.QN(n103));
   DFFR_X1 w2_reg_out_reg_2_ (.D(n80),
	.RN(RST_n),
	.CK(CLK),
	.Q(w2_reg_out[2]),
	.QN(n104));
   DFFR_X1 w1_reg_out_reg_3_ (.D(n79),
	.RN(RST_n),
	.CK(CLK),
	.QN(n105));
   DFFR_X1 w2_reg_out_reg_3_ (.D(n78),
	.RN(RST_n),
	.CK(CLK),
	.Q(w2_reg_out[3]),
	.QN(n106));
   DFFR_X1 w1_reg_out_reg_4_ (.D(n77),
	.RN(RST_n),
	.CK(CLK),
	.QN(n107));
   DFFR_X1 w2_reg_out_reg_4_ (.D(n76),
	.RN(RST_n),
	.CK(CLK),
	.Q(w2_reg_out[4]),
	.QN(n108));
   DFFR_X1 w1_reg_out_reg_5_ (.D(n75),
	.RN(RST_n),
	.CK(CLK),
	.QN(n109));
   DFFR_X1 w2_reg_out_reg_5_ (.D(n74),
	.RN(RST_n),
	.CK(CLK),
	.Q(w2_reg_out[5]),
	.QN(n110));
   DFFR_X1 w1_reg_out_reg_6_ (.D(n73),
	.RN(RST_n),
	.CK(CLK),
	.QN(n111));
   DFFR_X1 w2_reg_out_reg_6_ (.D(n72),
	.RN(RST_n),
	.CK(CLK),
	.Q(w2_reg_out[6]),
	.QN(n112));
   DFFR_X1 w1_reg_out_reg_7_ (.D(n71),
	.RN(RST_n),
	.CK(CLK),
	.QN(n113));
   DFFR_X1 w2_reg_out_reg_7_ (.D(n70),
	.RN(RST_n),
	.CK(CLK),
	.Q(w2_reg_out[7]),
	.QN(n114));
   DFFR_X1 DOUT_reg_6_ (.D(n69),
	.RN(RST_n),
	.CK(CLK),
	.Q(DOUT[6]),
	.QN(n47));
   DFFR_X1 DOUT_reg_5_ (.D(n68),
	.RN(RST_n),
	.CK(CLK),
	.Q(DOUT[5]),
	.QN(n46));
   DFFR_X1 DOUT_reg_4_ (.D(n67),
	.RN(RST_n),
	.CK(CLK),
	.Q(DOUT[4]),
	.QN(n45));
   DFFR_X1 DOUT_reg_3_ (.D(n66),
	.RN(RST_n),
	.CK(CLK),
	.Q(DOUT[3]),
	.QN(n44));
   DFFR_X1 DOUT_reg_2_ (.D(n65),
	.RN(RST_n),
	.CK(CLK),
	.Q(DOUT[2]),
	.QN(n43));
   DFFR_X1 DOUT_reg_1_ (.D(n64),
	.RN(RST_n),
	.CK(CLK),
	.Q(DOUT[1]),
	.QN(n42));
   DFFR_X1 DOUT_reg_0_ (.D(n63),
	.RN(RST_n),
	.CK(CLK),
	.Q(DOUT[0]),
	.QN(n41));
   OAI21_X1 U73 (.A(n11),
	.B1(VIN),
	.B2(n113),
	.ZN(n71));
   NAND2_X1 U74 (.A1(w[7]),
	.A2(VIN),
	.ZN(n11));
   OAI21_X1 U75 (.A(n14),
	.B1(VIN),
	.B2(n111),
	.ZN(n73));
   NAND2_X1 U76 (.A1(w[6]),
	.A2(VIN),
	.ZN(n14));
   OAI21_X1 U77 (.A(n17),
	.B1(VIN),
	.B2(n109),
	.ZN(n75));
   NAND2_X1 U78 (.A1(w[5]),
	.A2(VIN),
	.ZN(n17));
   OAI21_X1 U79 (.A(n20),
	.B1(VIN),
	.B2(n107),
	.ZN(n77));
   NAND2_X1 U80 (.A1(w[4]),
	.A2(VIN),
	.ZN(n20));
   OAI21_X1 U81 (.A(n23),
	.B1(VIN),
	.B2(n105),
	.ZN(n79));
   NAND2_X1 U82 (.A1(w[3]),
	.A2(VIN),
	.ZN(n23));
   OAI21_X1 U83 (.A(n26),
	.B1(VIN),
	.B2(n103),
	.ZN(n81));
   NAND2_X1 U84 (.A1(w[2]),
	.A2(VIN),
	.ZN(n26));
   OAI21_X1 U85 (.A(n29),
	.B1(VIN),
	.B2(n101),
	.ZN(n83));
   NAND2_X1 U86 (.A1(w[1]),
	.A2(VIN),
	.ZN(n29));
   OAI21_X1 U87 (.A(n32),
	.B1(VIN),
	.B2(n99),
	.ZN(n85));
   NAND2_X1 U88 (.A1(w[0]),
	.A2(VIN),
	.ZN(n32));
   OAI21_X1 U89 (.A(n4),
	.B1(n44),
	.B2(VIN),
	.ZN(n66));
   NAND2_X1 U90 (.A1(DOUT_reg_in[3]),
	.A2(VIN),
	.ZN(n4));
   OAI21_X1 U91 (.A(n7),
	.B1(n47),
	.B2(VIN),
	.ZN(n69));
   NAND2_X1 U92 (.A1(DOUT_reg_in[6]),
	.A2(VIN),
	.ZN(n7));
   OAI21_X1 U93 (.A(n2),
	.B1(n42),
	.B2(VIN),
	.ZN(n64));
   NAND2_X1 U94 (.A1(DOUT_reg_in[1]),
	.A2(VIN),
	.ZN(n2));
   OAI21_X1 U95 (.A(n3),
	.B1(n43),
	.B2(VIN),
	.ZN(n65));
   NAND2_X1 U96 (.A1(DOUT_reg_in[2]),
	.A2(VIN),
	.ZN(n3));
   OAI21_X1 U97 (.A(n5),
	.B1(n45),
	.B2(VIN),
	.ZN(n67));
   NAND2_X1 U98 (.A1(DOUT_reg_in[4]),
	.A2(VIN),
	.ZN(n5));
   OAI21_X1 U99 (.A(n6),
	.B1(n46),
	.B2(VIN),
	.ZN(n68));
   NAND2_X1 U100 (.A1(DOUT_reg_in[5]),
	.A2(VIN),
	.ZN(n6));
   OAI21_X1 U101 (.A(n1),
	.B1(n41),
	.B2(VIN),
	.ZN(n63));
   NAND2_X1 U102 (.A1(VIN),
	.A2(DOUT_reg_in[0]),
	.ZN(n1));
   OAI22_X1 U103 (.A1(n98),
	.A2(n111),
	.B1(VIN),
	.B2(n112),
	.ZN(n72));
   OAI22_X1 U104 (.A1(n98),
	.A2(n113),
	.B1(VIN),
	.B2(n114),
	.ZN(n70));
   OAI22_X1 U105 (.A1(n98),
	.A2(n109),
	.B1(VIN),
	.B2(n110),
	.ZN(n74));
   OAI22_X1 U106 (.A1(n98),
	.A2(n107),
	.B1(VIN),
	.B2(n108),
	.ZN(n76));
   OAI22_X1 U107 (.A1(n98),
	.A2(n105),
	.B1(VIN),
	.B2(n106),
	.ZN(n78));
   OAI22_X1 U108 (.A1(n98),
	.A2(n103),
	.B1(VIN),
	.B2(n104),
	.ZN(n80));
   OAI22_X1 U109 (.A1(n98),
	.A2(n101),
	.B1(VIN),
	.B2(n102),
	.ZN(n82));
   OAI22_X1 U110 (.A1(n98),
	.A2(n99),
	.B1(VIN),
	.B2(n100),
	.ZN(n84));
   OAI21_X1 U111 (.A(n35),
	.B1(n58),
	.B2(VIN),
	.ZN(n88));
   NAND2_X1 U112 (.A1(DIN[2]),
	.A2(VIN),
	.ZN(n35));
   OAI21_X1 U113 (.A(n33),
	.B1(n56),
	.B2(VIN),
	.ZN(n86));
   NAND2_X1 U114 (.A1(DIN[0]),
	.A2(VIN),
	.ZN(n33));
   OAI21_X1 U115 (.A(n34),
	.B1(n57),
	.B2(VIN),
	.ZN(n87));
   NAND2_X1 U116 (.A1(DIN[1]),
	.A2(VIN),
	.ZN(n34));
   OAI21_X1 U117 (.A(n36),
	.B1(n59),
	.B2(VIN),
	.ZN(n89));
   NAND2_X1 U118 (.A1(DIN[3]),
	.A2(VIN),
	.ZN(n36));
   OAI21_X1 U119 (.A(n37),
	.B1(n60),
	.B2(VIN),
	.ZN(n90));
   NAND2_X1 U120 (.A1(DIN[4]),
	.A2(VIN),
	.ZN(n37));
   OAI21_X1 U121 (.A(n38),
	.B1(n61),
	.B2(VIN),
	.ZN(n91));
   NAND2_X1 U122 (.A1(DIN[5]),
	.A2(VIN),
	.ZN(n38));
   OAI21_X1 U123 (.A(n39),
	.B1(n62),
	.B2(VIN),
	.ZN(n92));
   NAND2_X1 U124 (.A1(DIN[6]),
	.A2(VIN),
	.ZN(n39));
   INV_X1 U125 (.A(VIN),
	.ZN(n98));
   NAND2_X1 U126 (.A1(n40),
	.A2(n98),
	.ZN(n93));
   INV_X1 sub_32_U10 (.A(fb_sh[5]),
	.ZN(sub_32_n3));
   INV_X1 sub_32_U9 (.A(fb_sh[4]),
	.ZN(sub_32_n4));
   INV_X1 sub_32_U8 (.A(fb_sh[3]),
	.ZN(sub_32_n5));
   INV_X1 sub_32_U7 (.A(fb_sh[2]),
	.ZN(sub_32_n6));
   INV_X1 sub_32_U6 (.A(DIN1_reg_out[0]),
	.ZN(sub_32_n1));
   INV_X1 sub_32_U5 (.A(fb_sh[1]),
	.ZN(sub_32_n7));
   NAND2_X1 sub_32_U4 (.A1(fb_sh[0]),
	.A2(sub_32_n1),
	.ZN(sub_32_carry[1]));
   XNOR2_X1 sub_32_U3 (.A(sub_32_n8),
	.B(DIN1_reg_out[0]),
	.ZN(w[0]));
   INV_X1 sub_32_U2 (.A(fb_sh[6]),
	.ZN(sub_32_n2));
   INV_X1 sub_32_U1 (.A(fb_sh[0]),
	.ZN(sub_32_n8));
   FA_X1 sub_32_U2_1 (.A(DIN1_reg_out[1]),
	.B(sub_32_n7),
	.CI(sub_32_carry[1]),
	.CO(sub_32_carry[2]),
	.S(w[1]));
   FA_X1 sub_32_U2_2 (.A(DIN1_reg_out[2]),
	.B(sub_32_n6),
	.CI(sub_32_carry[2]),
	.CO(sub_32_carry[3]),
	.S(w[2]));
   FA_X1 sub_32_U2_3 (.A(DIN1_reg_out[3]),
	.B(sub_32_n5),
	.CI(sub_32_carry[3]),
	.CO(sub_32_carry[4]),
	.S(w[3]));
   FA_X1 sub_32_U2_4 (.A(DIN1_reg_out[4]),
	.B(sub_32_n4),
	.CI(sub_32_carry[4]),
	.CO(sub_32_carry[5]),
	.S(w[4]));
   FA_X1 sub_32_U2_5 (.A(DIN1_reg_out[5]),
	.B(sub_32_n3),
	.CI(sub_32_carry[5]),
	.CO(sub_32_carry[6]),
	.S(w[5]));
   FA_X1 sub_32_U2_6 (.A(DIN1_reg_out[6]),
	.B(sub_32_n2),
	.CI(sub_32_carry[6]),
	.CO(sub_32_carry[7]),
	.S(w[6]));
   FA_X1 sub_32_U2_7 (.A(DIN1_reg_out[6]),
	.B(sub_32_n2),
	.CI(sub_32_carry[7]),
	.S(w[7]));
   NOR2_X1 mult_39_U179 (.A1(mult_39_n165),
	.A2(mult_39_n175),
	.ZN(mult_39_n100));
   NAND2_X1 mult_39_U178 (.A1(DIN[2]),
	.A2(H2[6]),
	.ZN(mult_39_n101));
   NOR2_X1 mult_39_U177 (.A1(mult_39_n170),
	.A2(mult_39_n166),
	.ZN(mult_39_n102));
   NOR2_X1 mult_39_U176 (.A1(mult_39_n171),
	.A2(mult_39_n166),
	.ZN(mult_39_n103));
   NOR2_X1 mult_39_U175 (.A1(mult_39_n172),
	.A2(mult_39_n166),
	.ZN(mult_39_n104));
   NOR2_X1 mult_39_U174 (.A1(mult_39_n173),
	.A2(mult_39_n166),
	.ZN(mult_39_n105));
   NOR2_X1 mult_39_U173 (.A1(mult_39_n174),
	.A2(mult_39_n166),
	.ZN(mult_39_n106));
   NAND2_X1 mult_39_U172 (.A1(DIN[1]),
	.A2(H2[6]),
	.ZN(mult_39_n108));
   NOR2_X1 mult_39_U171 (.A1(mult_39_n170),
	.A2(mult_39_n168),
	.ZN(mult_39_n109));
   NOR2_X1 mult_39_U170 (.A1(mult_39_n171),
	.A2(mult_39_n168),
	.ZN(mult_39_n110));
   NOR2_X1 mult_39_U169 (.A1(mult_39_n172),
	.A2(mult_39_n168),
	.ZN(mult_39_n111));
   NOR2_X1 mult_39_U168 (.A1(mult_39_n173),
	.A2(mult_39_n168),
	.ZN(mult_39_n112));
   NOR2_X1 mult_39_U167 (.A1(mult_39_n174),
	.A2(mult_39_n168),
	.ZN(mult_39_n113));
   NAND2_X1 mult_39_U166 (.A1(DIN[0]),
	.A2(H2[6]),
	.ZN(mult_39_n115));
   NOR2_X1 mult_39_U165 (.A1(mult_39_n170),
	.A2(mult_39_n169),
	.ZN(mult_39_n116));
   NOR2_X1 mult_39_U164 (.A1(mult_39_n171),
	.A2(mult_39_n169),
	.ZN(mult_39_n117));
   NOR2_X1 mult_39_U163 (.A1(mult_39_n172),
	.A2(mult_39_n169),
	.ZN(mult_39_n118));
   NOR2_X1 mult_39_U162 (.A1(mult_39_n173),
	.A2(mult_39_n169),
	.ZN(mult_39_n119));
   NAND2_X1 mult_39_U161 (.A1(H2[4]),
	.A2(DIN[3]),
	.ZN(mult_39_n184));
   NAND2_X1 mult_39_U160 (.A1(DIN[5]),
	.A2(H2[2]),
	.ZN(mult_39_n183));
   NAND2_X1 mult_39_U159 (.A1(mult_39_n184),
	.A2(mult_39_n183),
	.ZN(mult_39_n41));
   XNOR2_X1 mult_39_U158 (.A(mult_39_n183),
	.B(mult_39_n184),
	.ZN(mult_39_n42));
   NAND2_X1 mult_39_U157 (.A1(H2[5]),
	.A2(DIN[6]),
	.ZN(mult_39_n74));
   NAND2_X1 mult_39_U156 (.A1(H2[4]),
	.A2(DIN[6]),
	.ZN(mult_39_n75));
   NAND2_X1 mult_39_U155 (.A1(H2[3]),
	.A2(DIN[6]),
	.ZN(mult_39_n76));
   NAND2_X1 mult_39_U154 (.A1(H2[2]),
	.A2(DIN[6]),
	.ZN(mult_39_n77));
   NAND2_X1 mult_39_U153 (.A1(H2[1]),
	.A2(DIN[6]),
	.ZN(mult_39_n78));
   NAND2_X1 mult_39_U152 (.A1(H2[0]),
	.A2(DIN[6]),
	.ZN(mult_39_n79));
   NOR4_X1 mult_39_U151 (.A1(mult_39_n168),
	.A2(mult_39_n169),
	.A3(mult_39_n175),
	.A4(mult_39_n174),
	.ZN(mult_39_n181));
   NOR2_X1 mult_39_U150 (.A1(mult_39_n166),
	.A2(mult_39_n175),
	.ZN(mult_39_n182));
   AOI222_X1 mult_39_U149 (.A1(mult_39_n72),
	.A2(mult_39_n181),
	.B1(mult_39_n182),
	.B2(mult_39_n72),
	.C1(mult_39_n182),
	.C2(mult_39_n181),
	.ZN(mult_39_n180));
   OAI222_X1 mult_39_U148 (.A1(mult_39_n180),
	.A2(mult_39_n167),
	.B1(mult_39_n167),
	.B2(mult_39_n164),
	.C1(mult_39_n180),
	.C2(mult_39_n164),
	.ZN(mult_39_n179));
   AOI222_X1 mult_39_U147 (.A1(mult_39_n179),
	.A2(mult_39_n62),
	.B1(mult_39_n179),
	.B2(mult_39_n64),
	.C1(mult_39_n64),
	.C2(mult_39_n62),
	.ZN(mult_39_n178));
   OAI222_X1 mult_39_U146 (.A1(mult_39_n178),
	.A2(mult_39_n160),
	.B1(mult_39_n178),
	.B2(mult_39_n162),
	.C1(mult_39_n162),
	.C2(mult_39_n160),
	.ZN(mult_39_n8));
   NAND2_X1 mult_39_U145 (.A1(DIN[5]),
	.A2(H2[6]),
	.ZN(mult_39_n80));
   NOR2_X1 mult_39_U144 (.A1(mult_39_n170),
	.A2(mult_39_n161),
	.ZN(mult_39_n81));
   NOR2_X1 mult_39_U143 (.A1(mult_39_n171),
	.A2(mult_39_n161),
	.ZN(mult_39_n82));
   NOR2_X1 mult_39_U142 (.A1(mult_39_n172),
	.A2(mult_39_n161),
	.ZN(mult_39_n83));
   NOR2_X1 mult_39_U141 (.A1(mult_39_n174),
	.A2(mult_39_n161),
	.ZN(mult_39_n85));
   NOR2_X1 mult_39_U140 (.A1(mult_39_n175),
	.A2(mult_39_n161),
	.ZN(mult_39_n86));
   NAND2_X1 mult_39_U139 (.A1(DIN[4]),
	.A2(H2[6]),
	.ZN(mult_39_n87));
   NOR2_X1 mult_39_U138 (.A1(mult_39_n170),
	.A2(mult_39_n163),
	.ZN(mult_39_n88));
   NOR2_X1 mult_39_U137 (.A1(mult_39_n163),
	.A2(mult_39_n171),
	.ZN(mult_39_n89));
   NOR2_X1 mult_39_U136 (.A1(mult_39_n172),
	.A2(mult_39_n163),
	.ZN(mult_39_n90));
   NOR2_X1 mult_39_U135 (.A1(mult_39_n173),
	.A2(mult_39_n163),
	.ZN(mult_39_n91));
   NOR2_X1 mult_39_U134 (.A1(mult_39_n174),
	.A2(mult_39_n163),
	.ZN(mult_39_n92));
   NOR2_X1 mult_39_U133 (.A1(mult_39_n163),
	.A2(mult_39_n175),
	.ZN(mult_39_n93));
   NAND2_X1 mult_39_U132 (.A1(DIN[3]),
	.A2(H2[6]),
	.ZN(mult_39_n94));
   NOR2_X1 mult_39_U131 (.A1(mult_39_n165),
	.A2(mult_39_n170),
	.ZN(mult_39_n95));
   NOR2_X1 mult_39_U130 (.A1(mult_39_n165),
	.A2(mult_39_n172),
	.ZN(mult_39_n97));
   NOR2_X1 mult_39_U129 (.A1(mult_39_n165),
	.A2(mult_39_n173),
	.ZN(mult_39_n98));
   NOR2_X1 mult_39_U128 (.A1(mult_39_n165),
	.A2(mult_39_n174),
	.ZN(mult_39_n99));
   NAND2_X1 mult_39_U127 (.A1(H2[6]),
	.A2(DIN[6]),
	.ZN(mult_39_n176));
   XNOR2_X1 mult_39_U126 (.A(mult_39_n2),
	.B(mult_39_n13),
	.ZN(mult_39_n177));
   XOR2_X1 mult_39_U125 (.A(mult_39_n176),
	.B(mult_39_n177),
	.Z(din_b0_12_));
   INV_X1 mult_39_U124 (.A(DIN[5]),
	.ZN(mult_39_n161));
   INV_X1 mult_39_U123 (.A(DIN[0]),
	.ZN(mult_39_n169));
   INV_X1 mult_39_U122 (.A(H2[0]),
	.ZN(mult_39_n175));
   INV_X1 mult_39_U121 (.A(H2[4]),
	.ZN(mult_39_n171));
   INV_X1 mult_39_U120 (.A(H2[2]),
	.ZN(mult_39_n173));
   INV_X1 mult_39_U119 (.A(DIN[3]),
	.ZN(mult_39_n165));
   INV_X1 mult_39_U118 (.A(DIN[2]),
	.ZN(mult_39_n166));
   INV_X1 mult_39_U117 (.A(DIN[1]),
	.ZN(mult_39_n168));
   INV_X1 mult_39_U116 (.A(DIN[4]),
	.ZN(mult_39_n163));
   INV_X1 mult_39_U115 (.A(H2[1]),
	.ZN(mult_39_n174));
   INV_X1 mult_39_U114 (.A(H2[5]),
	.ZN(mult_39_n170));
   INV_X1 mult_39_U113 (.A(H2[3]),
	.ZN(mult_39_n172));
   INV_X1 mult_39_U112 (.A(mult_39_n68),
	.ZN(mult_39_n167));
   INV_X1 mult_39_U111 (.A(mult_39_n54),
	.ZN(mult_39_n160));
   INV_X1 mult_39_U110 (.A(mult_39_n61),
	.ZN(mult_39_n162));
   INV_X1 mult_39_U109 (.A(mult_39_n70),
	.ZN(mult_39_n164));
   HA_X1 mult_39_U44 (.A(mult_39_n113),
	.B(mult_39_n119),
	.CO(mult_39_n71),
	.S(mult_39_n72));
   HA_X1 mult_39_U43 (.A(mult_39_n100),
	.B(mult_39_n106),
	.CO(mult_39_n69),
	.S(mult_39_n70));
   FA_X1 mult_39_U42 (.A(mult_39_n112),
	.B(mult_39_n118),
	.CI(mult_39_n71),
	.CO(mult_39_n67),
	.S(mult_39_n68));
   HA_X1 mult_39_U41 (.A(mult_39_n93),
	.B(mult_39_n99),
	.CO(mult_39_n65),
	.S(mult_39_n66));
   FA_X1 mult_39_U40 (.A(mult_39_n105),
	.B(mult_39_n117),
	.CI(mult_39_n111),
	.CO(mult_39_n63),
	.S(mult_39_n64));
   FA_X1 mult_39_U39 (.A(mult_39_n66),
	.B(mult_39_n69),
	.CI(mult_39_n67),
	.CO(mult_39_n61),
	.S(mult_39_n62));
   HA_X1 mult_39_U38 (.A(mult_39_n86),
	.B(mult_39_n92),
	.CO(mult_39_n59),
	.S(mult_39_n60));
   FA_X1 mult_39_U37 (.A(mult_39_n98),
	.B(mult_39_n116),
	.CI(mult_39_n104),
	.CO(mult_39_n57),
	.S(mult_39_n58));
   FA_X1 mult_39_U36 (.A(mult_39_n65),
	.B(mult_39_n110),
	.CI(mult_39_n60),
	.CO(mult_39_n55),
	.S(mult_39_n56));
   FA_X1 mult_39_U35 (.A(mult_39_n58),
	.B(mult_39_n63),
	.CI(mult_39_n56),
	.CO(mult_39_n53),
	.S(mult_39_n54));
   HA_X1 mult_39_U34 (.A(mult_39_n97),
	.B(mult_39_n91),
	.CO(mult_39_n51),
	.S(mult_39_n52));
   FA_X1 mult_39_U33 (.A(mult_39_n85),
	.B(mult_39_n103),
	.CI(mult_39_n109),
	.CO(mult_39_n49),
	.S(mult_39_n50));
   FA_X1 mult_39_U32 (.A(mult_39_n79),
	.B(mult_39_n115),
	.CI(mult_39_n59),
	.CO(mult_39_n47),
	.S(mult_39_n48));
   FA_X1 mult_39_U31 (.A(mult_39_n57),
	.B(mult_39_n52),
	.CI(mult_39_n50),
	.CO(mult_39_n45),
	.S(mult_39_n46));
   FA_X1 mult_39_U30 (.A(mult_39_n48),
	.B(mult_39_n55),
	.CI(mult_39_n46),
	.CO(mult_39_n43),
	.S(mult_39_n44));
   FA_X1 mult_39_U27 (.A(mult_39_n102),
	.B(mult_39_n90),
	.CI(mult_39_n108),
	.CO(mult_39_n39),
	.S(mult_39_n40));
   FA_X1 mult_39_U26 (.A(mult_39_n51),
	.B(mult_39_n78),
	.CI(mult_39_n42),
	.CO(mult_39_n37),
	.S(mult_39_n38));
   FA_X1 mult_39_U25 (.A(mult_39_n47),
	.B(mult_39_n49),
	.CI(mult_39_n40),
	.CO(mult_39_n35),
	.S(mult_39_n36));
   FA_X1 mult_39_U24 (.A(mult_39_n45),
	.B(mult_39_n38),
	.CI(mult_39_n36),
	.CO(mult_39_n33),
	.S(mult_39_n34));
   FA_X1 mult_39_U23 (.A(mult_39_n83),
	.B(mult_39_n89),
	.CI(mult_39_n95),
	.CO(mult_39_n31),
	.S(mult_39_n32));
   FA_X1 mult_39_U22 (.A(mult_39_n77),
	.B(mult_39_n101),
	.CI(mult_39_n41),
	.CO(mult_39_n29),
	.S(mult_39_n30));
   FA_X1 mult_39_U21 (.A(mult_39_n32),
	.B(mult_39_n39),
	.CI(mult_39_n37),
	.CO(mult_39_n27),
	.S(mult_39_n28));
   FA_X1 mult_39_U20 (.A(mult_39_n35),
	.B(mult_39_n30),
	.CI(mult_39_n28),
	.CO(mult_39_n25),
	.S(mult_39_n26));
   FA_X1 mult_39_U19 (.A(mult_39_n82),
	.B(mult_39_n88),
	.CI(mult_39_n94),
	.CO(mult_39_n23),
	.S(mult_39_n24));
   FA_X1 mult_39_U18 (.A(mult_39_n31),
	.B(mult_39_n76),
	.CI(mult_39_n29),
	.CO(mult_39_n21),
	.S(mult_39_n22));
   FA_X1 mult_39_U17 (.A(mult_39_n27),
	.B(mult_39_n24),
	.CI(mult_39_n22),
	.CO(mult_39_n19),
	.S(mult_39_n20));
   FA_X1 mult_39_U16 (.A(mult_39_n87),
	.B(mult_39_n81),
	.CI(mult_39_n75),
	.CO(mult_39_n17),
	.S(mult_39_n18));
   FA_X1 mult_39_U15 (.A(mult_39_n18),
	.B(mult_39_n23),
	.CI(mult_39_n21),
	.CO(mult_39_n15),
	.S(mult_39_n16));
   FA_X1 mult_39_U14 (.A(mult_39_n74),
	.B(mult_39_n80),
	.CI(mult_39_n17),
	.CO(mult_39_n13),
	.S(mult_39_n14));
   FA_X1 mult_39_U8 (.A(mult_39_n44),
	.B(mult_39_n53),
	.CI(mult_39_n8),
	.CO(mult_39_n7),
	.S(din_b0_6_));
   FA_X1 mult_39_U7 (.A(mult_39_n34),
	.B(mult_39_n43),
	.CI(mult_39_n7),
	.CO(mult_39_n6),
	.S(din_b0_7_));
   FA_X1 mult_39_U6 (.A(mult_39_n26),
	.B(mult_39_n33),
	.CI(mult_39_n6),
	.CO(mult_39_n5),
	.S(din_b0_8_));
   FA_X1 mult_39_U5 (.A(mult_39_n20),
	.B(mult_39_n25),
	.CI(mult_39_n5),
	.CO(mult_39_n4),
	.S(din_b0_9_));
   FA_X1 mult_39_U4 (.A(mult_39_n16),
	.B(mult_39_n19),
	.CI(mult_39_n4),
	.CO(mult_39_n3),
	.S(din_b0_10_));
   FA_X1 mult_39_U3 (.A(mult_39_n15),
	.B(mult_39_n14),
	.CI(mult_39_n3),
	.CO(mult_39_n2),
	.S(din_b0_11_));
   NOR2_X1 mult_42_U203 (.A1(mult_42_n179),
	.A2(mult_42_n192),
	.ZN(mult_42_n100));
   NOR2_X1 mult_42_U202 (.A1(mult_42_n192),
	.A2(FE_DBTN0_w_5),
	.ZN(mult_42_n101));
   NOR2_X1 mult_42_U201 (.A1(mult_42_n192),
	.A2(mult_42_n182),
	.ZN(mult_42_n102));
   NOR2_X1 mult_42_U200 (.A1(mult_42_n192),
	.A2(FE_DBTN1_w_3),
	.ZN(mult_42_n103));
   NOR2_X1 mult_42_U199 (.A1(mult_42_n192),
	.A2(FE_DBTN2_w_1),
	.ZN(mult_42_n105));
   NOR2_X1 mult_42_U198 (.A1(mult_42_n192),
	.A2(FE_DBTN3_w_0),
	.ZN(mult_42_n106));
   NAND2_X1 mult_42_U197 (.A1(H3[3]),
	.A2(w[7]),
	.ZN(mult_42_n107));
   NOR2_X1 mult_42_U196 (.A1(mult_42_n179),
	.A2(mult_42_n193),
	.ZN(mult_42_n108));
   NOR2_X1 mult_42_U195 (.A1(FE_DBTN0_w_5),
	.A2(mult_42_n193),
	.ZN(mult_42_n109));
   NOR2_X1 mult_42_U194 (.A1(mult_42_n182),
	.A2(mult_42_n193),
	.ZN(mult_42_n110));
   NOR2_X1 mult_42_U193 (.A1(FE_DBTN1_w_3),
	.A2(mult_42_n193),
	.ZN(mult_42_n111));
   NOR2_X1 mult_42_U192 (.A1(mult_42_n187),
	.A2(mult_42_n193),
	.ZN(mult_42_n112));
   NOR2_X1 mult_42_U191 (.A1(FE_DBTN2_w_1),
	.A2(mult_42_n193),
	.ZN(mult_42_n113));
   NOR2_X1 mult_42_U190 (.A1(FE_DBTN3_w_0),
	.A2(mult_42_n193),
	.ZN(mult_42_n114));
   NAND2_X1 mult_42_U189 (.A1(H3[2]),
	.A2(w[7]),
	.ZN(mult_42_n115));
   NOR2_X1 mult_42_U188 (.A1(mult_42_n179),
	.A2(mult_42_n194),
	.ZN(mult_42_n116));
   NOR2_X1 mult_42_U187 (.A1(FE_DBTN0_w_5),
	.A2(mult_42_n194),
	.ZN(mult_42_n117));
   NOR2_X1 mult_42_U186 (.A1(mult_42_n182),
	.A2(mult_42_n194),
	.ZN(mult_42_n118));
   NOR2_X1 mult_42_U185 (.A1(FE_DBTN1_w_3),
	.A2(mult_42_n194),
	.ZN(mult_42_n119));
   NOR2_X1 mult_42_U184 (.A1(mult_42_n187),
	.A2(mult_42_n194),
	.ZN(mult_42_n120));
   NOR2_X1 mult_42_U183 (.A1(FE_DBTN2_w_1),
	.A2(mult_42_n194),
	.ZN(mult_42_n121));
   NAND2_X1 mult_42_U182 (.A1(H3[1]),
	.A2(w[7]),
	.ZN(mult_42_n123));
   NOR2_X1 mult_42_U181 (.A1(mult_42_n179),
	.A2(mult_42_n195),
	.ZN(mult_42_n124));
   NOR2_X1 mult_42_U180 (.A1(FE_DBTN0_w_5),
	.A2(mult_42_n195),
	.ZN(mult_42_n125));
   NOR2_X1 mult_42_U179 (.A1(mult_42_n182),
	.A2(mult_42_n195),
	.ZN(mult_42_n126));
   NOR2_X1 mult_42_U178 (.A1(FE_DBTN1_w_3),
	.A2(mult_42_n195),
	.ZN(mult_42_n127));
   NOR2_X1 mult_42_U177 (.A1(mult_42_n187),
	.A2(mult_42_n195),
	.ZN(mult_42_n128));
   NOR2_X1 mult_42_U176 (.A1(FE_DBTN2_w_1),
	.A2(mult_42_n195),
	.ZN(mult_42_n129));
   NAND2_X1 mult_42_U175 (.A1(H3[0]),
	.A2(w[7]),
	.ZN(mult_42_n131));
   NOR2_X1 mult_42_U174 (.A1(FE_DBTN0_w_5),
	.A2(mult_42_n196),
	.ZN(mult_42_n133));
   NOR2_X1 mult_42_U173 (.A1(mult_42_n182),
	.A2(mult_42_n196),
	.ZN(mult_42_n134));
   NOR2_X1 mult_42_U172 (.A1(FE_DBTN1_w_3),
	.A2(mult_42_n196),
	.ZN(mult_42_n135));
   NOR2_X1 mult_42_U171 (.A1(mult_42_n187),
	.A2(mult_42_n196),
	.ZN(mult_42_n136));
   NAND2_X1 mult_42_U170 (.A1(w[2]),
	.A2(H3[5]),
	.ZN(mult_42_n54));
   NAND2_X1 mult_42_U169 (.A1(H3[0]),
	.A2(w[6]),
	.ZN(mult_42_n208));
   NAND2_X1 mult_42_U168 (.A1(w[2]),
	.A2(H3[4]),
	.ZN(mult_42_n207));
   NAND2_X1 mult_42_U167 (.A1(mult_42_n208),
	.A2(mult_42_n207),
	.ZN(mult_42_n63));
   XNOR2_X1 mult_42_U166 (.A(mult_42_n207),
	.B(mult_42_n208),
	.ZN(mult_42_n64));
   NOR4_X1 mult_42_U165 (.A1(mult_42_n195),
	.A2(mult_42_n196),
	.A3(FE_DBTN2_w_1),
	.A4(FE_DBTN3_w_0),
	.ZN(mult_42_n205));
   NOR2_X1 mult_42_U164 (.A1(mult_42_n194),
	.A2(FE_DBTN3_w_0),
	.ZN(mult_42_n206));
   AOI222_X1 mult_42_U163 (.A1(mult_42_n84),
	.A2(mult_42_n205),
	.B1(mult_42_n206),
	.B2(mult_42_n84),
	.C1(mult_42_n206),
	.C2(mult_42_n205),
	.ZN(mult_42_n204));
   OAI222_X1 mult_42_U162 (.A1(mult_42_n204),
	.A2(mult_42_n184),
	.B1(mult_42_n184),
	.B2(mult_42_n188),
	.C1(mult_42_n204),
	.C2(mult_42_n188),
	.ZN(mult_42_n203));
   AOI222_X1 mult_42_U161 (.A1(mult_42_n203),
	.A2(mult_42_n74),
	.B1(mult_42_n203),
	.B2(mult_42_n76),
	.C1(mult_42_n76),
	.C2(mult_42_n74),
	.ZN(mult_42_n202));
   OAI222_X1 mult_42_U160 (.A1(mult_42_n202),
	.A2(mult_42_n180),
	.B1(mult_42_n202),
	.B2(mult_42_n183),
	.C1(mult_42_n183),
	.C2(mult_42_n180),
	.ZN(mult_42_n8));
   NAND2_X1 mult_42_U159 (.A1(w[5]),
	.A2(H3[6]),
	.ZN(mult_42_n86));
   NAND2_X1 mult_42_U158 (.A1(w[4]),
	.A2(H3[6]),
	.ZN(mult_42_n87));
   NAND2_X1 mult_42_U157 (.A1(w[3]),
	.A2(H3[6]),
	.ZN(mult_42_n88));
   NAND2_X1 mult_42_U156 (.A1(w[2]),
	.A2(H3[6]),
	.ZN(mult_42_n89));
   NAND2_X1 mult_42_U155 (.A1(w[1]),
	.A2(H3[6]),
	.ZN(mult_42_n90));
   NAND2_X1 mult_42_U154 (.A1(w[0]),
	.A2(H3[6]),
	.ZN(mult_42_n91));
   NOR2_X1 mult_42_U153 (.A1(mult_42_n191),
	.A2(mult_42_n179),
	.ZN(mult_42_n93));
   NOR2_X1 mult_42_U152 (.A1(mult_42_n191),
	.A2(FE_DBTN0_w_5),
	.ZN(mult_42_n94));
   NOR2_X1 mult_42_U151 (.A1(mult_42_n191),
	.A2(mult_42_n182),
	.ZN(mult_42_n95));
   NOR2_X1 mult_42_U150 (.A1(mult_42_n191),
	.A2(FE_DBTN1_w_3),
	.ZN(mult_42_n96));
   NOR2_X1 mult_42_U149 (.A1(mult_42_n191),
	.A2(FE_DBTN2_w_1),
	.ZN(mult_42_n97));
   NOR2_X1 mult_42_U148 (.A1(mult_42_n191),
	.A2(FE_DBTN3_w_0),
	.ZN(mult_42_n98));
   NAND2_X1 mult_42_U147 (.A1(H3[4]),
	.A2(w[7]),
	.ZN(mult_42_n99));
   XNOR2_X1 mult_42_U146 (.A(mult_42_n2),
	.B(mult_42_n17),
	.ZN(mult_42_n201));
   XOR2_X1 mult_42_U145 (.A(mult_42_n201),
	.B(mult_42_n15),
	.Z(mult_42_n197));
   NAND2_X1 mult_42_U144 (.A1(H3[5]),
	.A2(w[7]),
	.ZN(mult_42_n199));
   AND2_X1 mult_42_U143 (.A1(w[6]),
	.A2(H3[6]),
	.ZN(mult_42_n200));
   XOR2_X1 mult_42_U142 (.A(mult_42_n199),
	.B(mult_42_n200),
	.Z(mult_42_n198));
   XOR2_X1 mult_42_U141 (.A(mult_42_n197),
	.B(mult_42_n198),
	.Z(ff_sh_6_));
   INV_X1 mult_42_U140 (.A(H3[0]),
	.ZN(mult_42_n196));
   INV_X1 mult_42_U139 (.A(H3[4]),
	.ZN(mult_42_n192));
   INV_X1 mult_42_U138 (.A(H3[5]),
	.ZN(mult_42_n191));
   INV_X1 mult_42_U137 (.A(H3[3]),
	.ZN(mult_42_n193));
   INV_X1 mult_42_U136 (.A(H3[2]),
	.ZN(mult_42_n194));
   INV_X1 mult_42_U135 (.A(H3[1]),
	.ZN(mult_42_n195));
   INV_X1 mult_42_U133 (.A(w[2]),
	.ZN(mult_42_n187));
   INV_X1 mult_42_U132 (.A(mult_42_n54),
	.ZN(mult_42_n186));
   INV_X1 mult_42_U131 (.A(w[4]),
	.ZN(mult_42_n182));
   INV_X1 mult_42_U127 (.A(w[6]),
	.ZN(mult_42_n179));
   INV_X1 mult_42_U126 (.A(mult_42_n80),
	.ZN(mult_42_n184));
   INV_X1 mult_42_U125 (.A(mult_42_n82),
	.ZN(mult_42_n188));
   INV_X1 mult_42_U124 (.A(mult_42_n73),
	.ZN(mult_42_n183));
   INV_X1 mult_42_U123 (.A(mult_42_n66),
	.ZN(mult_42_n180));
   HA_X1 mult_42_U51 (.A(mult_42_n129),
	.B(mult_42_n136),
	.CO(mult_42_n83),
	.S(mult_42_n84));
   HA_X1 mult_42_U50 (.A(mult_42_n114),
	.B(mult_42_n121),
	.CO(mult_42_n81),
	.S(mult_42_n82));
   FA_X1 mult_42_U49 (.A(mult_42_n128),
	.B(mult_42_n135),
	.CI(mult_42_n83),
	.CO(mult_42_n79),
	.S(mult_42_n80));
   HA_X1 mult_42_U48 (.A(mult_42_n106),
	.B(mult_42_n113),
	.CO(mult_42_n77),
	.S(mult_42_n78));
   FA_X1 mult_42_U47 (.A(mult_42_n120),
	.B(mult_42_n134),
	.CI(mult_42_n127),
	.CO(mult_42_n75),
	.S(mult_42_n76));
   FA_X1 mult_42_U46 (.A(mult_42_n78),
	.B(mult_42_n81),
	.CI(mult_42_n79),
	.CO(mult_42_n73),
	.S(mult_42_n74));
   HA_X1 mult_42_U45 (.A(mult_42_n98),
	.B(mult_42_n105),
	.CO(mult_42_n71),
	.S(mult_42_n72));
   FA_X1 mult_42_U44 (.A(mult_42_n112),
	.B(mult_42_n133),
	.CI(mult_42_n119),
	.CO(mult_42_n69),
	.S(mult_42_n70));
   FA_X1 mult_42_U43 (.A(mult_42_n77),
	.B(mult_42_n126),
	.CI(mult_42_n72),
	.CO(mult_42_n67),
	.S(mult_42_n68));
   FA_X1 mult_42_U42 (.A(mult_42_n70),
	.B(mult_42_n75),
	.CI(mult_42_n68),
	.CO(mult_42_n65),
	.S(mult_42_n66));
   FA_X1 mult_42_U39 (.A(mult_42_n97),
	.B(mult_42_n125),
	.CI(mult_42_n111),
	.CO(mult_42_n61),
	.S(mult_42_n62));
   FA_X1 mult_42_U38 (.A(mult_42_n91),
	.B(mult_42_n118),
	.CI(mult_42_n71),
	.CO(mult_42_n59),
	.S(mult_42_n60));
   FA_X1 mult_42_U37 (.A(mult_42_n69),
	.B(mult_42_n64),
	.CI(mult_42_n62),
	.CO(mult_42_n57),
	.S(mult_42_n58));
   FA_X1 mult_42_U36 (.A(mult_42_n60),
	.B(mult_42_n67),
	.CI(mult_42_n58),
	.CO(mult_42_n55),
	.S(mult_42_n56));
   FA_X1 mult_42_U34 (.A(mult_42_n103),
	.B(mult_42_n110),
	.CI(mult_42_n124),
	.CO(mult_42_n51),
	.S(mult_42_n52));
   FA_X1 mult_42_U33 (.A(mult_42_n131),
	.B(mult_42_n117),
	.CI(mult_42_n90),
	.CO(mult_42_n49),
	.S(mult_42_n50));
   FA_X1 mult_42_U32 (.A(mult_42_n63),
	.B(mult_42_n54),
	.CI(mult_42_n61),
	.CO(mult_42_n47),
	.S(mult_42_n48));
   FA_X1 mult_42_U31 (.A(mult_42_n52),
	.B(mult_42_n59),
	.CI(mult_42_n50),
	.CO(mult_42_n45),
	.S(mult_42_n46));
   FA_X1 mult_42_U30 (.A(mult_42_n48),
	.B(mult_42_n57),
	.CI(mult_42_n46),
	.CO(mult_42_n43),
	.S(mult_42_n44));
   FA_X1 mult_42_U29 (.A(mult_42_n102),
	.B(mult_42_n186),
	.CI(mult_42_n96),
	.CO(mult_42_n41),
	.S(mult_42_n42));
   FA_X1 mult_42_U28 (.A(mult_42_n116),
	.B(mult_42_n109),
	.CI(mult_42_n123),
	.CO(mult_42_n39),
	.S(mult_42_n40));
   FA_X1 mult_42_U27 (.A(mult_42_n51),
	.B(mult_42_n89),
	.CI(mult_42_n49),
	.CO(mult_42_n37),
	.S(mult_42_n38));
   FA_X1 mult_42_U26 (.A(mult_42_n40),
	.B(mult_42_n42),
	.CI(mult_42_n47),
	.CO(mult_42_n35),
	.S(mult_42_n36));
   FA_X1 mult_42_U25 (.A(mult_42_n38),
	.B(mult_42_n45),
	.CI(mult_42_n36),
	.CO(mult_42_n33),
	.S(mult_42_n34));
   FA_X1 mult_42_U24 (.A(mult_42_n95),
	.B(mult_42_n101),
	.CI(mult_42_n108),
	.CO(mult_42_n31),
	.S(mult_42_n32));
   FA_X1 mult_42_U23 (.A(mult_42_n88),
	.B(mult_42_n115),
	.CI(mult_42_n41),
	.CO(mult_42_n29),
	.S(mult_42_n30));
   FA_X1 mult_42_U22 (.A(mult_42_n32),
	.B(mult_42_n39),
	.CI(mult_42_n37),
	.CO(mult_42_n27),
	.S(mult_42_n28));
   FA_X1 mult_42_U21 (.A(mult_42_n35),
	.B(mult_42_n30),
	.CI(mult_42_n28),
	.CO(mult_42_n25),
	.S(mult_42_n26));
   FA_X1 mult_42_U20 (.A(mult_42_n94),
	.B(mult_42_n100),
	.CI(mult_42_n107),
	.CO(mult_42_n23),
	.S(mult_42_n24));
   FA_X1 mult_42_U19 (.A(mult_42_n31),
	.B(mult_42_n87),
	.CI(mult_42_n24),
	.CO(mult_42_n21),
	.S(mult_42_n22));
   FA_X1 mult_42_U18 (.A(mult_42_n27),
	.B(mult_42_n29),
	.CI(mult_42_n22),
	.CO(mult_42_n19),
	.S(mult_42_n20));
   FA_X1 mult_42_U17 (.A(mult_42_n99),
	.B(mult_42_n93),
	.CI(mult_42_n86),
	.CO(mult_42_n17),
	.S(mult_42_n18));
   FA_X1 mult_42_U16 (.A(mult_42_n18),
	.B(mult_42_n23),
	.CI(mult_42_n21),
	.CO(mult_42_n15),
	.S(mult_42_n16));
   FA_X1 mult_42_U8 (.A(mult_42_n56),
	.B(mult_42_n65),
	.CI(mult_42_n8),
	.CO(mult_42_n7),
	.S(ff_sh_0_));
   FA_X1 mult_42_U7 (.A(mult_42_n44),
	.B(mult_42_n55),
	.CI(mult_42_n7),
	.CO(mult_42_n6),
	.S(ff_sh_1_));
   FA_X1 mult_42_U6 (.A(mult_42_n34),
	.B(mult_42_n43),
	.CI(mult_42_n6),
	.CO(mult_42_n5),
	.S(ff_sh_2_));
   FA_X1 mult_42_U5 (.A(mult_42_n26),
	.B(mult_42_n33),
	.CI(mult_42_n5),
	.CO(mult_42_n4),
	.S(ff_sh_3_));
   FA_X1 mult_42_U4 (.A(mult_42_n20),
	.B(mult_42_n25),
	.CI(mult_42_n4),
	.CO(mult_42_n3),
	.S(ff_sh_4_));
   FA_X1 mult_42_U3 (.A(mult_42_n19),
	.B(mult_42_n16),
	.CI(mult_42_n3),
	.CO(mult_42_n2),
	.S(ff_sh_5_));
   XOR2_X1 mult_40_U401 (.A(w[6]),
	.B(w[5]),
	.Z(mult_40_n324));
   XOR2_X1 mult_40_U400 (.A(w[7]),
	.B(w[6]),
	.Z(mult_40_n409));
   NAND2_X1 mult_40_U399 (.A1(mult_40_n304),
	.A2(mult_40_n409),
	.ZN(mult_40_n350));
   NAND3_X1 mult_40_U398 (.A1(mult_40_n324),
	.A2(mult_40_n320),
	.A3(w[7]),
	.ZN(mult_40_n408));
   OAI21_X1 mult_40_U397 (.A(mult_40_n408),
	.B1(mult_40_n302),
	.B2(mult_40_n350),
	.ZN(mult_40_n110));
   XOR2_X1 mult_40_U396 (.A(w[5]),
	.B(w[4]),
	.Z(mult_40_n407));
   NAND2_X1 mult_40_U395 (.A1(mult_40_n355),
	.A2(mult_40_n407),
	.ZN(mult_40_n354));
   OR3_X1 mult_40_U394 (.A1(mult_40_n355),
	.A2(H4[0]),
	.A3(FE_DBTN0_w_5),
	.ZN(mult_40_n406));
   OAI21_X1 mult_40_U393 (.A(mult_40_n406),
	.B1(FE_DBTN0_w_5),
	.B2(mult_40_n354),
	.ZN(mult_40_n111));
   XOR2_X1 mult_40_U392 (.A(H4[11]),
	.B(mult_40_n302),
	.Z(mult_40_n405));
   XOR2_X1 mult_40_U391 (.A(H4[12]),
	.B(mult_40_n302),
	.Z(mult_40_n357));
   OAI22_X1 mult_40_U390 (.A1(mult_40_n405),
	.A2(mult_40_n350),
	.B1(mult_40_n304),
	.B2(mult_40_n357),
	.ZN(mult_40_n115));
   XOR2_X1 mult_40_U389 (.A(H4[10]),
	.B(mult_40_n302),
	.Z(mult_40_n404));
   OAI22_X1 mult_40_U388 (.A1(mult_40_n404),
	.A2(mult_40_n350),
	.B1(mult_40_n304),
	.B2(mult_40_n405),
	.ZN(mult_40_n116));
   XOR2_X1 mult_40_U387 (.A(H4[9]),
	.B(mult_40_n302),
	.Z(mult_40_n403));
   OAI22_X1 mult_40_U386 (.A1(mult_40_n403),
	.A2(mult_40_n350),
	.B1(mult_40_n304),
	.B2(mult_40_n404),
	.ZN(mult_40_n117));
   XOR2_X1 mult_40_U385 (.A(H4[8]),
	.B(mult_40_n302),
	.Z(mult_40_n351));
   OAI22_X1 mult_40_U384 (.A1(mult_40_n351),
	.A2(mult_40_n350),
	.B1(mult_40_n304),
	.B2(mult_40_n403),
	.ZN(mult_40_n118));
   XOR2_X1 mult_40_U383 (.A(H4[6]),
	.B(mult_40_n302),
	.Z(mult_40_n402));
   XOR2_X1 mult_40_U382 (.A(H4[7]),
	.B(mult_40_n302),
	.Z(mult_40_n349));
   OAI22_X1 mult_40_U381 (.A1(mult_40_n402),
	.A2(mult_40_n350),
	.B1(mult_40_n304),
	.B2(mult_40_n349),
	.ZN(mult_40_n120));
   XOR2_X1 mult_40_U380 (.A(H4[5]),
	.B(mult_40_n302),
	.Z(mult_40_n401));
   OAI22_X1 mult_40_U379 (.A1(mult_40_n401),
	.A2(mult_40_n350),
	.B1(mult_40_n304),
	.B2(mult_40_n402),
	.ZN(mult_40_n121));
   XOR2_X1 mult_40_U378 (.A(H4[4]),
	.B(mult_40_n302),
	.Z(mult_40_n400));
   OAI22_X1 mult_40_U377 (.A1(mult_40_n400),
	.A2(mult_40_n350),
	.B1(mult_40_n304),
	.B2(mult_40_n401),
	.ZN(mult_40_n122));
   XOR2_X1 mult_40_U376 (.A(H4[3]),
	.B(mult_40_n302),
	.Z(mult_40_n399));
   OAI22_X1 mult_40_U375 (.A1(mult_40_n399),
	.A2(mult_40_n350),
	.B1(mult_40_n304),
	.B2(mult_40_n400),
	.ZN(mult_40_n123));
   XOR2_X1 mult_40_U374 (.A(H4[2]),
	.B(mult_40_n302),
	.Z(mult_40_n398));
   OAI22_X1 mult_40_U373 (.A1(mult_40_n398),
	.A2(mult_40_n350),
	.B1(mult_40_n304),
	.B2(mult_40_n399),
	.ZN(mult_40_n124));
   XOR2_X1 mult_40_U372 (.A(H4[1]),
	.B(mult_40_n302),
	.Z(mult_40_n397));
   OAI22_X1 mult_40_U371 (.A1(mult_40_n397),
	.A2(mult_40_n350),
	.B1(mult_40_n304),
	.B2(mult_40_n398),
	.ZN(mult_40_n125));
   XOR2_X1 mult_40_U370 (.A(mult_40_n320),
	.B(w[7]),
	.Z(mult_40_n396));
   OAI22_X1 mult_40_U369 (.A1(mult_40_n396),
	.A2(mult_40_n350),
	.B1(mult_40_n304),
	.B2(mult_40_n397),
	.ZN(mult_40_n126));
   NOR2_X1 mult_40_U368 (.A1(mult_40_n304),
	.A2(mult_40_n320),
	.ZN(mult_40_n127));
   XOR2_X1 mult_40_U367 (.A(H4[13]),
	.B(FE_DBTN0_w_5),
	.Z(mult_40_n356));
   XOR2_X1 mult_40_U365 (.A(H4[11]),
	.B(FE_DBTN0_w_5),
	.Z(mult_40_n394));
   XOR2_X1 mult_40_U364 (.A(H4[12]),
	.B(FE_DBTN0_w_5),
	.Z(mult_40_n353));
   OAI22_X1 mult_40_U363 (.A1(mult_40_n394),
	.A2(mult_40_n354),
	.B1(mult_40_n355),
	.B2(mult_40_n353),
	.ZN(mult_40_n129));
   XOR2_X1 mult_40_U362 (.A(H4[10]),
	.B(FE_DBTN0_w_5),
	.Z(mult_40_n393));
   OAI22_X1 mult_40_U361 (.A1(mult_40_n393),
	.A2(mult_40_n354),
	.B1(mult_40_n355),
	.B2(mult_40_n394),
	.ZN(mult_40_n130));
   XOR2_X1 mult_40_U360 (.A(H4[9]),
	.B(FE_DBTN0_w_5),
	.Z(mult_40_n392));
   OAI22_X1 mult_40_U359 (.A1(mult_40_n392),
	.A2(mult_40_n354),
	.B1(mult_40_n355),
	.B2(mult_40_n393),
	.ZN(mult_40_n131));
   XOR2_X1 mult_40_U358 (.A(H4[8]),
	.B(FE_DBTN0_w_5),
	.Z(mult_40_n391));
   OAI22_X1 mult_40_U357 (.A1(mult_40_n391),
	.A2(mult_40_n354),
	.B1(mult_40_n355),
	.B2(mult_40_n392),
	.ZN(mult_40_n132));
   XOR2_X1 mult_40_U356 (.A(H4[7]),
	.B(FE_DBTN0_w_5),
	.Z(mult_40_n390));
   OAI22_X1 mult_40_U355 (.A1(mult_40_n390),
	.A2(mult_40_n354),
	.B1(mult_40_n355),
	.B2(mult_40_n391),
	.ZN(mult_40_n133));
   XOR2_X1 mult_40_U354 (.A(H4[6]),
	.B(FE_DBTN0_w_5),
	.Z(mult_40_n389));
   OAI22_X1 mult_40_U353 (.A1(mult_40_n389),
	.A2(mult_40_n354),
	.B1(mult_40_n355),
	.B2(mult_40_n390),
	.ZN(mult_40_n134));
   XOR2_X1 mult_40_U352 (.A(H4[5]),
	.B(FE_DBTN0_w_5),
	.Z(mult_40_n388));
   OAI22_X1 mult_40_U351 (.A1(mult_40_n388),
	.A2(mult_40_n354),
	.B1(mult_40_n355),
	.B2(mult_40_n389),
	.ZN(mult_40_n135));
   XOR2_X1 mult_40_U350 (.A(H4[4]),
	.B(FE_DBTN0_w_5),
	.Z(mult_40_n387));
   OAI22_X1 mult_40_U349 (.A1(mult_40_n387),
	.A2(mult_40_n354),
	.B1(mult_40_n355),
	.B2(mult_40_n388),
	.ZN(mult_40_n136));
   XOR2_X1 mult_40_U348 (.A(H4[3]),
	.B(FE_DBTN0_w_5),
	.Z(mult_40_n386));
   OAI22_X1 mult_40_U347 (.A1(mult_40_n386),
	.A2(mult_40_n354),
	.B1(mult_40_n355),
	.B2(mult_40_n387),
	.ZN(mult_40_n137));
   XOR2_X1 mult_40_U346 (.A(H4[2]),
	.B(FE_DBTN0_w_5),
	.Z(mult_40_n385));
   OAI22_X1 mult_40_U345 (.A1(mult_40_n385),
	.A2(mult_40_n354),
	.B1(mult_40_n355),
	.B2(mult_40_n386),
	.ZN(mult_40_n138));
   XOR2_X1 mult_40_U344 (.A(H4[1]),
	.B(FE_DBTN0_w_5),
	.Z(mult_40_n384));
   OAI22_X1 mult_40_U343 (.A1(mult_40_n384),
	.A2(mult_40_n354),
	.B1(mult_40_n355),
	.B2(mult_40_n385),
	.ZN(mult_40_n139));
   XOR2_X1 mult_40_U342 (.A(mult_40_n320),
	.B(w[5]),
	.Z(mult_40_n383));
   OAI22_X1 mult_40_U341 (.A1(mult_40_n383),
	.A2(mult_40_n354),
	.B1(mult_40_n355),
	.B2(mult_40_n384),
	.ZN(mult_40_n140));
   NOR2_X1 mult_40_U340 (.A1(mult_40_n355),
	.A2(mult_40_n320),
	.ZN(mult_40_n141));
   XOR2_X1 mult_40_U339 (.A(H4[13]),
	.B(w[3]),
	.Z(mult_40_n352));
   XOR2_X1 mult_40_U338 (.A(w[3]),
	.B(w[2]),
	.Z(mult_40_n382));
   NAND2_X1 mult_40_U337 (.A1(mult_40_n338),
	.A2(mult_40_n382),
	.ZN(mult_40_n371));
   XOR2_X1 mult_40_U335 (.A(H4[10]),
	.B(FE_DBTN1_w_3),
	.Z(mult_40_n381));
   XOR2_X1 mult_40_U334 (.A(H4[11]),
	.B(FE_DBTN1_w_3),
	.Z(mult_40_n348));
   OAI22_X1 mult_40_U333 (.A1(mult_40_n381),
	.A2(mult_40_n371),
	.B1(mult_40_n338),
	.B2(mult_40_n348),
	.ZN(mult_40_n144));
   XOR2_X1 mult_40_U332 (.A(H4[9]),
	.B(FE_DBTN1_w_3),
	.Z(mult_40_n380));
   OAI22_X1 mult_40_U331 (.A1(mult_40_n380),
	.A2(mult_40_n371),
	.B1(mult_40_n338),
	.B2(mult_40_n381),
	.ZN(mult_40_n145));
   XOR2_X1 mult_40_U330 (.A(H4[8]),
	.B(FE_DBTN1_w_3),
	.Z(mult_40_n379));
   OAI22_X1 mult_40_U329 (.A1(mult_40_n379),
	.A2(mult_40_n371),
	.B1(mult_40_n338),
	.B2(mult_40_n380),
	.ZN(mult_40_n146));
   XOR2_X1 mult_40_U328 (.A(H4[7]),
	.B(FE_DBTN1_w_3),
	.Z(mult_40_n378));
   OAI22_X1 mult_40_U327 (.A1(mult_40_n378),
	.A2(mult_40_n371),
	.B1(mult_40_n338),
	.B2(mult_40_n379),
	.ZN(mult_40_n147));
   XOR2_X1 mult_40_U326 (.A(H4[6]),
	.B(FE_DBTN1_w_3),
	.Z(mult_40_n377));
   OAI22_X1 mult_40_U325 (.A1(mult_40_n377),
	.A2(mult_40_n371),
	.B1(mult_40_n338),
	.B2(mult_40_n378),
	.ZN(mult_40_n148));
   XOR2_X1 mult_40_U324 (.A(H4[5]),
	.B(FE_DBTN1_w_3),
	.Z(mult_40_n376));
   OAI22_X1 mult_40_U323 (.A1(mult_40_n376),
	.A2(mult_40_n371),
	.B1(mult_40_n338),
	.B2(mult_40_n377),
	.ZN(mult_40_n149));
   XOR2_X1 mult_40_U322 (.A(H4[4]),
	.B(FE_DBTN1_w_3),
	.Z(mult_40_n375));
   OAI22_X1 mult_40_U321 (.A1(mult_40_n375),
	.A2(mult_40_n371),
	.B1(mult_40_n338),
	.B2(mult_40_n376),
	.ZN(mult_40_n150));
   XOR2_X1 mult_40_U320 (.A(H4[3]),
	.B(FE_DBTN1_w_3),
	.Z(mult_40_n374));
   OAI22_X1 mult_40_U319 (.A1(mult_40_n374),
	.A2(mult_40_n371),
	.B1(mult_40_n338),
	.B2(mult_40_n375),
	.ZN(mult_40_n151));
   XOR2_X1 mult_40_U318 (.A(H4[2]),
	.B(FE_DBTN1_w_3),
	.Z(mult_40_n373));
   OAI22_X1 mult_40_U317 (.A1(mult_40_n373),
	.A2(mult_40_n371),
	.B1(mult_40_n338),
	.B2(mult_40_n374),
	.ZN(mult_40_n152));
   XOR2_X1 mult_40_U316 (.A(H4[1]),
	.B(FE_DBTN1_w_3),
	.Z(mult_40_n372));
   OAI22_X1 mult_40_U315 (.A1(mult_40_n372),
	.A2(mult_40_n371),
	.B1(mult_40_n338),
	.B2(mult_40_n373),
	.ZN(mult_40_n153));
   XOR2_X1 mult_40_U314 (.A(mult_40_n320),
	.B(w[3]),
	.Z(mult_40_n370));
   OAI22_X1 mult_40_U313 (.A1(mult_40_n370),
	.A2(mult_40_n371),
	.B1(mult_40_n338),
	.B2(mult_40_n372),
	.ZN(mult_40_n154));
   XNOR2_X1 mult_40_U312 (.A(H4[13]),
	.B(w[1]),
	.ZN(mult_40_n368));
   NAND2_X1 mult_40_U311 (.A1(w[1]),
	.A2(FE_DBTN3_w_0),
	.ZN(mult_40_n343));
   XOR2_X1 mult_40_U309 (.A(H4[12]),
	.B(FE_DBTN2_w_1),
	.Z(mult_40_n367));
   OAI22_X1 mult_40_U308 (.A1(mult_40_n367),
	.A2(mult_40_n343),
	.B1(mult_40_n368),
	.B2(FE_DBTN3_w_0),
	.ZN(mult_40_n157));
   XOR2_X1 mult_40_U307 (.A(H4[11]),
	.B(FE_DBTN2_w_1),
	.Z(mult_40_n366));
   OAI22_X1 mult_40_U306 (.A1(mult_40_n366),
	.A2(mult_40_n343),
	.B1(mult_40_n367),
	.B2(FE_DBTN3_w_0),
	.ZN(mult_40_n158));
   XOR2_X1 mult_40_U305 (.A(H4[10]),
	.B(FE_DBTN2_w_1),
	.Z(mult_40_n365));
   OAI22_X1 mult_40_U304 (.A1(mult_40_n365),
	.A2(mult_40_n343),
	.B1(mult_40_n366),
	.B2(FE_DBTN3_w_0),
	.ZN(mult_40_n159));
   XOR2_X1 mult_40_U303 (.A(H4[9]),
	.B(FE_DBTN2_w_1),
	.Z(mult_40_n364));
   OAI22_X1 mult_40_U302 (.A1(mult_40_n364),
	.A2(mult_40_n343),
	.B1(mult_40_n365),
	.B2(FE_DBTN3_w_0),
	.ZN(mult_40_n160));
   XOR2_X1 mult_40_U301 (.A(H4[8]),
	.B(FE_DBTN2_w_1),
	.Z(mult_40_n363));
   OAI22_X1 mult_40_U300 (.A1(mult_40_n363),
	.A2(mult_40_n343),
	.B1(mult_40_n364),
	.B2(FE_DBTN3_w_0),
	.ZN(mult_40_n161));
   XOR2_X1 mult_40_U299 (.A(H4[7]),
	.B(FE_DBTN2_w_1),
	.Z(mult_40_n362));
   OAI22_X1 mult_40_U298 (.A1(mult_40_n362),
	.A2(mult_40_n343),
	.B1(mult_40_n363),
	.B2(FE_DBTN3_w_0),
	.ZN(mult_40_n162));
   XOR2_X1 mult_40_U297 (.A(H4[6]),
	.B(FE_DBTN2_w_1),
	.Z(mult_40_n361));
   OAI22_X1 mult_40_U296 (.A1(mult_40_n361),
	.A2(mult_40_n343),
	.B1(mult_40_n362),
	.B2(FE_DBTN3_w_0),
	.ZN(mult_40_n163));
   XOR2_X1 mult_40_U295 (.A(H4[5]),
	.B(FE_DBTN2_w_1),
	.Z(mult_40_n360));
   OAI22_X1 mult_40_U294 (.A1(mult_40_n360),
	.A2(mult_40_n343),
	.B1(mult_40_n361),
	.B2(FE_DBTN3_w_0),
	.ZN(mult_40_n164));
   XOR2_X1 mult_40_U293 (.A(H4[4]),
	.B(FE_DBTN2_w_1),
	.Z(mult_40_n359));
   OAI22_X1 mult_40_U292 (.A1(mult_40_n359),
	.A2(mult_40_n343),
	.B1(mult_40_n360),
	.B2(FE_DBTN3_w_0),
	.ZN(mult_40_n165));
   XOR2_X1 mult_40_U291 (.A(H4[3]),
	.B(FE_DBTN2_w_1),
	.Z(mult_40_n358));
   OAI22_X1 mult_40_U290 (.A1(mult_40_n358),
	.A2(mult_40_n343),
	.B1(mult_40_n359),
	.B2(FE_DBTN3_w_0),
	.ZN(mult_40_n166));
   XOR2_X1 mult_40_U289 (.A(H4[2]),
	.B(FE_DBTN2_w_1),
	.Z(mult_40_n344));
   OAI22_X1 mult_40_U288 (.A1(mult_40_n344),
	.A2(mult_40_n343),
	.B1(mult_40_n358),
	.B2(FE_DBTN3_w_0),
	.ZN(mult_40_n167));
   XOR2_X1 mult_40_U287 (.A(H4[13]),
	.B(w[7]),
	.Z(mult_40_n323));
   AOI22_X1 mult_40_U286 (.A1(mult_40_n301),
	.A2(mult_40_n299),
	.B1(mult_40_n324),
	.B2(mult_40_n323),
	.ZN(mult_40_n22));
   OAI22_X1 mult_40_U285 (.A1(mult_40_n353),
	.A2(mult_40_n354),
	.B1(mult_40_n355),
	.B2(mult_40_n356),
	.ZN(mult_40_n27));
   XOR2_X1 mult_40_U284 (.A(H4[12]),
	.B(w[3]),
	.Z(mult_40_n347));
   AOI22_X1 mult_40_U283 (.A1(mult_40_n347),
	.A2(mult_40_n314),
	.B1(mult_40_n315),
	.B2(mult_40_n352),
	.ZN(mult_40_n38));
   OAI22_X1 mult_40_U282 (.A1(mult_40_n349),
	.A2(mult_40_n350),
	.B1(mult_40_n304),
	.B2(mult_40_n351),
	.ZN(mult_40_n345));
   AOI22_X1 mult_40_U281 (.A1(mult_40_n312),
	.A2(mult_40_n314),
	.B1(mult_40_n315),
	.B2(mult_40_n347),
	.ZN(mult_40_n346));
   NAND2_X1 mult_40_U280 (.A1(mult_40_n300),
	.A2(mult_40_n346),
	.ZN(mult_40_n43));
   XOR2_X1 mult_40_U279 (.A(mult_40_n345),
	.B(mult_40_n346),
	.Z(mult_40_n44));
   NOR2_X1 mult_40_U278 (.A1(FE_DBTN2_w_1),
	.A2(H4[1]),
	.ZN(mult_40_n342));
   OAI22_X1 mult_40_U277 (.A1(mult_40_n317),
	.A2(mult_40_n343),
	.B1(mult_40_n344),
	.B2(FE_DBTN3_w_0),
	.ZN(mult_40_n341));
   NAND2_X1 mult_40_U276 (.A1(mult_40_n342),
	.A2(mult_40_n341),
	.ZN(mult_40_n339));
   NAND2_X1 mult_40_U275 (.A1(mult_40_n315),
	.A2(mult_40_n341),
	.ZN(mult_40_n340));
   MUX2_X1 mult_40_U274 (.A(mult_40_n339),
	.B(mult_40_n340),
	.S(H4[0]),
	.Z(mult_40_n335));
   NOR3_X1 mult_40_U273 (.A1(mult_40_n338),
	.A2(H4[0]),
	.A3(FE_DBTN1_w_3),
	.ZN(mult_40_n337));
   AOI21_X1 mult_40_U272 (.A(mult_40_n337),
	.B1(w[3]),
	.B2(mult_40_n314),
	.ZN(mult_40_n336));
   OAI222_X1 mult_40_U271 (.A1(mult_40_n335),
	.A2(mult_40_n311),
	.B1(mult_40_n336),
	.B2(mult_40_n335),
	.C1(mult_40_n336),
	.C2(mult_40_n311),
	.ZN(mult_40_n334));
   AOI222_X1 mult_40_U270 (.A1(mult_40_n334),
	.A2(mult_40_n96),
	.B1(mult_40_n334),
	.B2(mult_40_n97),
	.C1(mult_40_n97),
	.C2(mult_40_n96),
	.ZN(mult_40_n333));
   OAI222_X1 mult_40_U269 (.A1(mult_40_n333),
	.A2(mult_40_n305),
	.B1(mult_40_n333),
	.B2(mult_40_n309),
	.C1(mult_40_n309),
	.C2(mult_40_n305),
	.ZN(mult_40_n332));
   AOI222_X1 mult_40_U268 (.A1(mult_40_n332),
	.A2(mult_40_n88),
	.B1(mult_40_n332),
	.B2(mult_40_n91),
	.C1(mult_40_n91),
	.C2(mult_40_n88),
	.ZN(mult_40_n331));
   OAI222_X1 mult_40_U267 (.A1(mult_40_n331),
	.A2(mult_40_n294),
	.B1(mult_40_n331),
	.B2(mult_40_n303),
	.C1(mult_40_n303),
	.C2(mult_40_n294),
	.ZN(mult_40_n330));
   AOI222_X1 mult_40_U266 (.A1(mult_40_n330),
	.A2(mult_40_n76),
	.B1(mult_40_n330),
	.B2(mult_40_n81),
	.C1(mult_40_n81),
	.C2(mult_40_n76),
	.ZN(mult_40_n329));
   OAI222_X1 mult_40_U265 (.A1(mult_40_n329),
	.A2(mult_40_n292),
	.B1(mult_40_n329),
	.B2(mult_40_n293),
	.C1(mult_40_n293),
	.C2(mult_40_n292),
	.ZN(mult_40_n328));
   AOI222_X1 mult_40_U264 (.A1(mult_40_n328),
	.A2(mult_40_n64),
	.B1(mult_40_n328),
	.B2(mult_40_n69),
	.C1(mult_40_n69),
	.C2(mult_40_n64),
	.ZN(mult_40_n327));
   OAI222_X1 mult_40_U263 (.A1(mult_40_n327),
	.A2(mult_40_n297),
	.B1(mult_40_n327),
	.B2(mult_40_n298),
	.C1(mult_40_n298),
	.C2(mult_40_n297),
	.ZN(mult_40_n326));
   AOI222_X1 mult_40_U262 (.A1(mult_40_n326),
	.A2(mult_40_n52),
	.B1(mult_40_n326),
	.B2(mult_40_n57),
	.C1(mult_40_n57),
	.C2(mult_40_n52),
	.ZN(mult_40_n325));
   OAI222_X1 mult_40_U261 (.A1(mult_40_n325),
	.A2(mult_40_n295),
	.B1(mult_40_n325),
	.B2(mult_40_n296),
	.C1(mult_40_n296),
	.C2(mult_40_n295),
	.ZN(mult_40_n8));
   XOR2_X1 mult_40_U259 (.A(mult_40_n2),
	.B(mult_40_n322),
	.Z(mult_40_n321));
   XNOR2_X1 mult_40_U258 (.A(mult_40_n22),
	.B(mult_40_n321),
	.ZN(w_a1b0_20_));
   XNOR2_X2 mult_40_U257 (.A(w[4]),
	.B(w[3]),
	.ZN(mult_40_n355));
   XOR2_X2 mult_40_U256 (.A(w[2]),
	.B(FE_DBTN2_w_1),
	.Z(mult_40_n338));
   INV_X1 mult_40_U255 (.A(H4[0]),
	.ZN(mult_40_n320));
   INV_X1 mult_40_U254 (.A(mult_40_n98),
	.ZN(mult_40_n311));
   INV_X1 mult_40_U253 (.A(mult_40_n38),
	.ZN(mult_40_n310));
   INV_X1 mult_40_U252 (.A(mult_40_n395),
	.ZN(mult_40_n306));
   INV_X1 mult_40_U251 (.A(mult_40_n27),
	.ZN(mult_40_n307));
   INV_X1 mult_40_U250 (.A(mult_40_n348),
	.ZN(mult_40_n312));
   INV_X1 mult_40_U249 (.A(mult_40_n357),
	.ZN(mult_40_n301));
   INV_X1 mult_40_U248 (.A(mult_40_n92),
	.ZN(mult_40_n305));
   INV_X1 mult_40_U247 (.A(mult_40_n95),
	.ZN(mult_40_n309));
   INV_X1 mult_40_U246 (.A(mult_40_n369),
	.ZN(mult_40_n316));
   INV_X1 mult_40_U244 (.A(mult_40_n342),
	.ZN(mult_40_n317));
   INV_X1 mult_40_U242 (.A(w[7]),
	.ZN(mult_40_n302));
   INV_X1 mult_40_U239 (.A(mult_40_n350),
	.ZN(mult_40_n299));
   INV_X1 mult_40_U238 (.A(mult_40_n345),
	.ZN(mult_40_n300));
   INV_X1 mult_40_U237 (.A(mult_40_n338),
	.ZN(mult_40_n315));
   INV_X1 mult_40_U236 (.A(mult_40_n371),
	.ZN(mult_40_n314));
   INV_X1 mult_40_U235 (.A(mult_40_n324),
	.ZN(mult_40_n304));
   INV_X1 mult_40_U234 (.A(mult_40_n87),
	.ZN(mult_40_n303));
   INV_X1 mult_40_U233 (.A(mult_40_n82),
	.ZN(mult_40_n294));
   INV_X1 mult_40_U232 (.A(mult_40_n46),
	.ZN(mult_40_n295));
   INV_X1 mult_40_U231 (.A(mult_40_n51),
	.ZN(mult_40_n296));
   INV_X1 mult_40_U230 (.A(mult_40_n58),
	.ZN(mult_40_n297));
   INV_X1 mult_40_U229 (.A(mult_40_n63),
	.ZN(mult_40_n298));
   INV_X1 mult_40_U228 (.A(mult_40_n70),
	.ZN(mult_40_n292));
   INV_X1 mult_40_U227 (.A(mult_40_n75),
	.ZN(mult_40_n293));
   HA_X1 mult_40_U61 (.A(mult_40_n154),
	.B(mult_40_n167),
	.CO(mult_40_n97),
	.S(mult_40_n98));
   FA_X1 mult_40_U60 (.A(mult_40_n166),
	.B(mult_40_n141),
	.CI(mult_40_n153),
	.CO(mult_40_n95),
	.S(mult_40_n96));
   HA_X1 mult_40_U59 (.A(mult_40_n111),
	.B(mult_40_n140),
	.CO(mult_40_n93),
	.S(mult_40_n94));
   FA_X1 mult_40_U58 (.A(mult_40_n152),
	.B(mult_40_n165),
	.CI(mult_40_n94),
	.CO(mult_40_n91),
	.S(mult_40_n92));
   FA_X1 mult_40_U57 (.A(mult_40_n164),
	.B(mult_40_n127),
	.CI(mult_40_n151),
	.CO(mult_40_n89),
	.S(mult_40_n90));
   FA_X1 mult_40_U56 (.A(mult_40_n93),
	.B(mult_40_n139),
	.CI(mult_40_n90),
	.CO(mult_40_n87),
	.S(mult_40_n88));
   HA_X1 mult_40_U55 (.A(mult_40_n110),
	.B(mult_40_n126),
	.CO(mult_40_n85),
	.S(mult_40_n86));
   FA_X1 mult_40_U54 (.A(mult_40_n138),
	.B(mult_40_n163),
	.CI(mult_40_n150),
	.CO(mult_40_n83),
	.S(mult_40_n84));
   FA_X1 mult_40_U53 (.A(mult_40_n89),
	.B(mult_40_n86),
	.CI(mult_40_n84),
	.CO(mult_40_n81),
	.S(mult_40_n82));
   HA_X1 mult_40_U52 (.A(mult_40_n125),
	.B(mult_40_n137),
	.CO(mult_40_n79),
	.S(mult_40_n80));
   FA_X1 mult_40_U51 (.A(mult_40_n149),
	.B(mult_40_n162),
	.CI(mult_40_n85),
	.CO(mult_40_n77),
	.S(mult_40_n78));
   FA_X1 mult_40_U50 (.A(mult_40_n83),
	.B(mult_40_n80),
	.CI(mult_40_n78),
	.CO(mult_40_n75),
	.S(mult_40_n76));
   HA_X1 mult_40_U49 (.A(mult_40_n124),
	.B(mult_40_n136),
	.CO(mult_40_n73),
	.S(mult_40_n74));
   FA_X1 mult_40_U48 (.A(mult_40_n148),
	.B(mult_40_n161),
	.CI(mult_40_n79),
	.CO(mult_40_n71),
	.S(mult_40_n72));
   FA_X1 mult_40_U47 (.A(mult_40_n77),
	.B(mult_40_n74),
	.CI(mult_40_n72),
	.CO(mult_40_n69),
	.S(mult_40_n70));
   HA_X1 mult_40_U46 (.A(mult_40_n123),
	.B(mult_40_n135),
	.CO(mult_40_n67),
	.S(mult_40_n68));
   FA_X1 mult_40_U45 (.A(mult_40_n147),
	.B(mult_40_n160),
	.CI(mult_40_n73),
	.CO(mult_40_n65),
	.S(mult_40_n66));
   FA_X1 mult_40_U44 (.A(mult_40_n71),
	.B(mult_40_n68),
	.CI(mult_40_n66),
	.CO(mult_40_n63),
	.S(mult_40_n64));
   HA_X1 mult_40_U43 (.A(mult_40_n122),
	.B(mult_40_n134),
	.CO(mult_40_n61),
	.S(mult_40_n62));
   FA_X1 mult_40_U42 (.A(mult_40_n146),
	.B(mult_40_n159),
	.CI(mult_40_n67),
	.CO(mult_40_n59),
	.S(mult_40_n60));
   FA_X1 mult_40_U41 (.A(mult_40_n65),
	.B(mult_40_n62),
	.CI(mult_40_n60),
	.CO(mult_40_n57),
	.S(mult_40_n58));
   HA_X1 mult_40_U40 (.A(mult_40_n121),
	.B(mult_40_n133),
	.CO(mult_40_n55),
	.S(mult_40_n56));
   FA_X1 mult_40_U39 (.A(mult_40_n145),
	.B(mult_40_n158),
	.CI(mult_40_n61),
	.CO(mult_40_n53),
	.S(mult_40_n54));
   FA_X1 mult_40_U38 (.A(mult_40_n59),
	.B(mult_40_n56),
	.CI(mult_40_n54),
	.CO(mult_40_n51),
	.S(mult_40_n52));
   HA_X1 mult_40_U37 (.A(mult_40_n120),
	.B(mult_40_n132),
	.CO(mult_40_n49),
	.S(mult_40_n50));
   FA_X1 mult_40_U36 (.A(mult_40_n144),
	.B(mult_40_n157),
	.CI(mult_40_n55),
	.CO(mult_40_n47),
	.S(mult_40_n48));
   FA_X1 mult_40_U35 (.A(mult_40_n53),
	.B(mult_40_n50),
	.CI(mult_40_n48),
	.CO(mult_40_n45),
	.S(mult_40_n46));
   FA_X1 mult_40_U32 (.A(mult_40_n316),
	.B(mult_40_n131),
	.CI(mult_40_n49),
	.CO(mult_40_n41),
	.S(mult_40_n42));
   FA_X1 mult_40_U31 (.A(mult_40_n47),
	.B(mult_40_n44),
	.CI(mult_40_n42),
	.CO(mult_40_n39),
	.S(mult_40_n40));
   FA_X1 mult_40_U29 (.A(mult_40_n118),
	.B(mult_40_n130),
	.CI(mult_40_n38),
	.CO(mult_40_n35),
	.S(mult_40_n36));
   FA_X1 mult_40_U28 (.A(mult_40_n41),
	.B(mult_40_n43),
	.CI(mult_40_n36),
	.CO(mult_40_n33),
	.S(mult_40_n34));
   FA_X1 mult_40_U27 (.A(mult_40_n129),
	.B(mult_40_n310),
	.CI(mult_40_n142),
	.CO(mult_40_n31),
	.S(mult_40_n32));
   FA_X1 mult_40_U26 (.A(mult_40_n35),
	.B(mult_40_n117),
	.CI(mult_40_n32),
	.CO(mult_40_n29),
	.S(mult_40_n30));
   FA_X1 mult_40_U24 (.A(mult_40_n307),
	.B(mult_40_n116),
	.CI(mult_40_n31),
	.CO(mult_40_n25),
	.S(mult_40_n26));
   FA_X1 mult_40_U23 (.A(mult_40_n115),
	.B(mult_40_n27),
	.CI(mult_40_n306),
	.CO(mult_40_n23),
	.S(mult_40_n24));
   FA_X1 mult_40_U8 (.A(mult_40_n40),
	.B(mult_40_n45),
	.CI(mult_40_n8),
	.CO(mult_40_n7),
	.S(w_a1b0_14_));
   FA_X1 mult_40_U7 (.A(mult_40_n34),
	.B(mult_40_n39),
	.CI(mult_40_n7),
	.CO(mult_40_n6),
	.S(w_a1b0_15_));
   FA_X1 mult_40_U6 (.A(mult_40_n30),
	.B(mult_40_n33),
	.CI(mult_40_n6),
	.CO(mult_40_n5),
	.S(w_a1b0_16_));
   FA_X1 mult_40_U5 (.A(mult_40_n26),
	.B(mult_40_n29),
	.CI(mult_40_n5),
	.CO(mult_40_n4),
	.S(w_a1b0_17_));
   FA_X1 mult_40_U4 (.A(mult_40_n25),
	.B(mult_40_n24),
	.CI(mult_40_n4),
	.CO(mult_40_n3),
	.S(w_a1b0_18_));
   FA_X1 mult_40_U3 (.A(mult_40_n23),
	.B(mult_40_n22),
	.CI(mult_40_n3),
	.CO(mult_40_n2),
	.S(w_a1b0_19_));
   XOR2_X1 add_1_root_sub_0_root_add_37_U2 (.A(ff_sh_0_),
	.B(din_b0_6_),
	.Z(w_add_0_));
   AND2_X1 add_1_root_sub_0_root_add_37_U1 (.A1(ff_sh_0_),
	.A2(din_b0_6_),
	.ZN(add_1_root_sub_0_root_add_37_n1));
   FA_X1 add_1_root_sub_0_root_add_37_U1_1 (.A(din_b0_7_),
	.B(ff_sh_1_),
	.CI(add_1_root_sub_0_root_add_37_n1),
	.CO(add_1_root_sub_0_root_add_37_carry[2]),
	.S(w_add_1_));
   FA_X1 add_1_root_sub_0_root_add_37_U1_2 (.A(din_b0_8_),
	.B(ff_sh_2_),
	.CI(add_1_root_sub_0_root_add_37_carry[2]),
	.CO(add_1_root_sub_0_root_add_37_carry[3]),
	.S(w_add_2_));
   FA_X1 add_1_root_sub_0_root_add_37_U1_3 (.A(din_b0_9_),
	.B(ff_sh_3_),
	.CI(add_1_root_sub_0_root_add_37_carry[3]),
	.CO(add_1_root_sub_0_root_add_37_carry[4]),
	.S(w_add_3_));
   FA_X1 add_1_root_sub_0_root_add_37_U1_4 (.A(din_b0_10_),
	.B(ff_sh_4_),
	.CI(add_1_root_sub_0_root_add_37_carry[4]),
	.CO(add_1_root_sub_0_root_add_37_carry[5]),
	.S(w_add_4_));
   FA_X1 add_1_root_sub_0_root_add_37_U1_5 (.A(din_b0_11_),
	.B(ff_sh_5_),
	.CI(add_1_root_sub_0_root_add_37_carry[5]),
	.CO(add_1_root_sub_0_root_add_37_carry[6]),
	.S(w_add_5_));
   FA_X1 add_1_root_sub_0_root_add_37_U1_6 (.A(din_b0_12_),
	.B(ff_sh_6_),
	.CI(add_1_root_sub_0_root_add_37_carry[6]),
	.S(w_add_6_));
   XNOR2_X1 sub_0_root_sub_0_root_add_37_U10 (.A(sub_0_root_sub_0_root_add_37_n8),
	.B(w_add_0_),
	.ZN(DOUT_reg_in[0]));
   INV_X1 sub_0_root_sub_0_root_add_37_U9 (.A(w_a1b0_20_),
	.ZN(sub_0_root_sub_0_root_add_37_n2));
   INV_X1 sub_0_root_sub_0_root_add_37_U8 (.A(w_a1b0_19_),
	.ZN(sub_0_root_sub_0_root_add_37_n3));
   INV_X1 sub_0_root_sub_0_root_add_37_U7 (.A(w_a1b0_18_),
	.ZN(sub_0_root_sub_0_root_add_37_n4));
   INV_X1 sub_0_root_sub_0_root_add_37_U6 (.A(w_a1b0_17_),
	.ZN(sub_0_root_sub_0_root_add_37_n5));
   INV_X1 sub_0_root_sub_0_root_add_37_U5 (.A(w_a1b0_16_),
	.ZN(sub_0_root_sub_0_root_add_37_n6));
   INV_X1 sub_0_root_sub_0_root_add_37_U4 (.A(w_add_0_),
	.ZN(sub_0_root_sub_0_root_add_37_n1));
   INV_X1 sub_0_root_sub_0_root_add_37_U3 (.A(w_a1b0_15_),
	.ZN(sub_0_root_sub_0_root_add_37_n7));
   NAND2_X1 sub_0_root_sub_0_root_add_37_U2 (.A1(w_a1b0_14_),
	.A2(sub_0_root_sub_0_root_add_37_n1),
	.ZN(sub_0_root_sub_0_root_add_37_carry[1]));
   INV_X1 sub_0_root_sub_0_root_add_37_U1 (.A(w_a1b0_14_),
	.ZN(sub_0_root_sub_0_root_add_37_n8));
   FA_X1 sub_0_root_sub_0_root_add_37_U2_1 (.A(w_add_1_),
	.B(sub_0_root_sub_0_root_add_37_n7),
	.CI(sub_0_root_sub_0_root_add_37_carry[1]),
	.CO(sub_0_root_sub_0_root_add_37_carry[2]),
	.S(DOUT_reg_in[1]));
   FA_X1 sub_0_root_sub_0_root_add_37_U2_2 (.A(w_add_2_),
	.B(sub_0_root_sub_0_root_add_37_n6),
	.CI(sub_0_root_sub_0_root_add_37_carry[2]),
	.CO(sub_0_root_sub_0_root_add_37_carry[3]),
	.S(DOUT_reg_in[2]));
   FA_X1 sub_0_root_sub_0_root_add_37_U2_3 (.A(w_add_3_),
	.B(sub_0_root_sub_0_root_add_37_n5),
	.CI(sub_0_root_sub_0_root_add_37_carry[3]),
	.CO(sub_0_root_sub_0_root_add_37_carry[4]),
	.S(DOUT_reg_in[3]));
   FA_X1 sub_0_root_sub_0_root_add_37_U2_4 (.A(w_add_4_),
	.B(sub_0_root_sub_0_root_add_37_n4),
	.CI(sub_0_root_sub_0_root_add_37_carry[4]),
	.CO(sub_0_root_sub_0_root_add_37_carry[5]),
	.S(DOUT_reg_in[4]));
   FA_X1 sub_0_root_sub_0_root_add_37_U2_5 (.A(w_add_5_),
	.B(sub_0_root_sub_0_root_add_37_n3),
	.CI(sub_0_root_sub_0_root_add_37_carry[5]),
	.CO(sub_0_root_sub_0_root_add_37_carry[6]),
	.S(DOUT_reg_in[5]));
   FA_X1 sub_0_root_sub_0_root_add_37_U2_6 (.A(w_add_6_),
	.B(sub_0_root_sub_0_root_add_37_n2),
	.CI(sub_0_root_sub_0_root_add_37_carry[6]),
	.S(DOUT_reg_in[6]));
   NOR2_X1 mult_41_U203 (.A1(mult_41_n196),
	.A2(mult_41_n183),
	.ZN(mult_41_n100));
   NOR2_X1 mult_41_U202 (.A1(mult_41_n183),
	.A2(mult_41_n195),
	.ZN(mult_41_n101));
   NOR2_X1 mult_41_U201 (.A1(mult_41_n183),
	.A2(mult_41_n194),
	.ZN(mult_41_n102));
   NOR2_X1 mult_41_U200 (.A1(mult_41_n183),
	.A2(mult_41_n193),
	.ZN(mult_41_n103));
   NOR2_X1 mult_41_U199 (.A1(mult_41_n183),
	.A2(mult_41_n191),
	.ZN(mult_41_n105));
   NOR2_X1 mult_41_U198 (.A1(mult_41_n183),
	.A2(mult_41_n190),
	.ZN(mult_41_n106));
   NAND2_X1 mult_41_U197 (.A1(H1[3]),
	.A2(w2_reg_out[7]),
	.ZN(mult_41_n107));
   NOR2_X1 mult_41_U196 (.A1(mult_41_n196),
	.A2(mult_41_n185),
	.ZN(mult_41_n108));
   NOR2_X1 mult_41_U195 (.A1(mult_41_n195),
	.A2(mult_41_n185),
	.ZN(mult_41_n109));
   NOR2_X1 mult_41_U194 (.A1(mult_41_n194),
	.A2(mult_41_n185),
	.ZN(mult_41_n110));
   NOR2_X1 mult_41_U193 (.A1(mult_41_n193),
	.A2(mult_41_n185),
	.ZN(mult_41_n111));
   NOR2_X1 mult_41_U192 (.A1(mult_41_n192),
	.A2(mult_41_n185),
	.ZN(mult_41_n112));
   NOR2_X1 mult_41_U191 (.A1(mult_41_n191),
	.A2(mult_41_n185),
	.ZN(mult_41_n113));
   NOR2_X1 mult_41_U190 (.A1(mult_41_n190),
	.A2(mult_41_n185),
	.ZN(mult_41_n114));
   NAND2_X1 mult_41_U189 (.A1(H1[2]),
	.A2(w2_reg_out[7]),
	.ZN(mult_41_n115));
   NOR2_X1 mult_41_U188 (.A1(mult_41_n196),
	.A2(mult_41_n186),
	.ZN(mult_41_n116));
   NOR2_X1 mult_41_U187 (.A1(mult_41_n195),
	.A2(mult_41_n186),
	.ZN(mult_41_n117));
   NOR2_X1 mult_41_U186 (.A1(mult_41_n194),
	.A2(mult_41_n186),
	.ZN(mult_41_n118));
   NOR2_X1 mult_41_U185 (.A1(mult_41_n193),
	.A2(mult_41_n186),
	.ZN(mult_41_n119));
   NOR2_X1 mult_41_U184 (.A1(mult_41_n192),
	.A2(mult_41_n186),
	.ZN(mult_41_n120));
   NOR2_X1 mult_41_U183 (.A1(mult_41_n191),
	.A2(mult_41_n186),
	.ZN(mult_41_n121));
   NAND2_X1 mult_41_U182 (.A1(H1[1]),
	.A2(w2_reg_out[7]),
	.ZN(mult_41_n123));
   NOR2_X1 mult_41_U181 (.A1(mult_41_n196),
	.A2(mult_41_n188),
	.ZN(mult_41_n124));
   NOR2_X1 mult_41_U180 (.A1(mult_41_n195),
	.A2(mult_41_n188),
	.ZN(mult_41_n125));
   NOR2_X1 mult_41_U179 (.A1(mult_41_n194),
	.A2(mult_41_n188),
	.ZN(mult_41_n126));
   NOR2_X1 mult_41_U178 (.A1(mult_41_n193),
	.A2(mult_41_n188),
	.ZN(mult_41_n127));
   NOR2_X1 mult_41_U177 (.A1(mult_41_n192),
	.A2(mult_41_n188),
	.ZN(mult_41_n128));
   NOR2_X1 mult_41_U176 (.A1(mult_41_n191),
	.A2(mult_41_n188),
	.ZN(mult_41_n129));
   NAND2_X1 mult_41_U175 (.A1(H1[0]),
	.A2(w2_reg_out[7]),
	.ZN(mult_41_n131));
   NOR2_X1 mult_41_U174 (.A1(mult_41_n195),
	.A2(mult_41_n189),
	.ZN(mult_41_n133));
   NOR2_X1 mult_41_U173 (.A1(mult_41_n194),
	.A2(mult_41_n189),
	.ZN(mult_41_n134));
   NOR2_X1 mult_41_U172 (.A1(mult_41_n193),
	.A2(mult_41_n189),
	.ZN(mult_41_n135));
   NOR2_X1 mult_41_U171 (.A1(mult_41_n192),
	.A2(mult_41_n189),
	.ZN(mult_41_n136));
   NAND2_X1 mult_41_U170 (.A1(w2_reg_out[2]),
	.A2(H1[5]),
	.ZN(mult_41_n54));
   NAND2_X1 mult_41_U169 (.A1(H1[0]),
	.A2(w2_reg_out[6]),
	.ZN(mult_41_n208));
   NAND2_X1 mult_41_U168 (.A1(w2_reg_out[2]),
	.A2(H1[4]),
	.ZN(mult_41_n207));
   NAND2_X1 mult_41_U167 (.A1(mult_41_n208),
	.A2(mult_41_n207),
	.ZN(mult_41_n63));
   XNOR2_X1 mult_41_U166 (.A(mult_41_n207),
	.B(mult_41_n208),
	.ZN(mult_41_n64));
   NOR4_X1 mult_41_U165 (.A1(mult_41_n188),
	.A2(mult_41_n189),
	.A3(mult_41_n191),
	.A4(mult_41_n190),
	.ZN(mult_41_n205));
   NOR2_X1 mult_41_U164 (.A1(mult_41_n186),
	.A2(mult_41_n190),
	.ZN(mult_41_n206));
   AOI222_X1 mult_41_U163 (.A1(mult_41_n84),
	.A2(mult_41_n205),
	.B1(mult_41_n206),
	.B2(mult_41_n84),
	.C1(mult_41_n206),
	.C2(mult_41_n205),
	.ZN(mult_41_n204));
   OAI222_X1 mult_41_U162 (.A1(mult_41_n204),
	.A2(mult_41_n187),
	.B1(mult_41_n187),
	.B2(mult_41_n184),
	.C1(mult_41_n204),
	.C2(mult_41_n184),
	.ZN(mult_41_n203));
   AOI222_X1 mult_41_U161 (.A1(mult_41_n203),
	.A2(mult_41_n74),
	.B1(mult_41_n203),
	.B2(mult_41_n76),
	.C1(mult_41_n76),
	.C2(mult_41_n74),
	.ZN(mult_41_n202));
   OAI222_X1 mult_41_U160 (.A1(mult_41_n202),
	.A2(mult_41_n179),
	.B1(mult_41_n202),
	.B2(mult_41_n182),
	.C1(mult_41_n182),
	.C2(mult_41_n179),
	.ZN(mult_41_n8));
   NAND2_X1 mult_41_U159 (.A1(w2_reg_out[5]),
	.A2(H1[6]),
	.ZN(mult_41_n86));
   NAND2_X1 mult_41_U158 (.A1(w2_reg_out[4]),
	.A2(H1[6]),
	.ZN(mult_41_n87));
   NAND2_X1 mult_41_U157 (.A1(w2_reg_out[3]),
	.A2(H1[6]),
	.ZN(mult_41_n88));
   NAND2_X1 mult_41_U156 (.A1(w2_reg_out[2]),
	.A2(H1[6]),
	.ZN(mult_41_n89));
   NAND2_X1 mult_41_U155 (.A1(w2_reg_out[1]),
	.A2(H1[6]),
	.ZN(mult_41_n90));
   NAND2_X1 mult_41_U154 (.A1(w2_reg_out[0]),
	.A2(H1[6]),
	.ZN(mult_41_n91));
   NOR2_X1 mult_41_U153 (.A1(mult_41_n180),
	.A2(mult_41_n196),
	.ZN(mult_41_n93));
   NOR2_X1 mult_41_U152 (.A1(mult_41_n180),
	.A2(mult_41_n195),
	.ZN(mult_41_n94));
   NOR2_X1 mult_41_U151 (.A1(mult_41_n180),
	.A2(mult_41_n194),
	.ZN(mult_41_n95));
   NOR2_X1 mult_41_U150 (.A1(mult_41_n180),
	.A2(mult_41_n193),
	.ZN(mult_41_n96));
   NOR2_X1 mult_41_U149 (.A1(mult_41_n180),
	.A2(mult_41_n191),
	.ZN(mult_41_n97));
   NOR2_X1 mult_41_U148 (.A1(mult_41_n180),
	.A2(mult_41_n190),
	.ZN(mult_41_n98));
   NAND2_X1 mult_41_U147 (.A1(H1[4]),
	.A2(w2_reg_out[7]),
	.ZN(mult_41_n99));
   XNOR2_X1 mult_41_U146 (.A(mult_41_n2),
	.B(mult_41_n17),
	.ZN(mult_41_n201));
   XOR2_X1 mult_41_U145 (.A(mult_41_n201),
	.B(mult_41_n15),
	.Z(mult_41_n197));
   NAND2_X1 mult_41_U144 (.A1(H1[5]),
	.A2(w2_reg_out[7]),
	.ZN(mult_41_n199));
   AND2_X1 mult_41_U143 (.A1(w2_reg_out[6]),
	.A2(H1[6]),
	.ZN(mult_41_n200));
   XOR2_X1 mult_41_U142 (.A(mult_41_n199),
	.B(mult_41_n200),
	.Z(mult_41_n198));
   XOR2_X1 mult_41_U141 (.A(mult_41_n197),
	.B(mult_41_n198),
	.Z(fb_sh[6]));
   INV_X1 mult_41_U140 (.A(w2_reg_out[2]),
	.ZN(mult_41_n192));
   INV_X1 mult_41_U139 (.A(H1[0]),
	.ZN(mult_41_n189));
   INV_X1 mult_41_U138 (.A(w2_reg_out[0]),
	.ZN(mult_41_n190));
   INV_X1 mult_41_U137 (.A(w2_reg_out[6]),
	.ZN(mult_41_n196));
   INV_X1 mult_41_U136 (.A(H1[4]),
	.ZN(mult_41_n183));
   INV_X1 mult_41_U135 (.A(w2_reg_out[1]),
	.ZN(mult_41_n191));
   INV_X1 mult_41_U134 (.A(H1[5]),
	.ZN(mult_41_n180));
   INV_X1 mult_41_U133 (.A(w2_reg_out[5]),
	.ZN(mult_41_n195));
   INV_X1 mult_41_U132 (.A(w2_reg_out[4]),
	.ZN(mult_41_n194));
   INV_X1 mult_41_U131 (.A(w2_reg_out[3]),
	.ZN(mult_41_n193));
   INV_X1 mult_41_U130 (.A(H1[3]),
	.ZN(mult_41_n185));
   INV_X1 mult_41_U129 (.A(H1[2]),
	.ZN(mult_41_n186));
   INV_X1 mult_41_U128 (.A(H1[1]),
	.ZN(mult_41_n188));
   INV_X1 mult_41_U127 (.A(mult_41_n54),
	.ZN(mult_41_n181));
   INV_X1 mult_41_U126 (.A(mult_41_n80),
	.ZN(mult_41_n187));
   INV_X1 mult_41_U125 (.A(mult_41_n66),
	.ZN(mult_41_n179));
   INV_X1 mult_41_U124 (.A(mult_41_n73),
	.ZN(mult_41_n182));
   INV_X1 mult_41_U123 (.A(mult_41_n82),
	.ZN(mult_41_n184));
   HA_X1 mult_41_U51 (.A(mult_41_n129),
	.B(mult_41_n136),
	.CO(mult_41_n83),
	.S(mult_41_n84));
   HA_X1 mult_41_U50 (.A(mult_41_n114),
	.B(mult_41_n121),
	.CO(mult_41_n81),
	.S(mult_41_n82));
   FA_X1 mult_41_U49 (.A(mult_41_n128),
	.B(mult_41_n135),
	.CI(mult_41_n83),
	.CO(mult_41_n79),
	.S(mult_41_n80));
   HA_X1 mult_41_U48 (.A(mult_41_n106),
	.B(mult_41_n113),
	.CO(mult_41_n77),
	.S(mult_41_n78));
   FA_X1 mult_41_U47 (.A(mult_41_n120),
	.B(mult_41_n134),
	.CI(mult_41_n127),
	.CO(mult_41_n75),
	.S(mult_41_n76));
   FA_X1 mult_41_U46 (.A(mult_41_n78),
	.B(mult_41_n81),
	.CI(mult_41_n79),
	.CO(mult_41_n73),
	.S(mult_41_n74));
   HA_X1 mult_41_U45 (.A(mult_41_n98),
	.B(mult_41_n105),
	.CO(mult_41_n71),
	.S(mult_41_n72));
   FA_X1 mult_41_U44 (.A(mult_41_n112),
	.B(mult_41_n133),
	.CI(mult_41_n119),
	.CO(mult_41_n69),
	.S(mult_41_n70));
   FA_X1 mult_41_U43 (.A(mult_41_n77),
	.B(mult_41_n126),
	.CI(mult_41_n72),
	.CO(mult_41_n67),
	.S(mult_41_n68));
   FA_X1 mult_41_U42 (.A(mult_41_n70),
	.B(mult_41_n75),
	.CI(mult_41_n68),
	.CO(mult_41_n65),
	.S(mult_41_n66));
   FA_X1 mult_41_U39 (.A(mult_41_n97),
	.B(mult_41_n125),
	.CI(mult_41_n111),
	.CO(mult_41_n61),
	.S(mult_41_n62));
   FA_X1 mult_41_U38 (.A(mult_41_n91),
	.B(mult_41_n118),
	.CI(mult_41_n71),
	.CO(mult_41_n59),
	.S(mult_41_n60));
   FA_X1 mult_41_U37 (.A(mult_41_n69),
	.B(mult_41_n64),
	.CI(mult_41_n62),
	.CO(mult_41_n57),
	.S(mult_41_n58));
   FA_X1 mult_41_U36 (.A(mult_41_n60),
	.B(mult_41_n67),
	.CI(mult_41_n58),
	.CO(mult_41_n55),
	.S(mult_41_n56));
   FA_X1 mult_41_U34 (.A(mult_41_n103),
	.B(mult_41_n110),
	.CI(mult_41_n124),
	.CO(mult_41_n51),
	.S(mult_41_n52));
   FA_X1 mult_41_U33 (.A(mult_41_n131),
	.B(mult_41_n117),
	.CI(mult_41_n90),
	.CO(mult_41_n49),
	.S(mult_41_n50));
   FA_X1 mult_41_U32 (.A(mult_41_n63),
	.B(mult_41_n54),
	.CI(mult_41_n61),
	.CO(mult_41_n47),
	.S(mult_41_n48));
   FA_X1 mult_41_U31 (.A(mult_41_n52),
	.B(mult_41_n59),
	.CI(mult_41_n50),
	.CO(mult_41_n45),
	.S(mult_41_n46));
   FA_X1 mult_41_U30 (.A(mult_41_n48),
	.B(mult_41_n57),
	.CI(mult_41_n46),
	.CO(mult_41_n43),
	.S(mult_41_n44));
   FA_X1 mult_41_U29 (.A(mult_41_n102),
	.B(mult_41_n181),
	.CI(mult_41_n96),
	.CO(mult_41_n41),
	.S(mult_41_n42));
   FA_X1 mult_41_U28 (.A(mult_41_n116),
	.B(mult_41_n109),
	.CI(mult_41_n123),
	.CO(mult_41_n39),
	.S(mult_41_n40));
   FA_X1 mult_41_U27 (.A(mult_41_n51),
	.B(mult_41_n89),
	.CI(mult_41_n49),
	.CO(mult_41_n37),
	.S(mult_41_n38));
   FA_X1 mult_41_U26 (.A(mult_41_n40),
	.B(mult_41_n42),
	.CI(mult_41_n47),
	.CO(mult_41_n35),
	.S(mult_41_n36));
   FA_X1 mult_41_U25 (.A(mult_41_n38),
	.B(mult_41_n45),
	.CI(mult_41_n36),
	.CO(mult_41_n33),
	.S(mult_41_n34));
   FA_X1 mult_41_U24 (.A(mult_41_n95),
	.B(mult_41_n101),
	.CI(mult_41_n108),
	.CO(mult_41_n31),
	.S(mult_41_n32));
   FA_X1 mult_41_U23 (.A(mult_41_n88),
	.B(mult_41_n115),
	.CI(mult_41_n41),
	.CO(mult_41_n29),
	.S(mult_41_n30));
   FA_X1 mult_41_U22 (.A(mult_41_n32),
	.B(mult_41_n39),
	.CI(mult_41_n37),
	.CO(mult_41_n27),
	.S(mult_41_n28));
   FA_X1 mult_41_U21 (.A(mult_41_n35),
	.B(mult_41_n30),
	.CI(mult_41_n28),
	.CO(mult_41_n25),
	.S(mult_41_n26));
   FA_X1 mult_41_U20 (.A(mult_41_n94),
	.B(mult_41_n100),
	.CI(mult_41_n107),
	.CO(mult_41_n23),
	.S(mult_41_n24));
   FA_X1 mult_41_U19 (.A(mult_41_n31),
	.B(mult_41_n87),
	.CI(mult_41_n24),
	.CO(mult_41_n21),
	.S(mult_41_n22));
   FA_X1 mult_41_U18 (.A(mult_41_n27),
	.B(mult_41_n29),
	.CI(mult_41_n22),
	.CO(mult_41_n19),
	.S(mult_41_n20));
   FA_X1 mult_41_U17 (.A(mult_41_n99),
	.B(mult_41_n93),
	.CI(mult_41_n86),
	.CO(mult_41_n17),
	.S(mult_41_n18));
   FA_X1 mult_41_U16 (.A(mult_41_n18),
	.B(mult_41_n23),
	.CI(mult_41_n21),
	.CO(mult_41_n15),
	.S(mult_41_n16));
   FA_X1 mult_41_U8 (.A(mult_41_n56),
	.B(mult_41_n65),
	.CI(mult_41_n8),
	.CO(mult_41_n7),
	.S(fb_sh[0]));
   FA_X1 mult_41_U7 (.A(mult_41_n44),
	.B(mult_41_n55),
	.CI(mult_41_n7),
	.CO(mult_41_n6),
	.S(fb_sh[1]));
   FA_X1 mult_41_U6 (.A(mult_41_n34),
	.B(mult_41_n43),
	.CI(mult_41_n6),
	.CO(mult_41_n5),
	.S(fb_sh[2]));
   FA_X1 mult_41_U5 (.A(mult_41_n26),
	.B(mult_41_n33),
	.CI(mult_41_n5),
	.CO(mult_41_n4),
	.S(fb_sh[3]));
   FA_X1 mult_41_U4 (.A(mult_41_n20),
	.B(mult_41_n25),
	.CI(mult_41_n4),
	.CO(mult_41_n3),
	.S(fb_sh[4]));
   FA_X1 mult_41_U3 (.A(mult_41_n19),
	.B(mult_41_n16),
	.CI(mult_41_n3),
	.CO(mult_41_n2),
	.S(fb_sh[5]));
endmodule

